### ISSUE TITLE
Ubuntu 16.04 Customization Failing (again)

### ISSUE THREAD

**Issue by jon-waite** [vmware/container-service-extension#101]
Just trying to refresh our Ubuntu 16.04 templates and hitting 2 failures:

1) Appears to be the same issue as https://github.com/vmware/container-service-extension/issues/73 where during customization dpkg on the temp VM gets into an inconsistent state. The fix I used previously (manually logging in to the template VM as root when the customization fails, and then running 'dpkg --configure -a' followed by 'apt install open-vm-tools' allows the customization script to continue once open-vm-tools is available in the guest.

2) After the issue in 1) has been worked around, customization then fails with an error:

The following packages will be DOWNGRADED:
  docker-ce
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 1 not upgraded.

Customization attempt #<n> failed

The temp image has docker-ce v18.06.0~ce~3-0~ubuntu installed by the customization process - which is higher than the version specified in 'cust-ubuntu-16.04.sh':

apt-get -q install -y docker-ce=18.03.0~ce-0~ubuntu

Either the cust-ubuntu-16.04.sh needs to be updated to match the current version being install by the dpkg updates, or the script needs to allow downgrades ( '--allow-downgrades' in the apt-get install lines).

**Comment by sahithi** [comment]
Can you try commenting below lines in cust-ubuntu-16.04sh and try running install again?
apt-get -q dist-upgrade -y
apt-get -q autoremove -y

Note: Before issuing install command again, dont forget to delete the ubuntu-temp manually in vCD. CSE doesn't do the rollback yet.

**Comment by sahithi** [comment]
We have incorporated a temporary workaround into the code. Suer doesn't have to do anything manual now. Fix will be coming soon
