### ISSUE TITLE
CSE ui plugin 2.0 download lin

### ISSUE THREAD

**Issue by jsingh126** [vmware/container-service-extension#1029]
Hello Team,

I am looking for a link to download the CSE UI plugin 2.0 which is used in VCD 10.2.

Thanks,
Jitendra Singh

**Comment by Anirudh9794** [comment]
Hello,
Sorry for the late reply,
PFA container ui plugin 2.0
[container-ui-plugin.zip](https://github.com/vmware/container-service-extension/files/6504731/container-ui-plugin.zip)

Thanks,
Aniruddha

**Comment by jsingh126** [comment]
Thank you for the response. We ended up upgrading the CSE where we no longer need the 2.0 plugin.
