### ISSUE TITLE
CSE 3.0.2 cluster fails only on second cluster

### ISSUE THREAD

**Issue by Garydep** [vmware/container-service-extension#1038]
Good Morning,

I am using CSE 3.0.2 with vCD 10.2.2.
On deploying a Native Cluster, the 1st one deplys with no issues, all Ubuntu and Photon works.
The second one always fails, either in the same tenant or a different tenant.
If the 1st one works in TenantA, then TenantB fails.
If i delete the cluster in TenantA, then TenantB works... but then TenantA fails.

Below is the failure i receive when deploying the second cluster:

Couldn't initialize cluster: Initialize cluster script execution failed on node ['mstr-94nu']:['\t[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.14.10: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.14.10: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.14.10: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.14.10: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.3.10: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\n']

**Comment by Anirudh9794** [comment]
Hello,
This error generally happens when there is no proper internet connectivity.
Can you please verify if you have internet access in the VM which is failing? Since this is an internet connectivity issue, can you please try creating the cluster again?

Thanks,
Aniruddha

**Comment by Anirudh9794** [comment]
Hello @Garydep ,
Can you please let us know if you were able to create a cluster in both tenants?

**Comment by Garydep** [comment]
Hello,

yes, after a long time troubleshooting, it came down to the internet connectivity as you mentioned.
Thanks for the assistance
