### ISSUE TITLE
CSE 3.0.3 errors when deploying TKGm clusters

### ISSUE THREAD

**Issue by m1gu3lg** [vmware/container-service-extension#1090]
I am using CSE 3.0.3 with vCD 10.3beta2 (vCloud API version 35.0) and version 2.3.0 of the Container UI plugin for CSE to deploy TKGm clusters. Although I have been able to deploy some clusters successfully, I am getting occasional errors when deploying the worker or the NFS nodes.

Sometimes the process fails with the following error:
21-06-30 12:21:58 | cluster_service:669 - _create_cluster_async | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: Creating 2 node(s) for cluster 'My3rdTKGmCluster' (urn:vcloud:entity:cse:nativeCluster:db402b34-d30c-4433-8dfe-0b656a2483a9)
21-06-30 12:23:26 | cluster_service:691 - _create_cluster_async | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: Adding 2 node(s) to cluster 'My3rdTKGmCluster' (urn:vcloud:entity:cse:nativeCluster:db402b34-d30c-4433-8dfe-0b656a2483a9)
21-06-30 12:24:07 | cluster_service:2286 - _execute_script_in_nodes | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: will try to execute script on mstr-lels:
#!/usr/bin/env bash
kubeadm token create --print-join-command
ip route get 1 | awk '{print $NF;exit}'

21-06-30 12:24:07 | vsphere_utils:71 - get_vsphere | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: VM ID: urn:vcloud:vm:f946db29-1ddf-4866-a2a0-b9ce1185c1e2, Hostname: espc-ornm-vcs05.orn-pc.hi.inet
21-06-30 12:24:08 | cluster_service:2296 - _execute_script_in_nodes | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for tools on mstr-lels
21-06-30 12:24:08 | cluster_service:2241 - _wait_for_tools_ready_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachine:vm-1094', status=guestToolsRunning
21-06-30 12:24:10 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for process 4121 on vm 'vim.VirtualMachine:vm-1094' to finish (1)
21-06-30 12:24:16 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: process [0, <Response [200]>, <Response [200]>] on vm 'vim.VirtualMachine:vm-1094' finished, exit code: 0
21-06-30 12:24:16 | cluster_service:2302 - _execute_script_in_nodes | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: about to execute script on mstr-lels (vm='vim.VirtualMachine:vm-1094'), wait=True
21-06-30 12:24:18 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for process 4167 on vm 'vim.VirtualMachine:vm-1094' to finish (1)
21-06-30 12:24:28 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: process [0, <Response [200]>, <Response [200]>] on vm 'vim.VirtualMachine:vm-1094' finished, exit code: 0
21-06-30 12:24:28 | cluster_service:2323 - _execute_script_in_nodes | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: 0
21-06-30 12:24:28 | cluster_service:2324 - _execute_script_in_nodes | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG ::
21-06-30 12:24:28 | cluster_service:2325 - _execute_script_in_nodes | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: kubeadm join 192.168.1.101:6443 --token 2ssce2.ahh85uepfq0l3evm     --discovery-token-ca-cert-hash sha256:95e3b11e1746c260fa0abe987e20837dbcaa0ea47593beb182d13e31fc0c242a
0

21-06-30 12:24:28 | utils:394 - read_data_file | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: Found data file: /root/.cse_scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/node.sh
21-06-30 12:24:28 | cluster_service:2286 - _execute_script_in_nodes | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: will try to execute script on node-q6f5:
#!/usr/bin/env bash
set -e
while [ `systemctl is-active docker` != 'active' ]; do echo 'waiting for docker'; sleep 5; done
kubeadm join 192.168.1.101:6443 --token 2ssce2.ahh85uepfq0l3evm --discovery-token-ca-cert-hash sha256:95e3b11e1746c260fa0abe987e20837dbcaa0ea47593beb182d13e31fc0c242a

21-06-30 12:24:29 | vsphere_utils:71 - get_vsphere | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: VM ID: urn:vcloud:vm:4e9958b8-57d0-4bd3-bea9-f6d2cb150bbd, Hostname: espc-ornm-vcs05.orn-pc.hi.inet
21-06-30 12:24:30 | cluster_service:2296 - _execute_script_in_nodes | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for tools on node-q6f5
21-06-30 12:24:30 | cluster_service:2241 - _wait_for_tools_ready_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachine:vm-1095', status=guestToolsRunning
21-06-30 12:24:32 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for process 1880 on vm 'vim.VirtualMachine:vm-1095' to finish (1)
21-06-30 12:24:38 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: process [0, <Response [200]>, <Response [200]>] on vm 'vim.VirtualMachine:vm-1095' finished, exit code: 0
21-06-30 12:24:38 | cluster_service:2302 - _execute_script_in_nodes | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: about to execute script on node-q6f5 (vm='vim.VirtualMachine:vm-1095'), wait=True
21-06-30 12:24:40 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for process 1907 on vm 'vim.VirtualMachine:vm-1095' to finish (1)
21-06-30 12:24:50 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for process 1907 on vm 'vim.VirtualMachine:vm-1095' to finish (2)
21-06-30 12:25:00 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: waiting for process 1907 on vm 'vim.VirtualMachine:vm-1095' to finish (3)
21-06-30 12:25:10 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: exception, will retry in a few seconds, vm 'vim.VirtualMachine:vm-1095'
21-06-30 12:25:10 | cluster_service:2249 - _wait_for_guest_execution_callback | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | ERROR :: exception: (vim.fault.GuestOperationsUnavailable) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The guest operations agent could not be contacted.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
21-06-30 12:25:40 | cluster_service:2236 - _join_cluster | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | ERROR :: Error executing script in node node-q6f5: process not found (pid=1907) (vm='vim.VirtualMachine:vm-1095')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2312, in _execute_script_in_nodes
    callback=_wait_for_guest_execution_callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 216, in execute_script_in_guest
    callback=callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 123, in execute_program_in_guest
    raise e
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 89, in execute_program_in_guest
    (pid, vm))
Exception: process not found (pid=1907) (vm='vim.VirtualMachine:vm-1095')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2225, in _join_cluster
    script=script)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2328, in _execute_script_in_nodes
    raise E.ScriptExecutionError(f"Error executing script in node {node_name}: {str(err)}")  # noqa: E501
container_service_extension.exceptions.ScriptExecutionError: Error executing script in node node-q6f5: process not found (pid=1907) (vm='vim.VirtualMachine:vm-1095')
21-06-30 12:25:40 | cluster_service:752 - _create_cluster_async | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | ERROR :: Error creating cluster 'My3rdTKGmCluster'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2312, in _execute_script_in_nodes
    callback=_wait_for_guest_execution_callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 216, in execute_script_in_guest
    callback=callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 123, in execute_program_in_guest
    raise e
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 89, in execute_program_in_guest
    (pid, vm))
Exception: process not found (pid=1907) (vm='vim.VirtualMachine:vm-1095')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2225, in _join_cluster
    script=script)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2328, in _execute_script_in_nodes
    raise E.ScriptExecutionError(f"Error executing script in node {node_name}: {str(err)}")  # noqa: E501
container_service_extension.exceptions.ScriptExecutionError: Error executing script in node node-q6f5: process not found (pid=1907) (vm='vim.VirtualMachine:vm-1095')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 697, in _create_cluster_async
    template[LocalTemplateKey.REVISION])
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2237, in _join_cluster
    raise E.ClusterJoiningError(f"Couldn't join cluster: {str(err)}")
container_service_extension.exceptions.ClusterJoiningError: Couldn't join cluster: Error executing script in node node-q6f5: process not found (pid=1907) (vm='vim.VirtualMachine:vm-1095')
21-06-30 12:25:41 | cluster_service:757 - _create_cluster_async | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | INFO :: Error creating cluster 'My3rdTKGmCluster'. Deleting cluster (rollback=True)
21-06-30 12:25:41 | cluster_service:1853 - _delete_vapp | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: Deleting vapp My3rdTKGmCluster in (org: TestOrg, vdc: TestOrgVDC)
21-06-30 12:26:12 | cluster_service:1869 - _delete_vapp | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | DEBUG :: Deleted vapp My3rdTKGmCluster (vdc: https://10.95.113.156/api/vdc/ea936c4d-f03e-4146-8b05-1177e490988c)
21-06-30 12:26:13 | entity_service:336 - resolve_entity | Request Id: e0ed2bfd-cf58-4f68-9468-14e16a555c31 | ERROR :: #/status: required key [nodes] not found

Whereas in other occasions the process fails with the following error:
21-06-30 13:46:16 | cluster_service:669 - _create_cluster_async | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: Creating 2 node(s) for cluster 'My5thTKGmCluster' (urn:vcloud:entity:cse:nativeCluster:13f47aa0-11f9-4bc1-baf3-fe0233a7500b)
21-06-30 13:47:32 | cluster_service:691 - _create_cluster_async | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: Adding 2 node(s) to cluster 'My5thTKGmCluster' (urn:vcloud:entity:cse:nativeCluster:13f47aa0-11f9-4bc1-baf3-fe0233a7500b)
21-06-30 13:48:13 | cluster_service:2286 - _execute_script_in_nodes | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: will try to execute script on mstr-2dbp:
#!/usr/bin/env bash
kubeadm token create --print-join-command
ip route get 1 | awk '{print $NF;exit}'

21-06-30 13:48:13 | vsphere_utils:71 - get_vsphere | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: VM ID: urn:vcloud:vm:1ea00a3b-bdbe-4e25-9889-7935c7c3d998, Hostname: espc-ornm-vcs05.orn-pc.hi.inet
21-06-30 13:48:13 | cluster_service:2296 - _execute_script_in_nodes | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: waiting for tools on mstr-2dbp
21-06-30 13:48:13 | cluster_service:2241 - _wait_for_tools_ready_callback | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachine:vm-1102', status=guestToolsRunning
21-06-30 13:48:15 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: waiting for process 4017 on vm 'vim.VirtualMachine:vm-1102' to finish (1)
21-06-30 13:48:21 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: process [0, <Response [200]>, <Response [200]>] on vm 'vim.VirtualMachine:vm-1102' finished, exit code: 0
21-06-30 13:48:21 | cluster_service:2302 - _execute_script_in_nodes | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: about to execute script on mstr-2dbp (vm='vim.VirtualMachine:vm-1102'), wait=True
21-06-30 13:48:23 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: waiting for process 4038 on vm 'vim.VirtualMachine:vm-1102' to finish (1)
21-06-30 13:48:33 | cluster_service:2247 - _wait_for_guest_execution_callback | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: process [0, <Response [200]>, <Response [200]>] on vm 'vim.VirtualMachine:vm-1102' finished, exit code: 0
21-06-30 13:48:33 | cluster_service:2323 - _execute_script_in_nodes | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: 0
21-06-30 13:48:33 | cluster_service:2324 - _execute_script_in_nodes | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG ::
21-06-30 13:48:33 | cluster_service:2325 - _execute_script_in_nodes | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: kubeadm join 192.168.200.2:6443 --token cvebl3.ro4797uttxc6knem     --discovery-token-ca-cert-hash sha256:48f2de49a1f44bce5f1f0ebb1eedde48c2df7077f7b79491d7e93ed62f715a1d
0

21-06-30 13:48:33 | utils:394 - read_data_file | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: Found data file: /root/.cse_scripts/ubuntu-20.04_tkgm-1.20_antrea-0.11_rev1/node.sh
21-06-30 13:48:33 | cluster_service:2286 - _execute_script_in_nodes | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: will try to execute script on node-r5mn:
#!/usr/bin/env bash
set -e
while [ `systemctl is-active docker` != 'active' ]; do echo 'waiting for docker'; sleep 5; done
kubeadm join 192.168.200.2:6443 --token cvebl3.ro4797uttxc6knem --discovery-token-ca-cert-hash sha256:48f2de49a1f44bce5f1f0ebb1eedde48c2df7077f7b79491d7e93ed62f715a1d

21-06-30 13:48:35 | vsphere_utils:71 - get_vsphere | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: VM ID: urn:vcloud:vm:2ec24f1e-521c-4f24-b1eb-4544e25931ff, Hostname: espc-ornm-vcs05.orn-pc.hi.inet
21-06-30 13:48:35 | cluster_service:2296 - _execute_script_in_nodes | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: waiting for tools on node-r5mn
21-06-30 13:48:35 | cluster_service:2241 - _wait_for_tools_ready_callback | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachine:vm-1105', status=guestToolsRunning
21-06-30 13:48:37 | cluster_service:2236 - _join_cluster | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | ERROR :: Error executing script in node node-r5mn: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2301, in _execute_script_in_nodes
    _wait_until_ready_to_exec(vs, vm, password)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2264, in _wait_until_ready_to_exec
    callback=_wait_for_guest_execution_callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 143, in upload_file_to_guest
    False)
  File "/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vim.fault.InvalidGuestLogin: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2225, in _join_cluster
    script=script)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2328, in _execute_script_in_nodes
    raise E.ScriptExecutionError(f"Error executing script in node {node_name}: {str(err)}")  # noqa: E501
container_service_extension.exceptions.ScriptExecutionError: Error executing script in node node-r5mn: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
21-06-30 13:48:37 | cluster_service:752 - _create_cluster_async | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | ERROR :: Error creating cluster 'My5thTKGmCluster'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2301, in _execute_script_in_nodes
    _wait_until_ready_to_exec(vs, vm, password)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2264, in _wait_until_ready_to_exec
    callback=_wait_for_guest_execution_callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 143, in upload_file_to_guest
    False)
  File "/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vim.fault.InvalidGuestLogin: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2225, in _join_cluster
    script=script)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2328, in _execute_script_in_nodes
    raise E.ScriptExecutionError(f"Error executing script in node {node_name}: {str(err)}")  # noqa: E501
container_service_extension.exceptions.ScriptExecutionError: Error executing script in node node-r5mn: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 697, in _create_cluster_async
    template[LocalTemplateKey.REVISION])
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/def_/cluster_service.py", line 2237, in _join_cluster
    raise E.ClusterJoiningError(f"Couldn't join cluster: {str(err)}")
container_service_extension.exceptions.ClusterJoiningError: Couldn't join cluster: Error executing script in node node-r5mn: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
21-06-30 13:48:37 | cluster_service:757 - _create_cluster_async | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | INFO :: Error creating cluster 'My5thTKGmCluster'. Deleting cluster (rollback=True)
21-06-30 13:48:37 | cluster_service:1853 - _delete_vapp | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: Deleting vapp My5thTKGmCluster in (org: TestOrg, vdc: TestOrgVDC)
21-06-30 13:49:09 | cluster_service:1869 - _delete_vapp | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | DEBUG :: Deleted vapp My5thTKGmCluster (vdc: https://10.95.113.156/api/vdc/ea936c4d-f03e-4146-8b05-1177e490988c)
21-06-30 13:49:09 | entity_service:336 - resolve_entity | Request Id: e0c55033-bab1-4a84-9cd0-0df79deeb809 | ERROR :: #/status: required key [nodes] not found

**Comment by arunmk** [comment]
@m1gu3lg we have seen this error a few times and this is a transient error that happens during VC load and is related to a few timing considerations. We are looking at this but a retry should unblock you. Could you please check and confirm if that is the case?

**Comment by andrew-ni** [comment]
this error seems to be a common flakiness error that we see when deploying clusters. CSE Server uses a guest operations program in the VMs, and that’s where we see this error happening.

'The guest operations agent could not be contacted.'

In our experience, the majority of cluster creations are successful; but this error is definitely the most common one we see when a cluster creation fails.

**Comment by m1gu3lg** [comment]
I confirm retrying solves the issue, but the problem is the error rate. In our case, the behavior is the opposite: approximately 80% of the cluster creation operations fail at some point (mostly when adding the worker nodes or the NFS node) with the errors reported above, while only 20% succeed.

**Comment by sahithi** [comment]
We have root-caused this issue to be particularly happening with Ubuntu 20 template. We will soon update you on the delivery of the fix.

**Comment by Anirudh9794** [comment]
Hello @m1gu3lg 

The problem happens because CSE is trying to execute some scripts on the deployed k8s node without waiting for guest customization in VCD to finish. In CSE 3.0.4. we have introduced some more wait before executing the scripts in the node.

Can you please upgrade to CSE 3.0.4 and check if cluster creation doesn't fail more often?

Thanks,
Aniruddha

**Comment by m1gu3lg** [comment]
Hi Aniruddha,
I confirm cluster creation no longer fails so often after upgrading to CSE 3.0.4. However, I found an issue when running "cse upgrade -c ./config.yaml -t -s -k /root/.ssh/id_rsa.pub" to complete the upgrade. I had both TKGm and TKGplus clusters deployed, and cse reported an error concerning the NFS node of one of the TKGplus clusters (template ubuntu-16.04_tkgplus-1.19_weave-2.6.5_vdc).

**Console message:**
Loading all CSE clusters for processing...
CSE Installation Error. Check CSE install logs
Error executing script in node nfsd-f1d1: <module 'container_service_extension.exceptions' from '/usr/local/lib/python3.7/site-packages/container_service_extension/exceptions.py'>

**CSE installation log:**
21-07-27 07:24:09 | configure_cse:1732 - _upgrade_to_35 | INFO :: Loading all CSE clusters for processing...
21-07-27 07:24:21 | configure_cse:1547 - upgrade_cse | ERROR :: CSE Installation Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/vcdbroker.py", line 2085, in _execute_script_in_nodes
    callback=_wait_for_guest_execution_callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 143, in upload_file_to_guest
    False)
  File "/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vmodl.fault.ManagedObjectNotFound: (vmodl.fault.ManagedObjectNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = "The object 'vim.ManagedEntity:None' has already been deleted or has not been completely created",
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   obj = 'vim.ManagedEntity:None'
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/configure_cse.py", line 1533, in upgrade_cse
    log_wire=log_wire)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/configure_cse.py", line 1734, in _upgrade_to_35
    clusters = get_all_cse_clusters(client=client, fetch_details=True)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/vcdbroker.py", line 1725, in get_all_clusters
    _update_cluster_dict_with_node_info(client, cluster)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/vcdbroker.py", line 1564, in _update_cluster_dict_with_node_info
    client, node_info['ipAddress'], vapp, vm_name)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/vcdbroker.py", line 1519, in _get_nfs_exports
    check_tools=False)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/vcdbroker.py", line 2101, in _execute_script_in_nodes
    raise e.ScriptExecutionError(f"Error executing script in node {node_name}: {str(e)}")  # noqa: E501
container_service_extension.exceptions.ScriptExecutionError: Error executing script in node nfsd-f1d1: <module 'container_service_extension.exceptions' from '/usr/local/lib/python3.7/site-packages/container_service_extension/exceptions.py'>
