### ISSUE TITLE
Ability to provide DNS entries

### ISSUE THREAD

**Issue by mplanquart** [vmware/container-service-extension#112]
Our potential Customers are looking to use kubectl from within their organization. In order to do this, we suggested to NAT the apiserver to an official ipv4 (via an NSX Edge running in the tenant VDC).

To use meaningful DNS names, we had to modify the mstr script (below is an example for the Photon script):
kubeadm init --kubernetes-version=v1.9.1 --apiserver-cert-extra-sans k8s1.service.net.de,k8s2.service.net.de,k8s3.service.net.de,k8s4.service.net.de > /root
/kubeadm-init.out

This is a workaround as we would prefer to use specific DNS names for every Customer.
It would be useful to have a way to pass the DNS entries from the Tenant Admin upon creation of the cluster. Maybe an option to vcd cse cluster create?

Thanks,
Marc.

**Comment by sahithi** [comment]
Thanks for the suggestion and glad you have figured out a workaround. We will add this to our backlog.
