### ISSUE TITLE
Never ending CSE tasks in VCD UI

### ISSUE THREAD

**Issue by IvanMantillaFr** [vmware/container-service-extension#1150]
Hi,
We have a task that have been running in VCD 10.2.2 from 06-02-2021, in this case we found it just because we needed to upgrade CSE server to 3.1.0, when the "CSE Upgrade" command was execute there was an error processing one of the clusters:

Processing cluster 'test2021'
Failed to upgrade cluster 'test2021'
Processing cluster 'KubeTest'
Skipping cluster 'KubeTest' since it has already been processed.
Processing cluster 'Kuberne-Test'

I could not find any related logs to that specific task but that cluster was deleted, is there a way to delete this kind of tasks in VCD?? We already try to shutdown all VCD Cells, find and delete the cluster entity (entity does not exist). what else i can do??

Thank you

**Comment by sakthisunda** [comment]
Hi,
Currently, we don't have a CSE supported mechanism to cancel VCD task.
You may want to try :
VCD supported REST API:  POST https://<VCD-SERVER-ADDRESS>/task/{id}/action/cancel
Or thru DB edit at VCD database: **https://communities.vmware.com/t5/VMware-vCloud-Director/Task-Status-in-vCD/td-p/473973**

thanks
