### ISSUE TITLE
VCD CSE OVDC LIST fails to retrieve information

### ISSUE THREAD

**Issue by IvanMantillaFr** [vmware/container-service-extension#1151]
After CSE upgrade to 3.1, Trying to run the VCD CSE OVDC LIST command, to make sure the OVDCs have been enabled correctly, the command throughs an error trying to list second page of the list
:
Name                        ID                                    K8s Runtime
--------------------------  ------------------------------------  -------------
USMIA01P-US1134362P1347237  3d68346f-60ba-4089-a9e3-ca751d3ce804  []
CLSCL01P-CH1019448P1048002  c3045d74-56c3-4716-8e61-539492eac65b  []
CAT-COBOG01P                8a98cc20-e84d-4965-b3d1-1401b60828c8  []
ALP-ARBUE01                 90423ad8-9e7b-4174-8e04-fe5b70988c8a  []
ALP                         67cf9a87-3f0e-4273-8b06-11358779b904  []
BRSPO01P-BR1950A0000001     376eabd2-7234-4860-9978-f186c94ce15d  []
BRSPO01P-CO12345P000002     4ae44ffe-23ff-4d4a-9242-6ec7759d9ba9  []
ECGYE01P-EC1970A0000002     a96390f9-68e5-4025-adf6-71f1148e1997  []
CLSCL01P-CH1019448P1047986  2f314eaa-71f6-4a0d-92f2-0b3dbf762896  []
USMIA01P-US1134362P1347883  98c652ed-1afe-4ece-a1d5-2f24b1e7f887  []
Do you want more results? [y/N]: y
Usage: vcd cse ovdc list [OPTIONS]
Try 'vcd cse ovdc list -h' for help.

Error: Invalid URL '/api/cse/3.0/orgvdcs?page=2&pageSize=10': No schema supplied                                            . Perhaps you meant http:///api/cse/3.0/orgvdcs?page=2&pageSize=10?

**Comment by sakthisunda** [comment]
After upgrade, please execute`vcd logout` and `vcd login ` at the client. This will enable the CLI to pickup and use the latest server supported API version.

This is important afte the upgrade.
