### ISSUE TITLE
Is it Necessery to add registered VCs in CSE config.yaml(including VC configured as SDDC)?

### ISSUE THREAD

**Issue by hiteshsharma0** [vmware/container-service-extension#1158]
Hello Team,

We have VCD on 10.1 release. We recently added new vcenter endpoint to the VCD as SDDC. Can you please confirm if it is mandatory to add all the VCs to the CSE config.yaml even when one of which is configured as SDDC in vCloud director. We are using CSE 2.6.1. Just for your information, we did received the following error while checking the CSE service status 

"vCenter 'XXX' registered in vCD but not found in config file
CSE Server failure. Please check the logs." 

We unregistered the new VC from the VCD and started the CSE services and it worked fine.

**Comment by ltimothy7** [comment]
Hi,

It is required to list all VC's in the config file. The reason is if a cluster is deployed on a resource pool that CSE does not know about, then CSE can't run scripts on that cluster VM.

**Comment by hiteshsharma0** [comment]
Hello ltimothy,

 

Thanks for your response. However I want to highlight that the VCenter which we have recently added to the vCloud director is not configured as a resource but it is configured as SDDC. Even if I ave no plans to run CSE cluster on that vcenter, do I still need to add it in the config.yaml file. 

 

https://docs.vmware.com/en/VMware-Cloud-Director/10.0/com.vmware.vcloud.spportal.doc/GUID-AE9A18B5-20AF-4639-9FD7-3CF5E6BFEA73.html

 

Thanks & Regards!



Hitesh Sharma
Tech Lead – L2 Solutions Team

OCB | Private Cloud Operations INDIA

CVS : 73593096

Mobile: +918376908473

***@***.*** ***@***.***> 
4th Floor, Building No 8A, DLF Cyber City, Phase II, Sector 25, Gurgaon – 122002, Haryana, India
 <http://www.orange-business.com/> www.orange-business.com

**Comment by ltimothy7** [comment]
Hi,

CSE currently does not have logic to exclude certain VC's, so this VC would currently need to be added to the config file. A feature request would be needed to implement this.

Thank you. I will close this issue, but please comment if we can be of further help.

**Comment by hiteshsharma0** [comment]
Hello ltimothy,

Thanks for providing the clarity. Since we are already using the feature of providing SDDC vcenter to our customers through vcloud director tenant, Please guide us to raise the feature request on the upcoming CSE releases.

**Comment by ltimothy7** [comment]
Hi @hiteshsharma0, you could raise a feature request by making a new Github issue with the tag: [feature request]
