### ISSUE TITLE
Unable to get the complete list of clusters after upgrading to CSE 3.1

### ISSUE THREAD

**Issue by hiteshsharma0** [vmware/container-service-extension#1250]
Hello Team,

We have recently upgrade our CSE platform from 3.0 to 3.1. After the upgrade, we observed that "vcd cse cluster list" gives only 10 clusters in the output and for the rest, it asks if we want to the complete list or not. So while pressing Y to see the complete list, we are getting the below error:-

Do you want more results? [y/N]: y
Usage: vcd cse cluster list [OPTIONS]
Try "vcd cse cluster list -h" for help.

Error: Invalid URL '/api/cse/nativeclusters?page=2&pageSize=10&org_name=neworg                                                                                  &org_name=neworg': No schema supplied. Perhaps you meant http:///api/cse/n                                                                                        ativeclusters?page=2&pageSize=10&org_name=neworg&org_name=neworg?

Can you please suggest what can be done to fix this error? Also Can you please let me know why Owner as well as k8s Runtime information is coming as NA in the same output?

**Comment by sakthisunda** [comment]
3.0 (api_version: 33.0/34.0) --> 3.1 (service-->legacy_mode: true) upgrade has got this bug reproduced. Added to our pending tasks for upcoming release.

**Comment by hiteshsharma0** [comment]
> 
> 
> @hiteshsharma0 Thanks for reaching out.
> 
>     * For now, can you please use the option: `vcd cse cluster list -A/--all` ;
> 
>     * Can you also attach/screenshot your server configuration file with anything confidential information(username,password) removed/masked.
> 
>     * This will help in investigating this.
> 
>     * Since this is an upgrade, please make sure to logout and relogin for the right client for the CLI to communitcate to the CSE server.
> 
>     * We display only those metadata of the cluster that are applicable and available. In this case, the legacy cluster does not have owner and k8 provider. K8 provider is applicable only to definied entity based cluster (https://vmware.github.io/container-service-extension/cse3_1/CSE31.html)
> 
> 
> vcd cse cluster list -h Usage: vcd cse cluster list [OPTIONS]
> 
> Display clusters in vCD that are visible to the logged in user.
> 
> Examples vcd cse cluster list Display clusters in vCD that are visible to the logged in user.
> 
> ```
>   vcd cse cluster list -vdc ovdc1
>       Display clusters in vdc 'ovdc1'.
> ```
> 
> Options: -v, --vdc VDC_NAME Filter list to show clusters from a specific org VDC `-A, --all Display all the clusters non-interactively` -o, --org ORG_NAME Filter list to show clusters from a specific org -h, --help Show this message and exit.

Thanks Sakhi for your response, 

I tried to list the clusters with -A option but the result is same. However since the no. of clusters in oVdc is less than ten, i am able to list them all for the time being. Also we have upgraded to 3.1 with supporting legacy mode and i saw you have also identified this issue as bug :) . Please let me know incase you still need config.yaml file.

**Comment by sakthisunda** [comment]
1. This is reproducible; so config.yaml is not required. Thanks
2. As a workaround for now, you may update <python-installation-folder>/site-packages/container_service_extension/client/cse_client/cse_client.py: line 88:
self._request_page_size = 10 ( increase 10 to 50 ) to see 50 clusters at a time.  
3. Then try `vcd cse cluster list -A/--all` to see all clusters

**Comment by hiteshsharma0** [comment]
Thanks, I will apply this workaround . Can you also share us the timelines regarding when can we expect this bug to be fixed?

**Comment by sakthisunda** [comment]
@hiteshsharma0: we are targeting January release which will include this fix.

**Comment by sakthisunda** [comment]
@hiteshsharma0 : Did you get a chance to apply the workaround without issues? Just checking to know. thanks

**Comment by sakthisunda** [comment]
Also for ovdc list you may see similar issue. Please apply this workaround: edit the code:
<pythonInstallation>/container_service_extension/client/cse_client/api_35/ovdc_api.py: line 21: **self._request_page_size = 10**  
( increase the above  number from 10 to 50 or ### bigger number that will be the number of ovdcs displayed in a page)

**Comment by sakthisunda** [comment]
Summary of workaround:

- /container_service_extension/client/cse_client/api_35/ovdc_api.py ( choose the self._request_page_size > actual number of ovdcs created)
- /site-packages/container_service_extension/client/cse_client/cse_client.py: ( choose the self._request_page_size > number of clusters created)
- /site-packages/container_service_extension/common/constants/shared_constants.py:
- line 89: CSE_PAGINATION_DEFAULT_PAGE_SIZE = 25 (choose this a big number larger than both number of ovdcs and clusters in the system)

**NOTE: CSE server restart required after above changes**

**Comment by hiteshsharma0** [comment]
Thanks Sakhi, we are able to list all the clusters with this workaround.
