### ISSUE TITLE
getting error "No Virtual Data Centers with Kubernetes cluster deployment capabilities" from VCD UI

### ISSUE THREAD

**Issue by hiteshsharma0** [vmware/container-service-extension#1255]
Hello Team,

We have recently upgraded VCD to 10.2.2 which gave us the opportunity to use CSE plugin 2.2.0 inbuilt with this version of VCD. Our CSE version is 3.1.0 which was upgraded to this version before upgrading VCD. While all CSE functionalities(creating new clusters, scaling existing clusters, etc) are working well using VCD cli, while leveraging the UI, we get the following error and none of the templates are displayed:-

  "No Virtual Data Centers with Kubernetes cluster deployment capabilities"  

Also while executing the compute policy list command as system administrator, we are getting no output. Is it necessary to use compute policies for templates as we have not configured it in our config.yaml file. Also please let us know if i am missed something while upgrading the CSE. I also checked the compatibility matrix and found VCD UI 2.2.0 is compatible with CSE 3.1.1 while its not clearly mentioned about 3.1.0. Can you please confirm if we are not dealing with any incompatibility here. Also I will look forward to your suggestions regarding this UI error.

**Comment by andrew-ni** [comment]
Hello,

Assuming you are trying to create "Native" clusters, can you confirm that you have enabled ovdcs for cluster deployment using CSE CLI `vcd cse ovdc enable OVDCNAME -o ORGNAME -n`

You can confirm ovdc enablement using the CSE CLI command `vcd cse ovdc list`. Also, make sure you are in the correct org context in UI as well as CLI (`vcd org use ORGNAME`)

**Comment by hiteshsharma0** [comment]
Hello, Thanks for your response.

I guess we haven't done and this option doesn't exist now. the only command option we have under ovdc is compute-policy which is showing empty when we try to list it. Please suggest how can we enable it as "vcd cse ovdc list" also shows command not found as list command is not there.

**Comment by andrew-ni** [comment]
Can you attach your CSE config file and remove the sensitive info?

**Comment by hiteshsharma0** [comment]
As suggested, Please find the config.yaml file attached. You may also find that we are not any restricting on kubernetes templates.
[config.txt](https://github.com/vmware/container-service-extension/files/7510188/config.txt)
d.

**Comment by hiteshsharma0** [comment]
Hello Andrew,

Did you get a chance to review the config file attached? How should we proceed going forward to fix this issues?

**Comment by andrew-ni** [comment]
Hi @hiteshsharma0 , sorry for the late reply. I'm asking the team; your server is running in legacy mode with 3.1.0 CSE Server on VCD 10.2.2 api35. I think the problem is still due to not having any ovdcs enabled for k8s deployment, but i'm looking into how to get the `ovdc enable` commands to show up in your CSE CLI

**Comment by rocknes** [comment]
As far as I know, if CSE server is running in legacy mode (api version < 35.0), there is no provision to enable/disable ovdc for K8s deployment. This feature was added later on for CSE running with api version 35.0 or above.

Also for CSE server running in legacy mode the correct UI plugin should be 1.x and not 2.x.

**Comment by andrew-ni** [comment]
Hey @hiteshsharma0 , here's the link to plugin v1.0.3 

https://github.com/vmware/container-service-extension/raw/master/cse_ui/1.0.3/container-ui-plugin.zip

To use this zip file, go to `More > Customize Portal` as provider. Disable the pre-existing UI plugin and upload this 1.0.3 version. Make sure you refresh the browser to see the new plugin.

Aside from that, is there a specific reason you guys are running legacy mode? We recommend running CSE Server with legacy mode false for most use cases.

**Comment by hiteshsharma0** [comment]
Hello Andrew,

I tested and it seems that the plugin v1.0.3 is working. The reason for using legacy mode is when we upgraded CSE to 3.1, we were still using VCD 10.1 but now that we have upgraded the VCD 10.2, we will plan to run CSE without legacy mode. Just for my knowledge, Is there any feature not supported in legacy mode for running native k8 clusters?

**Comment by hiteshsharma0** [comment]
> 
> 
> As far as I know, if CSE server is running in legacy mode (api version < 35.0), there is no provision to enable/disable ovdc for K8s deployment. This feature was added later on for CSE running with api version 35.0 or above.
> 
> Also for CSE server running in legacy mode the correct UI plugin should be 1.x and not 2.x.

@andrew-ni & @rocknes : Yes, I don't see that option myself in the command line. Incase we need to enable them now, how can we do it?

**Comment by andrew-ni** [comment]
Sorry for the confusion. Legacy mode CSE Server does not involve ovdc enablement. You should be able to use the CSE Server as you have been using it in VCD 10.1.

**Comment by hiteshsharma0** [comment]
Hello Andrew,

We don't want to use CSE as we did for vcd 10.1 rather we want to leverage latest features for native clusters. I did some research myself and i do agree with @rocknes that Placement policies for kubernetes runtimes are not supported in version 34.0. In order to leverage latest GUI features which are there on plugin 2.2, we have to make CSE server to use vcd API 35.0 or higher, set legacy mode to false and update the template cookbook URL. Can you please validate my understanding? Also can you please advise how can we do it with minimal maintenance window of the service?  :P

**Comment by hiteshsharma0** [comment]
Hello @andrew-ni 


We somehow manage to come out of the situation where we were not able to create clusters by upgrading CSE to non legacy mode from both cli and GUI using 2.2 vcd plugin. we are able to create new clusters now however we are not able to list or manage existing clusters. below is the error which we are received when upgrade script was trying to upgrade the clusters:-

minor_error_code=MinorErrorCode.DEFAULT_ERROR_CODE)container_service_extension.exception.exceptions.DefEntityServiceError: [ 53bf4f8d-636b-42fd-bdf1-59053e2da89d ] This operation is denied.21-11-18 12:36:34 | configure_cse:2406 - _process_non_legacy_clusters | INFO :: Processing cluster 'k6-multienv-name'21-11-18 12:36:34 | configure_cse:2434 - _process_non_legacy_clusters | ERROR :: [ b55e943a-3ec5-481a-b36a-72631b02b58e ] This operation is denied.Traceback (most recent call last):File "/usr/local/lib/python3.7/site-packages/container_service_extension/rde/common/entity_service.py", line 49, in exception_handler_wrapperresult = func(*args, **kwargs)File "/usr/local/lib/python3.7/site-packages/container_service_extension/rde/common/entity_service.py", line 327, in get_entityresource_url_relative_path=f"{CloudApiResource.ENTITIES}/"File "/usr/local/lib/python3.7/site-packages/container_service_extension/lib/cloudapi/cloudapi_client.py", line 134, in do_requestresponse.raise_for_status()File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_statusraise HTTPError(http_error_msg, response=self)requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:https://VCD_URL/cloudapi/1.0.0/entities/7314cf0b-9033-4758-9755-8dcbfb4fc875During handling of the above exception, another exception occurred:

Can you suggest how we can fix this issue so that we can list/manage old native clusters?

**Comment by rocknes** [comment]
This error is coming directly from VCD. We generally see this error if two different users were used to register the defined entity schema and create the actual defined entities that represent the cluster. This is generally a very hairy situation. 

Have you shared the proper defined entity rights to the user who owns the cluster?

**Comment by hiteshsharma0** [comment]
Hello Rocknes,

Thanks for the suggestion. The issue is resolved.
