### ISSUE TITLE
Unable to create TKG Clusters in CSE 3.1.1

### ISSUE THREAD

**Issue by sreejesh-d** [vmware/container-service-extension#1263]
Hi,
I am unable to create TKG clusters. It fails with the error in screenshot. Native Cluster deployment works fine. Am I missing something here? 
VCD 10.3.1
CSE 3.1.1
vSphere 7U2

![image](https://user-images.githubusercontent.com/21360201/143193237-2f7dcaa9-53e7-4f87-ace4-fd1c46a18c1b.png)
Tried to delete the failed cluster but the job stuck in 'DELETE:IN_PROGRESS'. Is there' a way to clean this failed entry. Tried rerun CSE, no luck. 
![image](https://user-images.githubusercontent.com/21360201/143193729-0987af2e-3ae3-4586-9f44-38585f44acdd.png)

**Comment by ltimothy7** [comment]
Hi @sreejesh-d,
We see there is an ongoing conversation about this on the cse-support channel. We will follow this conversation as well.

**Comment by sreejesh-d** [comment]
It would be an immense help if you can ping me. this is blocker for cse deployment.

**Comment by sreejesh-d** [comment]
logs are attached to the support channel thread. Please let me know if you need further details.

**Comment by ltimothy7** [comment]
This has been resolved offline.
The "Manage user's own API token" right must be added published to the org.
