### ISSUE TITLE
Unable to Delete Clusters which are not in a valid state

### ISSUE THREAD

**Issue by hiteshsharma0** [vmware/container-service-extension#1264]
Hello Team,

I am trying to delete a cluster in CSE 3.1.0 which is not in a valid state. I tried using both CLI and API however I am getting "the Cluster is not in a valid state for this operation". Please let me know how can we delete them. We are using CSE 3.1.0 with VCD 10.2.2

**Comment by Anirudh9794** [comment]
Hello Hitesh,
This is a known issue in CSE 3.1.
Could you please follow the steps in https://vmware.github.io/container-service-extension/cse3_1/KNOWN_ISSUES.html#:~:text=In%20CSE%203.1%2C%20deleting,datacenter%20and%20delete%20it to delete the clusters which are not in a valid state?

Thanks,
Aniruddha

**Comment by hiteshsharma0** [comment]
Hello Anirudh,

Yes, I am following the same procedure for deleting it via API but its still giving me "RDE_ENTITY_NOT_RESOLVED" error. I have attached the image of the API response when we try to delete the cluster using the cluster ID. Please suggest any solution as this issue has been going on for a long time.

![image](https://user-images.githubusercontent.com/71020231/144995140-02e86ef4-c066-491a-ba4a-a73994fa9e68.png)

**Comment by sakthisunda** [comment]
Hi Hitesh,
Can you please do the following steps in the order given below(resolve --> delete). Replace vcd-fqdn and cluster-id with actual values.

- Perform POST on https:/{vcd-fqdn}/cloudapi/1.0.0/entities/{cluster-id}/**resolve**
- https://vmware.github.io/container-service-extension/cse3_1/KNOWN_ISSUES.html#:~:text=In%20CSE%203.1%2C%20deleting,datacenter%20and%20delete%20it

**Comment by hiteshsharma0** [comment]
Hello Sakshi,

Thanks for your response. It worked for us.
