### ISSUE TITLE
Where can I find the password of the templates created by the cse!

### ISSUE THREAD

**Issue by amns12** [vmware/container-service-extension#1270]
After successfully create cluster, try login to the master or nodes it gives invalid credential, i used root and changeme

**Comment by Anirudh9794** [comment]
Hello,

password authentication will be disabled for the template VMs. You can supply the ssh keys during cluster creation to login to the VM.

Thanks,
Aniruddha

**Comment by Anirudh9794** [comment]
Please feel free to re-open the issue if you are not able to ssh into the VMs using ssh-keys.

**Comment by amns12** [comment]
> After successfully create cluster, try login to the master or nodes it gives invalid credential, i used root and changeme

Reopen

**Comment by rocknes** [comment]
Hi,

You can navigate to the vm in VCD UI and look at the guest customization section, if you try to edit it, a new dialog will open and it will show you the auto generated root password. Use username=root and this auto generated password to log into the node vm.

However please note that you can not log into the ubuntu vms using plain text password over ssh. So, you will need to either use a web console or vmware remote console (vmrc) (both links can be found on the vm page of VCD UI) .

Regards
Aritra Sen

**Comment by amns12** [comment]
thank you for your reply.
is there a way to SSH to ubuntu VM, unless is a kind of problem I'm having, please advice regarding SSH access.
