### ISSUE TITLE
Failed to Deploy  CSE Kubernetes Template ubuntu-16.04_k8-1.18_weave-2.6.5

### ISSUE THREAD

**Issue by sas-de** [vmware/container-service-extension#1275]
### Describe the bug

After deploy a CSE Kubernetes Template  ubuntu-16.04_k8-1.18_weave-2.6.5 weave-net pods can't be deployed.

kube-system   weave-net-grz98                     0/2     ImagePullBackOff   0          14m
kube-system   weave-net-j5kg8                     0/2     ImagePullBackOff   0          8d
kube-system   weave-net-mnwpk                     0/2     ImagePullBackOff   0          8d
kube-system   weave-net-pcn8c                     0/2     ImagePullBackOff   0          2d5h
kube-system   weave-net-pdln7                     0/2     ImagePullBackOff   0          41h
kube-system   weave-net-q74sd                     0/2     ImagePullBackOff   0          5d22h
kube-system   weave-net-rccv2                     0/2     ImagePullBackOff   0          8d

Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  14m                   default-scheduler  Successfully assigned kube-system/weave-net-grz98 to node-jo2h
  Warning  Failed     14m (x2 over 14m)     kubelet            Failed to pull image "ghcr.io/weaveworks/launcher/weave-npc:2.6.5": rpc error: code = Unknown desc = Error response from daemon: manifest unknown
  Normal   BackOff    14m (x2 over 14m)     kubelet            Back-off pulling image "ghcr.io/weaveworks/launcher/weave-npc:2.6.5"
  Warning  Failed     14m (x2 over 14m)     kubelet            Error: ImagePullBackOff
  Normal   Pulling    14m (x3 over 14m)     kubelet            Pulling image "ghcr.io/weaveworks/launcher/weave-kube:2.6.5"
  Warning  Failed     14m (x3 over 14m)     kubelet            Failed to pull image "ghcr.io/weaveworks/launcher/weave-kube:2.6.5": rpc error: code = Unknown desc = Error response from daemon: manifest unknown
  Warning  Failed     14m (x3 over 14m)     kubelet            Error: ErrImagePull
  Normal   Pulling    14m (x3 over 14m)     kubelet            Pulling image "ghcr.io/weaveworks/launcher/weave-npc:2.6.5"
  Warning  Failed     14m (x3 over 14m)     kubelet            Error: ErrImagePull
  Warning  Failed     9m44s (x20 over 14m)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    4m48s (x42 over 14m)  kubelet            Back-off pulling image "ghcr.io/weaveworks/launcher/weave-kube:2.6.5"

### Reproduction steps

```bash
1. Delete Kubernetes Container Cluster and redeploy - same error
2. T
3.
...
```

### Expected behavior

Deploy the Pods

**Comment by rocknes** [comment]
Hi,

Image pull backoff indicates that the node vms doesn't have connectivity to the container repository. This should be either a firewall rule preventing the outgoing traffic or the network the cluster is attached to doesn't have internet access.

Regards
Aritra Sen

**Comment by goelaashima** [comment]
@sas-de 

Were you able to get passed the issue.

Aashima

**Comment by goelaashima** [comment]
Weave had an issue, we have resolved it in the latest template revision version 3 - ubuntu-16.04_k8-1.18_weave-2.6.5.

Can you give it another try and let us know? If it doesn't work, you can reopen the issue.
