### ISSUE TITLE
RuntimeWarning: `NoneType` object value of non-optional type description detected when decoding DefEntityType

### ISSUE THREAD

**Issue by viveksingh2323** [vmware/container-service-extension#1280]
### Describe the bug

We have deployed CSE 3.1 and integrated with cloud director 10.3.1. Every time we execute command through vcd-cli we get a warning message shown below

(python) cse [ ~ ]$ vcd cse cluster list
/opt/cse/python/lib/python3.7/site-packages/dataclasses_json/core.py:171: RuntimeWarning: `NoneType` object value of non-optional type description detected when decoding DefEntityType.
  warnings.warn(f"`NoneType` object {warning}.", RuntimeWarning)
Name         Org            Owner          VDC               K8s Runtime    K8s Version             Status
-----------  -------------  -------------  ----------------  -------------  ----------------------  ----------------
tkgmcl04     ORG01CUSTA  cseadmin       ORGVDCCUSTA01  TKGm           TKGm v1.20.8+vmware.1   CREATE:SUCCEEDED

### Reproduction steps

```bash
Execute any command through vcd-cli e.g.
(python) cse [ ~ ]$ vcd cse cluster list
(python) cse [ ~ ]$ vcd cse cluster apply <yanlfile>
```

### Expected behavior

No warning message is expected.

**Comment by rocknes** [comment]
Hi,

We will need CSE logs to find out more on what is going on. I have a gut feeling that one of the RDE object in VCD object has incomplete data, CSE pulls it while listing all clusters and chokes while parsing the json.

Please set the following environment variable to `True`
`CSE_CLIENT_WIRE_LOGGING` before running the command, this should generate a wire log for the client in the folder ~/.cse-logs.

Regards
Aritra Sen

**Comment by aroraravneet** [comment]
[cse-client-wire.log](https://github.com/vmware/container-service-extension/files/7853497/cse-client-wire.log)

**Comment by rocknes** [comment]
Hi @aroraravneet can you please also attach cse-client-debug.log?

**Comment by viveksingh2323** [comment]
[cse-server-debug.log](https://github.com/vmware/container-service-extension/files/7867647/cse-server-debug.log)

**Comment by rocknes** [comment]
Sorry, I think you uploaded the wrong log. I want the client side debug log (it should be in folder ~/.cse-logs on the machine where the client is invoking the command).

I took a look at the wire log, and it seems to be ok. The client side debug log will have the stack trace that will help me to narrow down the problem.

Regards
Aritra Sen

**Comment by viveksingh2323** [comment]
[cse-client-debug.log](https://github.com/vmware/container-service-extension/files/7875020/cse-client-debug.log)

Uploaded correct log. Sorry for confusion

**Comment by rocknes** [comment]
Thanks, I will take a look and update.

**Comment by rocknes** [comment]
Thanks for all the logs.

The warning is stemming from the following RDE definition:
```
		"id": "urn:vcloud:type:vmware:meteringentity:1.0.0",
		"name": "MeteringEntity",
		"description": null,
```

The description string is null for this particular RDE type. 

CSE queries VCD to get all registered Defined Entity Types (this is done to figure out whether v1.0.0 or v2.0.0 of nativeCluster RDE is registered).
While casting the definition of the metering RDE type to DefEntityType Object, CSE finds the description string to be null and raise the warning.

In de_cluster.py, `__init__` method

```
        self._server_rde_version = \
            schema_svc.get_latest_registered_schema_version()
```

In schema_service.py, list_defined_entity_types method
```
            if len(response_body['values']) > 0:
                for entityType in response_body['values']:
                    yield common_models.DefEntityType.from_dict(entityType)
```

I am not sure why CSE expects all RDE type description to be non null. @sahithi  do you know why we have this restriction?

A quick workaround can be to just update the definition of metering RDE type to a non null description

As system administrator
GET /cloudapi/1.0.0/entityType/urn:vcloud:type:vmware:meteringentity:1.0.0

Copy the response, update the description field and use the updated payload for

PUT /cloudapi/1.0.0/entityType/urn:vcloud:type:vmware:meteringentity:1.0.0

**Comment by viveksingh2323** [comment]
hello, I will test this in my setup and will report the result

**Comment by viveksingh2323** [comment]
As System admin i tried API call
 GET https://<Portal FQDN>/cloudapi/1.0.0/entityType/urn:vcloud:type:vmware:meteringentity:1.0.0

but i get error message 404. For your information we did update to Cloud Director 10.3.2
{
    "minorErrorCode": "RESOURCE_NOT_FOUND",
    "message": "Resource not found",
    "stackTrace": "javax.ws.rs.ClientErrorException: HTTP 404 Not Found

**Comment by rocknes** [comment]
Sorry, small correction to the URL, it should be

GET https://Portal FQDN/cloudapi/1.0.0/entityTypes/urn:vcloud:type:vmware:meteringentity:1.0.0
PUT /cloudapi/1.0.0/entityTypes/urn:vcloud:type:vmware:meteringentity:1.0.0

notice it is entityTypes and not entityType.
Let me know if you face any other issue.

**Comment by rocknes** [comment]
Did you use some other account to register the metering defined entity?
There are some pretty strict Access Control mechanism which stops even sys admin from accessing the schema of RDE (Runtime Defined Entities)s. You will need to run the above REST calls as the user who registered the metering RDE.

**Comment by viveksingh2323** [comment]
To be frank i am not sure about metering RDE registration. How to find who did the RDE registration? Is it something which gets registered during CSE installation?

**Comment by rocknes** [comment]
No, the RDE registration for metering must have been done by the metering solution.
Ideally we should fix this from CSE, since CSE shouldn't be reading other solution's RDE. However as a workaround I was suggesting to update the metering RDE's description so that CSE stops throwing the warning.

If this is not a blocker for you/your customer, I would suggest just waiting for the proper fix in CSE's next release.
