### ISSUE TITLE
Upgrade CSE from 3.1.1 to 3.1.2 fails with "no such child: {http://www.vmware.com/vcloud/v1.5}NumCpus"

### ISSUE THREAD

**Issue by IvanMantillaFr** [vmware/container-service-extension#1297]
### Describe the bug

We updated CSE using the regular process, from 3.1.1 to 3.1.2, when we run the cse upgrade it fails with the followin error

22-02-03 13:54:23 | template_builder:57 - assign_placement_policy_to_template | INFO :: Successfully tagged template ubuntu-16.04_k8-1.21_weave-2.8.1_rev1 with placement policy native.
22-02-03 13:54:23 | configure_cse:2245 - _upgrade_to_cse_3_1_non_legacy | INFO :: Loading all CSE clusters for processing...
22-02-03 13:54:34 | configure_cse:872 - upgrade_cse | ERROR :: Failed to upgrade CSE. Check CSE install logs
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/container_service_extension/installer/configure_cse.py", line 859, in upgrade_cse
    log_wire=log_wire
  File "/root/.local/lib/python3.7/site-packages/container_service_extension/installer/configure_cse.py", line 2247, in _upgrade_to_cse_3_1_non_legacy
    clusters: List = get_all_cse_clusters(client=client, fetch_details=True)
  File "/root/.local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 1800, in get_all_clusters
    _update_cluster_dict_with_node_info(client, cluster)
  File "/root/.local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 1617, in _update_cluster_dict_with_node_info
    node_info['numberOfCpus'] = vm.VmSpecSection.NumCpus.text
  File "src/lxml/objectify.pyx", line 231, in lxml.objectify.ObjectifiedElement.__getattr__
  File "src/lxml/objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: {[http://www.vmware.com/vcloud/v1.5}NumCpus](http://www.vmware.com/vcloud/v1.5%7dNumCpus)

### Reproduction steps

```bash
1.Gracefully stop CSE Server.
2. Reinstall container-service-extension from PyPI:
pip3 install --user --upgrade container-service-extension
Check the release notes for version compatibility.
3. Use cse sample command to generate a new sample config file and fill in the relevant values from the previous config file. No changes made here.

4. If the previously generated templates are no longer supported by the new version, delete the old templates (from VCD UI / vcd-cli) and generate new ones via
cse template install -c myconfig.yaml Check here for available templates.

5. Run cse upgrade command to make the environment forward compatible.
```

### Expected behavior

Finish the upgrade process

**Comment by sakthisvmware** [comment]
We had similar issue reported by a customer before. We found out that
VM/vApp got created partially/with error state in VCD.
In that case, CSE errors out not finding cpu information while upgrading.
After investigation, the corrupted VM had to be deleted.
Ref:https://bugzilla.eng.vmware.com/show_bug.cgi?id=2863626
NOTE: Before doing that, may be power off and power on the VM.
If that does not work, we require the following files.
a) cse-install-wire_<YYYY-MM-DD_HH-MM-SS>.log
b) Server config file in plain text (unencrypted) with server information(username/password) removed
c) Please do the following steps before restarting the upgrade.
1. Set log_wire: true in server configuration file under service section.
   service: log_wire: true
2. Backup the existing log files under <home>/.cse-logs. Remove exisiting log files.
3. Rerun the upgrade again. Generate fresh cse-install-wire_<YYYY-MM-DD_HH-MM-SS>.log
4. Upload cse-install-wire_<YYYY-MM-DD_HH-MM-SS>.log(complete file), in addition to cse-install_<YYYY-MM-DD_HH-MM-SS>.log
This will help in identifying any corrupted VM/vApp. 
If you have access to VCD UI, it may help in identifying the VM that is in partially created state. Deleting it and retrying upgrade would be the next step. (edited)

**Comment by IvanMantillaFr** [comment]
In the cse-install-wire log a VM had status="FAILED_CREATION" , we deleted it from VCD and the upgrade finished successfully. Thank you for the help!!
