### ISSUE TITLE
Delete node fails with error "node not found", for an unregistered node with kubernetes 

### ISSUE THREAD

**Issue by harshneelmore** [vmware/container-service-extension#142]
When a node is created and it fails to register with kubernetes, the node is listed under cluster info but when the delete command is issued on the particular node it returns node not found.

Following is an example-  
container-service-extension username$ vcd cse node info Cluster1 node-bptj
property      value
------------  --------------
ipAddress     10.150.211.162
memoryMB      2048
name          node-bptj
node_type     node
numberOfCpus  2
status        Powered off

container-service-extension username$ vcd cse node delete Cluster1 node-bptj
Are you sure you want to delete the node(s) [y/N]: y
delete_nodes: Deleting 1 node(s) from testTwo(7789e5d3-a3a3-4d70-90dd-0ae442969d4f)
task: b86db97a-6e2d-406f-82ff-3ac6d34c8a96, result: error, message: Couldn't delete node(s):
Error from server (NotFound): nodes "node-bptj" not found

**Comment by fjmatos** [comment]
harshneelmore  Try using the force flag, this way:
$ vcd cse node delete Cluster1 node-bptj  --force
