### ISSUE TITLE
Data file not found! in v1.2.2 template update

### ISSUE THREAD

**Issue by jondwaite** [vmware/container-service-extension#145]
After upgrading cse to v1.2.2, attempting to recompose templates now results in the following output during template upgrade:

Processing template: photon-v2
Updating template
Downloading photon-custom-hw11-2.0-304b817.ova
Uploading photon-custom-hw11-2.0-304b817.ova
Find source ova 'photon-custom-hw11-2.0-304b817.ova': success
Waiting for upload to complete...........done
Creating vApp template 'photon2-temp'
**Data file not found!
Data file not found!**
vdcInstantiateVapp: Creating Virtual Application photon2-temp(59924f71-02d4-4369-a02b-14711b897ab7)
vdcInstantiateVapp: Creating Virtual Application photon2-temp(59924f71-02d4-4369-a02b-14711b897ab7)
task: e5b14395-a86d-4cf9-afda-a62c0003e4e8, Created Virtual Application photon2-temp(59924f71-02d4-4369-a02b-14711b897ab7), result: success
Customizing vApp template 'photon2-temp'
**Data file not found!
Data file not found!**

**Comment by jondwaite** [comment]
Putting some debugging into util.py this appears to be caused by [
https://github.com/vmware/container-service-extension/pull/123](url). I'm running cse in a venv, the following paths get searched by the code:

~/<venv>/bin/init-ubuntu-16.04.sh
~/<venv>/bin/scripts/init-ubuntu-16.04.sh
~/<venv>/bin/cse/init-ubuntu-16.04.sh
/usr/lib64/python36.zip/init-ubuntu-16.04.sh
/usr/lib64/python36.zip/scripts/init-ubuntu-16.04.sh
/usr/lib64/python36.zip/cse/init-ubuntu-16.04.sh
/usr/lib64/python3.6/init-ubuntu-16.04.sh
/usr/lib64/python3.6/scripts/init-ubuntu-16.04.sh
/usr/lib64/python3.6/cse/init-ubuntu-16.04.sh
/usr/lib64/python3.6/lib-dynload/init-ubuntu-16.04.sh
/usr/lib64/python3.6/lib-dynload/scripts/init-ubuntu-16.04.sh
/usr/lib64/python3.6/lib-dynload/cse/init-ubuntu-16.04.sh
~/<venv>/lib64/python3.6/site-packages/init-ubuntu-16.04.sh
~/<venv>/lib64/python3.6/site-packages/scripts/init-ubuntu-16.04.sh
~/<venv>/lib64/python3.6/site-packages/cse/init-ubuntu-16.04.sh
~/<venv>/lib/python3.6/site-packages/init-ubuntu-16.04.sh
~/<venv>/lib/python3.6/site-packages/scripts/init-ubuntu-16.04.sh
~/<venv>/lib/python3.6/site-packages/cse/init-ubuntu-16.04.sh

This was following the usual:
$ python3.6 -m venv test01
$ source ./test01/bin/activate
$ pip3 install --user vcd-cli
$ pip3 install --user container-service-extension

The actual scripts are being installed to ~/.local/cse - not sure if that's something unique on my platform (CentOS Linux) or generally where pip3 puts them, but they're not being found following this change where previously they were.

**Comment by mgaruccio** [comment]
Interesting, I'm also using a venv and on RHEL so that might narrow down the problem.

**Comment by jondwaite** [comment]
Ok, so I think I've resolved this - and it also appears to 'fix' the issue with guest customization [https://github.com/vmware/container-service-extension/issues/144](here):

```
$ python3.6 -m venv test01
$ cd test01 && source ./bin/activate
$ pip3.6 install vcd-cli
$ pip3.6 install container-service-extension
$ mkdir ./bin/scripts
$ cp ~/test01/cse/* ./bin/scripts
$ cse install -c config.yaml
```

Basically - don't use '--user' when in a python venv on CentOS 7, and you still need to manually copy the cse scripts to a location which get_data_file() in utils.py searches for them in (pretty sure this is still an issue in get_data_file, but at least this works around it for me.

**Comment by jondwaite** [comment]
Hi Andrew, I'll check what those paths evaluate to both inside and outside the venv in our environment and post back. The scripts don't get installed to `~/.local/cse` - they currently get installed to `~/<venv>/cse/` but this doesn't appear to be a location checked by get_data_file.

**Comment by jondwaite** [comment]
Without venv active:
```
>>> site.getsitepackages()
['/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']
>>> site.getusersitepackages()
'/home/cse/.local/lib/python3.6/site-packages'
>>> sys.path
['', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']
```

With venv active:
```
>>> site.getsitepackages()
['/home/cse/cse/lib64/python3.6/site-packages', '/home/cse/cse/lib/python3.6/site-packages']
>>> site.getusersitepackages()
'/home/cse/.local/lib/python3.6/site-packages'
>>> sys.path
['', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/home/cse/cse/lib64/python3.6/site-packages', '/home/cse/cse/lib/python3.6/site-packages']
```

Looks like these match up to the paths being searched by get_data_file, but don't include the folder where pip is actually creating the scripts ('/home/cse/cse/cse/' - which is actually '~/<venv>/cse/' since /home/cse is the home drive and cse is the venv too).

**Comment by andrew-ni** [comment]
PR #146 has been created to fix this issue!
