### ISSUE TITLE
vcd cse system info fails with vCD 9.5

### ISSUE THREAD

**Issue by daydrim** [vmware/container-service-extension#147]
Hello, I'm testing vCloud 9.5.0.10264774+ CSE 1.2.2 + vcd-cli 21.0.0
We an error:

$ vcd cse system info
Usage: vcd cse system info [OPTIONS]
Try "vcd cse system info -h" for help.

Error: Cannot send message to service with id: xxxxxxxx-dddd-1111-aaaa-555955555999. Check your service configuration.

It looks like with vCD 9.1 it works correctly but we need time to check with 9.1.

**Comment by mgaruccio** [comment]
You may want to check AMQP withing VCD, we're getting the same error and AMQP testing in VCD fails.  If we set the password again it works for about 5 minutes and then fails again.  Opened a ticket with VMWare last night and still awaiting a response.

**Comment by harshneelmore** [comment]
Can you provide more information about the setup?

Are any of the VCD CSE commands working after login?

Can you provide us with cse.log and vcd.log?

**Comment by daydrim** [comment]
It seems resolved with installation of dedicated RabbitMQ and configure config.yaml to use it.
