### ISSUE TITLE
Security Updates

### ISSUE THREAD

**Issue by mgaruccio** [vmware/container-service-extension#171]
Are there plans for VMWare to provide ongoing updates to CSE templates that incorporate new security updates?  Specifically for https://github.com/kubernetes/kubernetes/issues/71411 at this time but ideally every time there is a patch release?  As it stands today customers deploying clusters only get 1.10.1 with no easy way to update.

**Comment by goelaashima** [comment]
Hi There 

We have released a patch last evening on CSE to address that vulnerability - https://vmware.github.io/container-service-extension/RELEASE_NOTES.html

Please pick up latest 1.2.5 patch.

Thanks.

**Comment by mgaruccio** [comment]
I ran the updates but my nodes are still showing v1.10.1 when deploying a cluster.

**Comment by mgaruccio** [comment]
Figured this out, for anyone else running into the problem who has also applied the venv workaround from #145 you'll need to update your scripts separately before deploying the templates

**Comment by andrew-ni** [comment]
@mgaruccio Yes, if CSE scripts were moved, please delete them. `pip install container-service-extension` will download the updated scripts to your site-packages. We will include in the documentation the order of directories that CSE searches for scripts.
