### ISSUE TITLE
CSE installation from github tag fails with error in virtual environment

### ISSUE THREAD

**Issue by hodgesrm** [vmware/container-service-extension#181]
Trying to install CSE from a github tag fails with the following error when using a virtual environment.  The following commands reproduce the problem:
```
python3 -m venv cse
. cse/bin/activate
pip3 install git+https://github.com/vmware/container-service-extension.git@1.2.4
```
The command fails with the following error:
```
...
    running install_data
    creating /container_service_extension_scripts
    error: could not create '/container_service_extension_scripts': Permission denied
    
    ----------------------------------------
Command "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/9_/b6zq96vj0l3gj6v52m04rj480000gn/T/pip-req-build-k05rfgzg/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/9_/b6zq96vj0l3gj6v52m04rj480000gn/T/pip-record-o3ns9eeo/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/include/site/python3.6/container-service-extension" failed with error code 1 in /private/var/folders/9_/b6zq96vj0l3gj6v52m04rj480000gn/T/pip-req-build-k05rfgzg/
```

It looks as if setup.py has a reference to /container_service_extension_scripts on line 11 which does not function correctly in this case.  
```
  9 
 10 osl = 'open_source_license_container-service-extension_1.2.0_GA.txt'
 11 cse_scripts_dir = '/container_service_extension_scripts'
 12 
 13 setup(
```

**Comment by andrew-ni** [comment]
I'm using the commands you listed on my mac, and I can't reproduce this issue. 

The problem seems to be that you don't have permissions to create the directory 'container_service_extension_scripts' (where we download our script files to), which is weird since you're using a virtual environment.
Is there any indication of where the installation is trying to create the directory?

After running those commands, in a virtualenv **cse**, here's how my files look:
```
~/cse-test/cse/lib/python3.7/site-packages/container_service_extension
~/cse-test/cse/lib/python3.7/site-packages/container_service_extension_scripts
```

**Comment by hodgesrm** [comment]
@andrew-ni 

Interesting!  It works when I create the venv using `python3 -m virtualenv` as you suggested.  Also, as you point out there's no issue when installing from pipy.org.  I suspect setup.py is triggering a Python setuptools bug but that's just a guess.  Here are the versions on which I'm seeing the failure. 
```
(cse-doc-test) $ uname -a
Darwin rhodges-mbp.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64
(cse-doc-test) $ python3 --version
Python 3.6.6
(cse-doc-test) $ pip3 --version
pip 18.1 from /Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/pip (python 3.6)
```
Looks as if your solution is the workaround.  I'll doc this in INSTALLATION.md and close the issue.

**Comment by andrew-ni** [comment]
That's great! If anything, later we can play around with using a different method to download data files, maybe just to the project directory itself.
