### ISSUE TITLE
CSE install command failed in template creation

### ISSUE THREAD

**Issue by Vijendrasi** [vmware/container-service-extension#190]
Photon OS :

Created symlink /etc/systemd/system/iptables.service.wants/iptables-ports.service → /etc/systemd/system/iptables-ports.service.
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
curl#6: Couldn't resolve host name
Error: Failed to synchronize cache for repo 'VMware Photon Linux 2.0(x86_64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_2.0_x86_64'
curl#6: Couldn't resolve host name
Error: Failed to synchronize cache for repo 'VMware Photon Linux 2.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_2.0_x86_64'
curl#6: Couldn't resolve host name
Error: Failed to synchronize cache for repo 'VMware Photon Extras 2.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_extras_2.0_x86_64'
Error(1011) : No matching packages

Ubuntu OS :

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
curl: (6) Could not resolve host: download.docker.com
gpg: no valid OpenPGP data found.

stdout:
NOCHANGE: partition 1 is size 20744159. it cannot be grown
installing kubernetes
Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'

**Comment by Vijendrasi** [comment]
In our setup internet connection is possible only through proxy server. 

CSE VM can reach to internet using internet proxy settings but I don't know how to setup proxy setting during CSE installation in Photon and Ubuntu template creation & update.

**Comment by harshneelmore** [comment]
Hi @Vijendrasi,
Kindly upload the cse install logs, to troubleshoot the issue.

**Comment by rocknes** [comment]
We use python requests library to download the ova files from ubuntu servers. And by default we don't use assume the presence of any proxies.

The library has support for proxies, please take a look at http://docs.python-requests.org/en/latest/user/advanced/#proxies

I think setting the correct enviorment variables will do the trick, let us know.

**Comment by Vijendrasi** [comment]
Hello @rocknes 
Please let me know which file I need to update with proxy information.
CSE VM is able to reach internet but template VMs need proxy settings to reach internet.

**Comment by Vijendrasi** [comment]
I putted proxy details in cust-photon-v2.sh file :
export HTTP_PROXY="http://Proxy IP:8080/"
export HTTPS_PROXY="http://Proxy IP:8080/"

Now I am getting below error message. YY.YY.YY.Y -> DNS server and  XXX.XXX.X.XXX -> Photon-Template-VM. I am able to access https://gcr.io/v2/ from other VMs in same subnet using same DNS server and proxy details.
iting for process 1089 on vm 'vim.VirtualMachine:vm-131' to finish (22)
process [1, <Response [200]>, <Response [200]>] on vm 'vim.VirtualMachine:vm-131' finished, exit code: 1
Result: [1, <Response [200]>, <Response [200]>]
stderr:
Created symlink /etc/systemd/system/iptables.service.wants/iptables-ports.service → /etc/systemd/system/iptables-ports.service.
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /etc/systemd/system/kubelet.service.
Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on Y.YY.YY.Y:53: read udp XXX.XXX.X.XXX:49080->Y.YY.YY.Y:53: i/o timeout


stdout:
installing kuberentes
downloading container images

For Ubuntu template vm I think  export HTTP_PROXY="http://Proxy IP:8080/" command is not working.

**Comment by Vijendrasi** [comment]
On Ubuntu template I have similar issue after setting proxy settings.

root@ubuntu1604-temp:~# docker pull k8s.gcr.io/kube-apiserver-amd64:v1.10.11
Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by harshneelmore** [comment]
Once the Ubuntu/Photon images are downloaded there are scripts run inside the created VM for customizing the image as per CSE requirement which download container packages from the internet.

Make sure the network specified in config.yaml under [broker] can connect to the internet.
