### ISSUE TITLE
Configuration for multiple PVDC

### ISSUE THREAD

**Issue by mgaruccio** [vmware/container-service-extension#195]
I am working through configuring CSE in a second (of several) provider virtual datacenters.  #82 mentions being able to do this with a few tweaks but doesn't specify what the tweaks are.  Can anyone provide a list of steps/requirements to get CSE working across PVDC's?

**Comment by rocknes** [comment]
Hi Mike,

Currently when CSE is installed, it creates the necessary templates in a catalog (viz. cse) and then shares the catalog with all orgs in the cloud. 

Once installation is over, if CSE is started up with a config file that points to a different org and ovdc (by changing the broker section of the config file), CSE should still be able to access the templates from the new org and be able to deploy kubernetes cluster in the new org. And this new org can be powered by a different pvdc.

I hope this answers your question.

Regards
Aritra Sen
