### ISSUE TITLE
Error: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)

### ISSUE THREAD

**Issue by andrew-ni** [vmware/container-service-extension#219]
This error appears _sometimes_ when issuing a CSE client command (`vcd cse ...`) while CSE server is not running.

The correct output in this situation should be:
`Error: External service 'cse' failed to respond in the specified timeout (10 SECONDS)`

This bug is likely caused by vCD not finding anywhere on AMQP to put the incoming CSE client request, and returning an XML error response, as opposed to a JSON non-error response.

We are currently investigating this.

Mentioned in #196

**Comment by rocknes** [comment]
Fixed in https://github.com/vmware/container-service-extension/pull/371
