### ISSUE TITLE
DefaultBroker object has no attribute 'config'

### ISSUE THREAD

**Issue by tironside** [vmware/container-service-extension#225]
cse 1.2.6 seems to have broken then vcd cse cluster config

--- cluster info -----
C:\Users\tiron\.vcd-cli>vcd cse cluster info TONY-PHOTON
property         value
---------------  -----------------------------------------------------------------------------
cluster_id       15e0cc18-c462-406b-afb5-95d5e1797007
cse_version      1.2.6
leader_endpoint  192.168.0.150
master_nodes     {'name': 'mstr-fen4', 'ipAddress': '192.168.0.150'}
name             TONY-PHOTON
nfs_nodes
nodes            {'name': 'node-ihte', 'ipAddress': '192.168.0.152'}
                 {'name': 'node-525r', 'ipAddress': '192.168.0.151'}
number_of_vms    3
status           POWERED_ON
template         photon-v2
vapp_href        https://ode.teluscloud.com/api/vApp/vapp-34392e4c-b6ac-402c-8818-6ab8426ece42
vapp_id          34392e4c-b6ac-402c-8818-6ab8426ece42
vdc_href         https://ode.teluscloud.com/api/vdc/ab57e0f7-c3ba-445e-b41c-01693ebf5396
vdc_name         1234567890-LIDC-FP

--- cluster config ---- 
C:\Users\tiron\.vcd-cli>vcd cse cluster config TONY-PHOTON
Usage: vcd cse cluster config [OPTIONS] NAME
Try "vcd cse cluster config -h" for help.

Error: 'DefaultBroker' object has no attribute 'config'

-----  api call for same command ---

`{
    "message": {
        "reason": "'DefaultBroker' object has no attribute 'config'",
        "description": "'DefaultBroker' object has no attribute 'config'",
        "stacktrace": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.6/site-packages/container_service_extension/utils.py\", line 764, in exception_handler_wrapper\n    result = func(*args, **kwargs)\n",
            "  File \"/usr/lib/python3.6/site-packages/container_service_extension/broker.py\", line 601, in get_cluster_config\n    result['body'] = get_cluster_config(self.config, vapp,\n",
            "AttributeError: 'DefaultBroker' object has no attribute 'config'\n"
        ]
    }
}
`

checking the cse server itself

[root@PCLIDCDVCSE01 x205591]# cse check
Validating config file 'config.yaml'
Connected to AMQP server (pclidcdvamqp-vip.dv.pc.local:5672)
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director (ode.teluscloud.com:443)
Connected to vCenter Server 'pclidcdvvcr01.dv.pc.local' as 'svc_vro_vc01' (pclidcdvvcr01.dv.pc.local:443)
Config file 'config.yaml' is valid

[root@PCLIDCDVCSE01 x205591]# cse check --check-install
Validating config file 'config.yaml'
Connected to AMQP server (pclidcdvamqp-vip.dv.pc.local:5672)
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director (ode.teluscloud.com:443)
Connected to vCenter Server 'pclidcdvvcr01.dv.pc.local' as 'svc_vro_vc01' (pclidcdvvcr01.dv.pc.local:443)
Config file 'config.yaml' is valid
Validating CSE installation according to config file
AMQP exchange 'CSE' exists
CSE on vCD is currently enabled
Found catalog 'CSE_Cat'
Found template 'photon-custom-hw11-2.0-304b817-k8s' in catalog 'CSE_Cat'
Found template 'ubuntu-16.04-server-cloudimg-amd64-k8s' in catalog 'CSE_Cat'
CSE installation is valid

Clusters can create etc, just can't get the config.

Thx

**Comment by sahithi** [comment]
We are looking into this. I will give an update soon,

**Comment by rocknes** [comment]
I have created a PR to fix the issue.
https://reviewable.io/reviews/vmware/container-service-extension/227#-

It will be picked up as part of next CSE release.

However, if you want a quick fix. You can edit broker.py in your site packages to include the change mentioned in PR 227. viz. replace self.config to get_server_runtime_config().

If you are using a virtual env the file should be located at
<root of virtual env folder>\<virtual env name>\Lib\site-packages\container_service_extension\broker.py
else please look inside python installation's site package folder.

**Comment by tironside** [comment]
Thanks!

T
