### ISSUE TITLE
Error while creating cluster: VM is not ready to execute scripts

### ISSUE THREAD

**Issue by ledbsd** [vmware/container-service-extension#228]
vCloud Director 9.1.0.7905680
vcd version 21.0.2
vcd cse version 1.2.6

When run the command:

`vcd cse cluster create MyCluster --nodes 3 --cpu 1 --memory 2048 --network "lan.cse" --storage-profile "S_FAST" --ssh-key .ssh/id_rsa.pub --template ubuntu-16.04
create_cluster: Creating cluster MyCluster(bee20dbc-c79d-4960-84b7-59617e4fe4d6)
create_cluster: Creating cluster vApp MyCluster(bee20dbc-c79d-4960-84b7-59617e4fe4d6)
create_cluster: Creating master node for MyCluster(bee20dbc-c79d-4960-84b7-59617e4fe4d6)
create_cluster: Initializing cluster MyCluster(bee20dbc-c79d-4960-84b7-59617e4fe4d6)
task: 68879fb7-48a7-4f4b-9345-9a0d56498acf, result: error, message: VM is not ready to execute scripts`

cse-server-debug.log :

>19-02-11 09:12:26 | cluster:363 - execute_script_in_nodes | DEBUG :: about to execute script on mstr-lh3m (vm='vim.VirtualMachine:vm-3857'), wait=False
>19-02-11 09:12:26 | cluster:390 - execute_script_in_nodes | DEBUG :: [1350]
>19-02-11 09:12:26 | cluster:391 - execute_script_in_nodes | DEBUG ::
>19-02-11 09:12:26 | cluster:392 - execute_script_in_nodes | DEBUG ::
>19-02-11 09:12:29 | cluster:352 - execute_script_in_nodes | DEBUG :: will try to execute script on mstr-lh3m:
>#!/usr/bin/env bash
>set -e
>while [ `systemctl is-active docker` != 'active' ]; do echo 'waiting for docker'; sleep 5; done
>kubeadm init --kubernetes-version=v1.10.11 > /root/kubeadm-init.out
>mkdir -p /root/.kube
>cp -f /etc/kubernetes/admin.conf /root/.kube/config
>chown $(id -u):$(id -g) /root/.kube/config
>kubectl apply -f /root/weave.yml

>19-02-11 09:12:29 | cluster:358 - execute_script_in_nodes | DEBUG :: waiting for tools on mstr-lh3m
>19-02-11 09:12:29 | cluster:225 - wait_for_tools_ready_callback | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachine:vm-3857', status=guestToolsRunning
>19-02-11 09:12:32 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet
>19-02-11 09:12:36 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet
>...
>19-02-11 09:14:29 | broker:534 - create_cluster_thread | ERROR :: Traceback (most recent call last):
  >File "/usr/lib/python3.7/site-packages/container_service_extension/broker.py", line 478, in create_cluster_thread
    init_cluster(server_config, vapp, template)
>  File "/usr/lib/python3.7/site-packages/container_service_extension/cluster.py", line 282, in init_cluster
    script, nodes)
  >File "/usr/lib/python3.7/site-packages/container_service_extension/cluster.py", line 361, in execute_script_in_nodes
    wait_until_ready_to_exec(vs, vm, password)
>  File "/usr/lib/python3.7/site-packages/container_service_extension/cluster.py", line 334, in wait_until_ready_to_exec
    raise CseServerError('VM is not ready to execute scripts')
container_service_extension.exceptions.CseServerError: VM is not ready to execute scripts

It looks like VMTools are not available on the deployed VM. But we succes connect to the deployed VM using the ssh-key, and VMTools are running:

>**[root@localhost ~]# ssh 10.10.10.4**
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-119-generic x86_64)

> **root@mstr-lh3m:~# systemctl status open-vm-tools.service**
open-vm-tools.service - Service for virtual machines hosted on VMware
   Loaded: loaded (/lib/systemd/system/open-vm-tools.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-02-11 09:12:15 UTC; 12min ago
     Docs: http://open-vm-tools.sourceforge.net/about.php
 Main PID: 913 (vmtoolsd)
    Tasks: 1
   Memory: 13.7M
      CPU: 540ms
   CGroup: /system.slice/open-vm-tools.service
           └─913 /usr/bin/vmtoolsd

> Feb 11 09:14:24 mstr-lh3m vmsvc[913]: pam_unix(vmtoolsd:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root

**Comment by ledbsd** [comment]
if we use a white network instead of a switched network when creating templates, everything works fine.

**Comment by Hjelmar** [comment]
I have the exact same isse on a brand new installation (CSE 1.2.7 on vCD9.5)

How did you configure this in vCD?

/Kenneth

**Comment by ledbsd** [comment]
I connected the nodes to the Org VDC network with white IP-addresses (full access to the internet). After that, everything worked.
