### ISSUE TITLE
updated docker version

### ISSUE THREAD

**Issue by mgaruccio** [vmware/container-service-extension#231]
A new runc vulnerability was announced today (https://seclists.org/oss-sec/2019/q1/119) that impacts Docker-CE.  An update has been provided to the base docker-ce package as of version 18.09.02 (https://github.com/docker/docker-ce/releases) that addresses the problem.  Is it possible to get a version of CSE which leverages this docker package instead of 18.03.0 in the customization script published to PIP so we can start providing it to our customers?

**Comment by sahithi** [comment]
This is in our roadmap. Rough timeline for the updated templates (both base OS and updated versions of Docker & Kubernetes) is end of the first quarter.
