### ISSUE TITLE
RFE: CSI driver for vCloud Director independent disks

### ISSUE THREAD

**Issue by pasikarkkainen** [vmware/container-service-extension#240]
Are there currently plans to develop kubernetes CSI driver to support vcd "independent disks" -feature? It's the obvious solution for getting dynamically provisioned, persistent storage volumes properly supported in CSE and in kubernetes+vcloud in general.

Thanks a lot.

**Comment by sahithi** [comment]
Hi,

We are currently working on integrating CSE with VMware PKS and the first cut of this integration will be ready by end of April/May, 2019. PKS provides the functionality of dynamic persistent volumes and lot more. You can explore that option.

With that said, writing kubernetes cloud provider for vCD has been in the pipeline and we will re-evaluate it for the next release.

 We will update the documentation soon on latest features and what is coming.

**Comment by vitality1987** [comment]
Hi @sahithi, can you please provide an update on the plans of writing a Kubernetes Cloud Provider for vCD?

**Comment by pasikarkkainen** [comment]
yep, me too, I'm very much interested in the status of Kubernetes Cloud Provider for vCD :)

**Comment by pasikarkkainen** [comment]
ping? any news?

**Comment by f41gh7** [comment]
I`ve manage to add own implementation of CSI for vCloud: 

https://github.com/f41gh7/vcd-csi

Currently, there are some limitations ( vm naming, disk unit nums) and it`s tested only with ubuntu.

**Comment by pasikarkkainen** [comment]
@f41gh7 cool! Thanks a lot.

**Comment by jonkerj** [comment]
Hi VMWare, any update on the CSI/vCD development yet?

**Comment by minhphuoc275** [comment]
Following ....

**Comment by goelaashima** [comment]
Hello @minhphuoc275 , @jonkerj , @pasikarkkainen , @vitality1987 , @f41gh7 

The CSI driver for K8s Clusters on VCD is now available at https://github.com/vmware/cloud-director-named-disk-csi-driver. The Readme provides steps to use it. 

The CSI driver is available for use with CSE 3.1.1 and VCD 10.3.1 for TKG OVA K8s offerings. https://vmware.github.io/container-service-extension/cse3_1/CSE31.html

Let us know if you have queries. 

Best.
Aashima
