### ISSUE TITLE
create CSE cluster asking for Select a virtual data center

### ISSUE THREAD

**Issue by avnish80** [vmware/container-service-extension#247]
root@photon-machine [ ~ ]# vcd --no-wait cse cluster create firstk8s  --network T1-OrgNetwork --ssh-key ~                   /.ssh/id_rsa.pub
Usage: vcd cse cluster create [OPTIONS] NAME
Try "vcd cse cluster create -h" for help.

Error: select a virtual datacenter
<img width="903" alt="error2" src="https://user-images.githubusercontent.com/47804703/53069904-88ee3f80-3503-11e9-9345-7561b0dc07f1.png">

**Comment by ledbsd** [comment]
Have you tried it:

`vcd vdc use VDCNAME`

before "vcd cse cluster create" ?

**Comment by sahithi** [comment]
Yes, can you please try the above and see if it works?

**Comment by avnish80** [comment]
Thanks it is working
