### ISSUE TITLE
Error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by avnish80** [vmware/container-service-extension#257]
pls see attached image , when i am trying to login , getting this error.
<img width="552" alt="error" src="https://user-images.githubusercontent.com/47804703/53405751-82b60280-39de-11e9-8c69-67685d3265d6.png">

**Comment by andrew-ni** [comment]
This bug should be raised in `vcd-cli`. We can't really do anything about it here, as the vcd-cli team would have to investigate and make the fix
