### ISSUE TITLE
cse 1.2.7 cse cluster create not setting content-type header

### ISSUE THREAD

**Issue by tironside** [vmware/container-service-extension#270]
when using create cluster internally within our environment everything works fine.

same command executed on the other side of a web application firewall fails with an error "error expecting value: line 1 column 1 (char 0)"

The web application firewall logs show that the header for content-type is missing

`

[{"id"=>"960904",   "message"=>"Request Containing Content, but Missing   Content-Type header", "data"=>"Access denied with code   403 (phase 1). Match of \"rx ^0$\" against \"REQUEST_HEADERS:Content-Length\"   required."}]
--

`

the headers for the request are as follows:

`

{"Connection":"keep-alive","Zen-Host":"ZENEDGE","Accept":"application\/*+json;version=30.0","x-vcloud-authorization":"****","X-Country-Code":"BG","request-id":"2019-03-13T11:58:41Z\|878b31cd67\|212.50.27.57\|KjNAxmMJ5h","Host":"****","X-Forwarded-For":"212.50.27.57","User-Agent":"python-requests\/2.21.0","Content-Length":"218","X-Client-IP":"212.50.27.57","Accept-Encoding":"gzip,   deflate"}
--

`

Disabling the rule makes it work aok; that being said a post request should have a content-type header in it.

this is confirmed in vcd cse cluster create, but may be elsewhere, please add a header for content-type to conform to web standards

Thx

**Comment by rocknes** [comment]
Thanks a lot for pointing this out. This is indeed a bug in CSE.

https://github.com/vmware/container-service-extension/blob/32eb0fb81390eaa8c2c3d2c81de786d4c330d340/container_service_extension/client/cluster.py#L243

This should have not been set to None.

**Comment by rocknes** [comment]
Issues fixed via https://github.com/vmware/container-service-extension/pull/296
