### ISSUE TITLE
CSE won't install - TypeError: unexpected kwargs: {'ssl': False} 1.2.7

### ISSUE THREAD

**Issue by onthax** [vmware/container-service-extension#325]
New to CSE, trying to deploy and getting an error on install.

Tried using our customized config.yaml but it also fails when using the sample.

`cse install -c config.yaml  --ssh-key ~/.ssh/id_rsa.pub
Validating config file 'config.yaml'
Traceback (most recent call last):
  File "/usr/bin/cse", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/container_service_extension/cse.py", line 239, in install
    ext_install=ext_install)
  File "/usr/lib/python3.7/site-packages/container_service_extension/configure_cse.py", line 644, in install_cse
    config = get_validated_config(config_file_name)
  File "/usr/lib/python3.7/site-packages/container_service_extension/configure_cse.py", line 336, in get_validated_config
    validate_amqp_config(config['amqp'])
  File "/usr/lib/python3.7/site-packages/container_service_extension/configure_cse.py", line 383, in validate_amqp_config
    socket_timeout=5)
  File "/usr/lib/python3.7/site-packages/pika/connection.py", line 658, in __init__
    raise TypeError('unexpected kwargs: %r' % (kwargs,))
TypeError: unexpected kwargs: {'ssl': False}
`

config.yaml is just the sample, which fails a config validation check too

# cse check --config config.yaml
Validating config file 'config.yaml'
Config file 'config.yaml' is invalid

cse sample > config.yaml

`amqp:
  exchange: cse-ext
  host: amqp.vmware.com
  password: guest
  port: 5672
  prefix: vcd
  routing_key: cse
  ssl: false
  ssl_accept_all: false
  username: guest
  vhost: /

vcd:
  api_version: '29.0'
  host: vcd.vmware.com
  log: true
  password: my_secret_password
  port: 443
  username: administrator
  verify: false

vcs:
- name: vc1
  password: my_secret_password
  username: cse_user@vsphere.local
  verify: false
- name: vc2
  password: my_secret_password
  username: cse_user@vsphere.local
  verify: false

service:
  enforce_authorization: false
  listeners: 5

broker:
  catalog: cse
  cse_msg_dir: /tmp/cse
  default_template: photon-v2
  ip_allocation_mode: pool
  network: admin_network
  org: Admin
  storage_profile: '*'
  templates:
  - admin_password: guest_os_admin_password
    catalog_item: photon-custom-hw11-2.0-304b817-k8s
    cleanup: true
    cpu: 2
    description: 'PhotonOS v2

      Docker 17.06.0-4

      Kubernetes 1.9.1

      weave 2.3.0'
    mem: 2048
    name: photon-v2
    sha256_ova: cb51e4b6d899c3588f961e73282709a0d054bb421787e140a1d80c24d4fd89e1
    source_ova: http://dl.bintray.com/vmware/photon/2.0/GA/ova/photon-custom-hw11-2.0-304b817.ova
    source_ova_name: photon-custom-hw11-2.0-304b817.ova
    temp_vapp: photon2-temp
  - admin_password: guest_os_admin_password
    catalog_item: ubuntu-16.04-server-cloudimg-amd64-k8s
    cleanup: true
    cpu: 2
    description: 'Ubuntu 16.04

      Docker 18.03.0~ce

      Kubernetes 1.10.1

      weave 2.3.0'
    mem: 2048
    name: ubuntu-16.04
    sha256_ova: 3c1bec8e2770af5b9b0462e20b7b24633666feedff43c099a6fb1330fcc869a9
    source_ova: https://cloud-images.ubuntu.com/releases/xenial/release-20180418/ubuntu-16.04-server-cloudimg-amd64.ova
    source_ova_name: ubuntu-16.04-server-cloudimg-amd64.ova
    temp_vapp: ubuntu1604-temp
  type: default
  vdc: Catalog
`

Using PhotonOS 3.0

note:
get same issue with  setting to true (since we use SSL for AMQP)
ssl: true
ssl_accept_all: true

**Comment by andrew-ni** [comment]
Hello! 
This is an issue that shows up if your **pika** version is >= 1.0.0. CSE is only compatible with **pika** < 1.0.0 and >= 0.11.2.

To verify this, can you run `pip list` or `pip freeze`? (May need to do `pip3 list` or `pip3.6 list`, etc)
This will display all installed python packages and their versions. We have this change reflected in our **requirements.txt**, but the version restriction wasn't live in CSE 1.2.7.

The fix for this is to downgrade your **pika** version. The version that I am using currently is 0.13.1. Run this command and you should be good: `pip install pika==0.13.1 --upgrade`

If you're still having issues, please let us know!

**Comment by onthax** [comment]
Thanks, that has resolved it.
