### ISSUE TITLE
Neither 'init-photon-v2.sh' or 'init-ubuntu-16.04.sh' files found (CSE 2.0.0b1)

### ISSUE THREAD

**Issue by mann1mal** [vmware/container-service-extension#333]
Attempting to configure CSE 2.0 Beta (Native only, no PKS Ent) on a fresh install of vCD 9.7/vSphere 6.7/NSX-v 2.4 and the config is failing for both Photon and Ubuntu templates with the following errors:
```
***output omitted***
Uploaded 'photon-custom-hw11-2.0-304b817.ova' to catalog 'cse'
Requested data file 'init-photon-v2.sh' not found
CSE Installation Error. Check CSE install logs

***output omitted***
Uploaded 'ubuntu-16.04-server-cloudimg-amd64.ova' to catalog 'cse'
Requested data file 'init-ubuntu-16.04.sh' not found
CSE Installation Error. Check CSE install logs
```
It appears CSE can't find the scripts folder to perform the initial configuration on the nodes.
Please let me know if you need any additional information, thank you!

Config file pasted below:
```
amqp:
  exchange: systemExchange
  host: director.vcd.zpod.io
  password: VMware1!
  port: 5672
  prefix: vcd
  routing_key: cse
  ssl: false
  ssl_accept_all: false
  username: admin
  vhost: cse-host


vcd:
  api_version: '32.0'
  host: 10.96.66.133
  log: true
  password: 
  port: 443
  username: administrator
  verify: false

vcs:
- name: vcsa-1
  password: 
  username: administrator@vcd.zpod.io
  verify: false

service:
  enforce_authorization: false
  listeners: 5

broker:
  catalog: cse
  cse_msg_dir: /tmp/cse
  default_template: ubuntu-16.04
  ip_allocation_mode: pool
  network: test-external
  org: cse_org_1
  storage_profile: '*'
  templates:
  - admin_password: VMware1!
    catalog_item: photon-custom-hw11-2.0-304b817-k8s
    cleanup: true
    cpu: 2
    description: 'PhotonOS v2

      Docker 17.06.0-9

      Kubernetes 1.10.11

      weave 2.3.0'
    mem: 2048
    name: photon-v2
    sha256_ova: cb51e4b6d899c3588f961e73282709a0d054bb421787e140a1d80c24d4fd89e1
    source_ova: http://dl.bintray.com/vmware/photon/2.0/GA/ova/photon-custom-hw11-2.0-304b817.ova
   source_ova_name: photon-custom-hw11-2.0-304b817.ova
    temp_vapp: photon2-temp
  - admin_password: VMware1!
    catalog_item: ubuntu-16.04-server-cloudimg-amd64-k8s
    cleanup: true
    cpu: 2
    description: 'Ubuntu 16.04

      Docker 18.06.3~ce

      Kubernetes 1.13.5

      weave 2.3.0'
    mem: 2048
    name: ubuntu-16.04
    sha256_ova: 3c1bec8e2770af5b9b0462e20b7b24633666feedff43c099a6fb1330fcc869a9
    source_ova: https://cloud-images.ubuntu.com/releases/xenial/release-20180418/ubuntu-16.04-server-cloudimg-amd64.ova
    source_ova_name: ubuntu-16.04-server-cloudimg-amd64.ova
    temp_vapp: ubuntu1604-temp
  type: default
  vdc: cse_vdc_1

**Comment by mann1mal** [comment]
I used the following command to pulldown the CSE 2.0 Beta software:

pip3 install git+https://github.com/vmware/container-service-extension.git@2.0.0.b1

After manually using wget to pulldown the CSE 2.0 Beta bits, I was able to run the config from the directory where the archive was unpacked and the "scripts" folder existed. The script was able to proceed.

Is this expected behavior?

**Comment by andrew-ni** [comment]
Hi, could you tell us your OS, as well as your Python3 version and Pip3 version?
Also, are you using a virtual environment?
```bash
$ python3 -V # get python version
$ pip3 -V # get pip version
```

These commands are working for me on mac, with Python 3.7.3, and pip 19.1.1. 
```bash
$ pip install git+https://github.com/vmware/container-service-extension.git@2.0.0b1
$ pip install container-service-extension=2.0.0.0b1
```

After running this, I can check the `site-packages` folder for my python interpreter and see the directories `container_service_extension` and `container_service_extension_scripts`
```bash
$ which python3
/Users/niandrew/virtualenv/bin/python
$ find . -name init-ubuntu-16.04.sh
/Users/niandrew/virtualenv/lib/python3.7/site-packages/container_service_extension_scripts/init-ubuntu-16.04.sh
```

When installing `container-service-extension` via pip, CSE scripts should be placed alongside the main `container-service-extension` directory. Did you experience this issue installing other versions of CSE?

**Comment by rocknes** [comment]
Instead of using ```pip3 install git+https://github.com/vmware/container-service-extension.git@2.0.0.b1```
CSE 2.0.0.0b1 can be installed via the following command
```pip install container-service-extension --pre```

I am not sure if the installation from git branch copies the script files to site-packages or not.

**Comment by mann1mal** [comment]
Hi Andrew, thanks for the response.

I am attempting to install the CSE server on CentOS 7.6. I'm sure this is user error as I'm far from a python expert but here's what I've got:
```
# python3.7 -V
Python 3.7.3
# pip3.7 -V
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```
After running the pip3.7 install command reference in my 2nd post, I get the same behavior. Nothing present in `site-packages`
```
# which python3.7
/usr/local/bin/python3.7
# find . -name init-ubuntu-16.04.sh
**returns nothing**
```
I notice you are using a virtualenv in your setup, could that be causing issues?

**Comment by mann1mal** [comment]
Ok, quick update. Started from scratch, installed Python 3.6 in accordance with the [vcd-cli installation documentation](https://vmware.github.io/vcd-cli/install.html). Created a virtualenv.
```
$ python3 -V
Python 3.6.7
$ pip3 -V
pip 19.1.1 from /home/cse/environments/my_env/lib64/python3.6/site-packages/pip (python 3.6)
```
When attempting the following command:
```
$ pip install git+https://github.com/vmware/container-service-extension.git@2.0.0b1
```
I receive permission denied errors:
```
creating /container_service_extension_scripts
    error: could not create '/container_service_extension_scripts': Permission denied
    ----------------------------------------
ERROR: Command "/home/cse/environments/my_env/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-i23b09p5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-taldvqdx/install-record.txt --single-version-externally-managed --compile --install-headers /home/cse/environments/my_env/include/site/python3.6/container-service-extension --user --prefix=" failed with error code 1 in /tmp/pip-req-build-i23b09p5/
```
However, when I run the command @rocknes passed along, CSE is installed successfully and the scripts folder is present in `site-packages` directory:
```
$ which python3
~/environments/my_env/bin/python3
$ find . -name init-ubuntu-16.04.sh
./my_env/lib/python3.6/site-packages/container_service_extension_scripts/init-ubuntu-16.04.sh
```
Thoughts?

**Comment by andrew-ni** [comment]
That's good that one of the commands worked! 

It's strange why the git variation gives you permission denied, especially when you're using a virtual environment. After some testing on my system, using the same pip version as you, I can't reproduce this (The git variation works and correctly copies the script files).
