### ISSUE TITLE
cse service failed to start

### ISSUE THREAD

**Issue by Vijendrasi** [vmware/container-service-extension#342]
CSE version : 1.2.7
OS : Photon 3.0 
VCD : 9.5

Fail to start CSE service.
root@CSEVM01 [ /etc/systemd/system ]# systemctl status cse.service
● cse.service - Container Service Extension for VMware vCloud Director
   Loaded: loaded (/etc/systemd/system/cse.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-05-21 07:45:22 UTC; 9s ago
  Process: 370 ExecStart=/home/vmware/cse.sh (code=exited, status=203/EXEC)
 Main PID: 370 (code=exited, status=203/EXEC)

May 21 07:45:22 CSEVM01 systemd[1]: cse.service: Main process exited, code=exited, status=203/EXEC
May 21 07:45:22 CSEVM01 systemd[1]: cse.service: Failed with result 'exit-code'.
May 21 07:45:22 CSEVM01 systemd[1]: cse.service: Service RestartSec=100ms expired, scheduling restart.
May 21 07:45:22 CSEVM01 systemd[1]: cse.service: Scheduled restart job, restart counter is at 5.
May 21 07:45:22 CSEVM01 systemd[1]: Stopped Container Service Extension for VMware vCloud Director.
May 21 07:45:22 CSEVM01 systemd[1]: cse.service: Start request repeated too quickly.
May 21 07:45:22 CSEVM01 systemd[1]: cse.service: Failed with result 'exit-code'.
May 21 07:45:22 CSEVM01 systemd[1]: Failed to start Container Service Extension for VMware vCloud Director.

---------------------------------------------------------------------------------------------------
Running CSE Server Manually

root@CSEVM01 [ /home/vmware ]# cse run --config config.yaml
Validating config file 'config.yaml'
Connected to AMQP server (192.168.2.4:5672)
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director (192.168.2.14:443)
Connected to vCenter Server 'vcsa.lab65.local' as 'administrator@vsphere.local' (192.168.2.126:443)
Config file 'config.yaml' is valid
Validating CSE installation according to config file
AMQP exchange 'CSE' exists
CSE on vCD is currently enabled
Found catalog 'cse'
Found template 'photon-custom-hw11-2.0-304b817-k8s' in catalog 'cse'
Found template 'ubuntu-16.04-server-cloudimg-amd64-k8s' in catalog 'cse'
CSE installation is valid
Container Service Extension for vCloudDirector
Server running using config file: config.yaml
Log files: cse-logs/cse-server-info.log, cse-logs/cse-server-debug.log
waiting for requests (ctrl+c to close)

root@CSEVM01 [ /home/vmware ]# nohup cse run --config config.yaml > nohup.out 2>&1 &
[1] 445

root@CSEVM01 [ /home/vmware ]# cat cse.sh
#!/usr/bin/env bash
cse run --config /home/vmware/config.yaml

root@CSEVM01 [ /etc/systemd/system ]# cat cse.service
[Unit]
Description=Container Service Extension for VMware vCloud Director
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/home/vmware/cse.sh
Type=simple
User=root
WorkingDirectory=/home/vmware
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by sahithi** [comment]
Can you execute the commands in 'cse.service' and 'cse.sh' one by one and see at which command is it exactly failing?

**Comment by Vijendrasi** [comment]
Thanks Sahithi, It was permission issue for cse.sh and cse.service.
