### ISSUE TITLE
CSE 2.0 require Python version 3.7.3 or greater

### ISSUE THREAD

**Issue by Vijendrasi** [vmware/container-service-extension#349]
I am installing CSE 2.0 on Photon OS 2.0, It required Python 3.7.3 and currently 3.6.5 installed. Please let me know how to upgrade it require version.

root@photon-machine [ /home/vmware ]# python3 --version
Python 3.6.5

cse sample > config.yaml
>>
Required Python version: >= 3.7.3
Installed Python version: 3.6.5 (default, Mar 14 2019, 13:20:37)
[GCC 6.3.0]
Python version should be 3.7.3 or greater

**Comment by sahithi** [comment]
Can you try below?
    $ tdnf install -y build-essential python3-setuptools python3-tools python3-pip python3-devel

**Comment by Vijendrasi** [comment]
tdnf install -y build-essential python3-setuptools python3-tools python3-pip python3-devel
Package build-essential is already installed.
Package python3-setuptools is already installed.
Package python3-tools is already installed.
Package python3-pip is already installed.
Package python3-devel is already installed.
Nothing to do.
---------------------------------------------------------------------------------------
Today I installed Photon OS 3.0 and try to install CSE 2.0 on it but same result.

root@CSEVM200 [ /home/vmware ]# cse sample > config.yaml
root@CSEVM200 [ /home/vmware ]# cat config.yaml
Required Python version: >= 3.7.3
Installed Python version: 3.7.0 (default, May 29 2019, 20:01:38)
[GCC 7.3.0]
Python version should be 3.7.3 or greater
--------------------------------------------------------------------------------------
I am very surprise to see there is no reference mentioned in the documents. Is any one tested CSE 2.0 in Photon OS or not ?
