### ISSUE TITLE
2.0 upgrade path

### ISSUE THREAD

**Issue by mgaruccio** [vmware/container-service-extension#363]
with 2.0 released I have been testing in my lab and found that once 2.0 is deployed and templates are updated customers no longer have the ability to deploy new nodes into their existing clusters due to the node having the 1.13 components installed while the control plane is 1.10.  Ideally we would tell customers to update their master nodes to 1.13 before we made the switch but 1.13 is not compatible with 1.10 workers (see k8s [version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/))

Is there a documented procedure for upgrading from 1.2.7 to 2.0.0 without loss of functionality at the customer side?

**Comment by mgaruccio** [comment]
So I've dug into this a bit more and it seems like the best option would be if we can co-exist both 1.27 and 2.0 on the same VCD.  This would actually be pretty easy for the server component since it seems we could just change the service name in server_constants.py but I don't see a similar way to modify the client config to point to a different url path, can anyone provide guidance here?

**Comment by sahithi** [comment]
Hi,

The ability to retain older templates is coming as part of next CSE release.

For now, there is one workaround possible. We have not tested this, but it should work.

1. Before you run CSE 2.0 installation, rename the catalog_items to something else so that they will not get overwritten. For example, rename catalog_item from "ubuntu-16.04-server-cloudimg-amd64-k8s" to "ubuntu-16.04-server-cloudimg-amd64-k8s-**old**".

2. Depending on the need to use any particular template, you will have to change the template name back to what CSE expects. CSE expects to have catalog_items with the names given in config.yaml

Hope this helps. Let us know if you hit any issues.

**Comment by mgaruccio** [comment]
Ok, so if we followed that procedure we would keep the old templates but wouldn't be able to make the new templates available to our clients correct?

Is there a timeline for the next release?  1.10 is EOL and we have customers anxious to update to a new version but we can't make it available until we can do so without breaking existing clusters.

**Comment by sahithi** [comment]
No, you will be able to use both old and new. It’s just that admin has to do this additional step of ensuring that active template in vCD UI matches with the what client wants to use.

Say, with the step-1 mentioned in my previous comment, vcd catalog would have
1. Ubuntu-16.04.....k8s_old
2. Ubuntu-16.04.....k8s 
3. Photon.................k8s_old
4. Photon................k8s

As CSE identifies templates by their name mentioned in config.yaml, the active templates in the above setup are (2) and (4), which are actually newer ones.

Now, if you want to switch back to older templates, rename (2) and (4) to something else and bring back (1) and (3) to what CSE expects.

**Comment by mgaruccio** [comment]
That would allow us to swap between the two template versions quickly but still wouldn't allow us to actually change the templates out for 1.13 without breaking CSE for everyone who is still on 1.10.  This is a self-service platform so clients don't have to coordinate their cluster/node deployments with us and we would have no way to switch the templates out for them before they ran a deploy. 

Is there any timeline for a release that will allow for selecting k8s version/template at deploy time?  If not is there any possibility of a stopgap release that deploys 1.12 so we can get customers onto a supported release and begin setting them up for a future migration to 1.13?

**Comment by goelaashima** [comment]
Hi Mike

We are hopeful on bringing the feature out soon with which you will have the capability to use old and new templates. We realize the importance of this capability. 

I can't comment on the timelines yet. We have just started the work.

Aashima

**Comment by mgaruccio** [comment]
Has there been any progress on this?  Our customers complaining about the EOL version of k8s and I need to know if there will be an upgrade path for CSE soon or if we need to start implementing another solution.

**Comment by goelaashima** [comment]
Mike

Which CSE templates are prominently used in your environment - Photon or Ubuntu?

Our plan is to have update templates with revised K8s version in our next CSE release, with which you can deploy new container clusters.

Aashima

**Comment by mgaruccio** [comment]
Our users are primarily on Ubuntu due to the feature lag with Photon, but a new k8s version doesn't solve the problem of needing an upgrade path from 1.27 to 2.0, as it stands if we deploy any updated version we break management for all of our existing clusters

**Comment by rocknes** [comment]
Hi Mike, 

I sense there are two asks,
1. Upgrade CSE to newer version while retaining management of clusters running k8s version 1.12 and below,
2. Eventually upgrade k8s for clusters *in place*, given most of the old k8s versions are being deprecated.

Let me know if I am missing something.
In place k8s upgrade is not on our road map right now, and won't be addressed anytime soon.

For #1, in the next CSE release we are revamping template life cycle management. We will have the inbuilt capability to host multiple templates simultaneously  (even with different versions of k8s on the same base os). Out of box we won't define the templates with older k8s versions, but we can always work together to get you the necessary old template definitions to you, so that your customers can continue to manage their clusters running old k8s. Let me know if you have any other ask,

**Comment by mgaruccio** [comment]
@rocknes 

automating the in place upgrade isn't all that important to us, all we really need to enable a clean upgrade path is the ability to deploy templates that don't skip versions of k8s.  So ideally we need 1.10, 1.11, 1.12 and 1.13 templates available so that clients can upgrade their masters with kubeadm and then begin deploying new nodes with a matching version while removing old nodes on the previous version.   as it stands right now if a client upgrades their master nodes to 1.13 their worker nodes are unsupported since they don't meet the version skew policy.  

At this point I would settle for a stopgap release that deploys 1.12 instead of 1.13 so we can instruct our customers to upgrade to that version before we deploy the upgrade, then once all workers are at that level we can upgrade to 1.13. That's still far too high-touch to be acceptable as an ongoing approach to managing version skew but it would at least let us work with our existing clients to get them moved off of their EOL software without requiring cluster migrations.

It would also be helpful if you can share a roadmap/commitment to performing a new release every quarter with an updated k8s version so we can reassure our customers that this won't happen again as it is rather disruptive to their operations.

**Comment by rocknes** [comment]
The whole template rework is for the goal of being able to release updated k8s quarterly. :)
I will get back to you with a roadmap, after I discuss it with management.

But we should be able to get you the 1.12 template as soon as the next CSE version is released.

**Comment by mgaruccio** [comment]
That's great to hear, any update you can give me on timelines for the next release would be great.

Thanks!

**Comment by goelaashima** [comment]
Hi Mike

We are planning our next release to be sometime in October. We also have every intention to keep up with new K8s version releases via new templates. 

If I could pick your brain on the upgrades little bit - do you make any prescriptive documentation available to your customers / tenants on how they should upgrade K8s clusters, covering what-to, how-to? Or, they are expected to self-serve.

Thank you for partnering, Mike. Much appreciated.
Aashima

**Comment by mgaruccio** [comment]
Right now our support teams are working with individual customers to plan their migrations but we would like to be able to provide them more standardized documentation once we know what the upgrade path will look like.  To that end please let me know when there is alpha/beta code available with 1.12 templates and the ability to select one at cluster creation time.

**Comment by goelaashima** [comment]
Mike, we will reach out to you when we approach that milestone. First week of Sept is the target right now, if all goes well.

**Comment by andrew-ni** [comment]
Hi @mgaruccio , we're currently looking into this.

From our understanding, Kubernetes clusters can only upgrade by 1 minor version at a time (1.10 -> 1.11, but NOT 1.10 -> 1.12). This standard cluster upgrade info is described by Kubernetes [HERE](https://v1-12.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/#upgrade-kubelet-on-each-node). From this page, it seems like clusters can and should be upgraded without adding any additional higher-versioned nodes.
Upgrade path recommended by Kubernetes:
[1.10 -> 1.11](https://v1-12.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/#upgrade-kubelet-on-each-node)
[1.11 -> 1.12](https://v1-12.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-12/)
[1.12 -> 1.13](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-13/)
[1.13 -> 1.14](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-14/)
[1.14 -> 1.15](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/)

For example, a 1.10 cluster should be upgraded to 1.11 by `kubeadm upgrade`ing the master and worker nodes. The resulting 1.11 cluster can be upgraded to 1.12 via the same method. The only use case we're seeing for CSE templates that support more minor versions of Kubernetes would be to add nodes to clusters that are already the desired version.

We're a little wary about providing templates for deprecated (or soon-to-be deprecated) versions of Kubernetes, especially if these templates are not needed to upgrade a cluster.

We're wondering if you could describe the upgrade methods that you've tried so far, and if you have a use case for your clusters that we're not thinking about?

**Comment by mgaruccio** [comment]
@andrew-ni worker/master version skew can be up to 2 minor versions, as detailed in the k8 docs [here](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubelet).  

As for use case, we are attempting to provide our customers with an upgrade path that can be orchestrated from the CSE layer.  We're talking about clusters with dozens or hundreds of nodes so asking our customers to perform individual upgrades with kubeadm on each node is asking a lot and removes a lot of the value proposition of using a tool like CSE to manage their machines.  The upgrade path we would like to offer would be to use kubeadm to upgrade the master node and then use CSE to perform rolling upgrades of the cluster by adding nodes with the new version while removing old nodes.  

The bigger issue however is that as soon as we apply an upgrade every existing cluster loses the ability to deploy new nodes, so if customer A performs an upgrade on their master node and requests an updated k8s version we can't provide it to them until every other customer has also upgraded their clusters to the latest version.  With a quarterly release cycle that ends up being a massive amount of coordination with customers for what is intended to be a largely self-service platform.

An even bigger problem with this particular release is that there is no clean path to even request that our customers upgrade, as soon as they move onto 1.13 they lose the ability to add new nodes since they are 1.10 until we upgrade, so we essentially need to get every customer to upgrade all of their clusters on the same night or accept that their clusters are orphaned until they can perform the upgrade. 

However with the recent High severity CVE's released for k8s we have been able to work with our customers to get them accept this disruptive upgrade process as necessary to get them a non-vulnerable platform, but we have now been told that there is not going to be a patch release for the 1.13 based templates and we will need to wait for the next release with 1.15 to have the security fixes available.  If we could get a patch release that bumps the hotfix version to 1.13.10 we would at least be able to bring our customers up to that version, but I'm concerned based on release schedules that the next release with a new minor version will be on 1.16 and we will be back to asking customers to perform disruptive upgrades again.

**Comment by rocknes** [comment]
Hi Mike (@mgaruccio)

With the next release of CSE, we will have the following templates out of box
Ubuntu with k8s 1.13.5
Ubuntu with k8s 1.15.3
Photon with k8s  1.12.7
Photon with k8s 1.14.x (tentative, depends on photon supporting k8s 1.14)

Btw the 1.15.3 ubuntu template will be available by the end of first week of September with the early access build that we will provide you.

We are also working on getting the Ubuntu with k8s 1.12.x template for just you.

We verified that we can upgrade an api server from v1.10 to v1.12 (had to force the 1.11 -> 1.12 transition) with 1.10 kublets on the workers. So your plan to upgrade your customers to k8s 1.15.3 is possible as early as September. Once your cluster is on 1.12, you can upgrade the master to 1.13 and use the out of box templates to get the 1.13 worker nodes. Subsequently you can follow the same process to get the whole cluster to 1.15.3.

Going forward with subsequent versions of CSE you will be able to retain older templates alongside newer templates, so it will be possible for your customers to stay on different versions of k8s and still manage to expand their clusters. And if they ever wish to upgrade, they will have the option do something like what you are planning now, and the templates to let them do so will be there.

On a separate note, I had a question regarding the whole operation, is it possible for your customer to downsize the clusters to just the master node, upgrade kube-api-server from 1.10 to 1.15 and then re-add the nodes back? I know this will cause service downtime, but by doing so we can avoid the hassle of doing the rolling upgrade thrice (1.10->1.12, 1.12->1.13, and 1.13->1.15).

With the new version of CSE, the cluster structure/representation in vCD has changed, so to be able to manage clusters deployed by CSE 2.0.0 and below, we need to prep them (read as adding metadata + representational changes that need a power cycle). Given that to manage older clusters via next release of CSE, we need the downtime, can't the same downtime be used to drain the nodes?

Regards
Aritra Sen

**Comment by rocknes** [comment]
Hi Mike @mgaruccio 

We have released CSE 2.5.0 beta 1 on pypi.org. 
Did you get a chance to review my proposal in the last update?
Do you still need those 1.12 k8s based templates? If yes, please share an email id with us, where we can send you the steps required to create the templates.

Regards
Aritra Sen

**Comment by mgaruccio** [comment]
Apologies for the delay responding here.   We were able to upgrade to 2.5 but the majority of our clients on the platform decided to just do a migration to a new cluster since that is less disruptive than powering down the entire cluster while it is running.
