### ISSUE TITLE
systemctl status systemd-modules-load.service failed

### ISSUE THREAD

**Issue by mohdimk** [vmware/container-service-extension#389]
root@photon-machine [ ~ ]# systemctl status systemd-modules-load.service
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Tue 2019-07-23 12:47:31 UTC; 13min ago
           ├─ ConditionDirectoryNotEmpty=|/lib/modules-load.d was not met
           ├─ ConditionDirectoryNotEmpty=|/usr/lib/modules-load.d was not met
           ├─ ConditionDirectoryNotEmpty=|/usr/local/lib/modules-load.d was not met
           ├─ ConditionDirectoryNotEmpty=|/etc/modules-load.d was not met
           ├─ ConditionDirectoryNotEmpty=|/run/modules-load.d was not met
           ├─ ConditionKernelCommandLine=|modules-load was not met
           └─ ConditionKernelCommandLine=|rd.modules-load was not met
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
root@photon-machine [ ~ ]#

**Comment by rocknes** [comment]
I am not sure how this is related to container service extension. Can you please elaborate?

**Comment by rocknes** [comment]
Closing issue. Since I don;t believe this is related to CSE.
