### ISSUE TITLE
CSE on vCD

### ISSUE THREAD

**Issue by omairkca** [vmware/container-service-extension#420]
HI EveryOne,

I am install a CSE on vCD after installation CSE unable to create cluster below mention error and unable to view Container extension on vCD.
[root@nfs bin]# ./vcd login 172.16.10.181 System administrator --password cyber99 -w -i
administrator logged in, org: 'System', vdc: 'cse'
[root@nfs bin]# ./vcd org use Catalog
now using org: 'Catalog', vdc: 'Catalog', vApp: ''.
[root@nfs bin]# ./vcd vdc use Catalog
now using org: 'Catalog', vdc: 'Catalog', vApp: ''.
[root@nfs bin]# ./vcd cse cluster create abc
create_cluster: Creating cluster abc(9eaf3fe7-aea3-431c-969a-7b152962126d)
task: 41b6dd87-c700-4f2c-8473-80efd1973fc1, result: error, message: VDC initialization failed as arguments are either invalid or None

Regards,
Muhammad Omair Ahmed

**Comment by andrew-ni** [comment]
Please check out the `cluster create` cli options using `vcd cse cluster create -h`.
For native (vCD) clusters, `--network` is required. 

If you're still running into issues, please post your vCD version, CSE version (`cse version` and `vcd cse version`), as well as your pyvcloud version `pip list | grep pyvcloud`

**Comment by omairkca** [comment]
Below mention the all output 

[root@nfs bin]# ./vcd cse cluster create -h
Usage: vcd cse cluster create [OPTIONS] NAME

  Create a Kubernetes cluster.

Options:
  -v, --vdc VDC_NAME          Org VDC to use. Defaults to currently logged-in
                              org VDC
  -N, --nodes INTEGER         Number of nodes to create
  -c, --cpu INTEGER           Number of virtual CPUs on each node (Exclusive
                              to native Kubernetes provider)
  -m, --memory INTEGER        Megabytes of memory on each node (Exclusive to
                              native Kubernetes provider)
  -n, --network TEXT          Network name (Exclusive to native Kubernetes
                              provider) (Required)
  -s, --storage-profile TEXT  Name of the storage profile for the nodes
                              (Exclusive to native Kubernetes provider)
  -k, --ssh-key FILENAME      SSH public key to connect to the guest OS on the
                              VM (Exclusive to native Kubernetes provider)
  -t, --template TEXT         Name of the template to instantiate nodes from
                              (Exclusive to native Kubernetes provider)
  --enable-nfs                Create an additional NFS node (Exclusive to
                              native Kubernetes provider)
  --disable-rollback          Disable rollback on failed cluster creation
                              (Exclusive to native Kubernetes provider)
  -o, --org ORG_NAME          Org to use. Defaults to currently logged-in org
  -h, --help                  Show this message and exit.
[root@nfs bin]# cse version
CSE, Container Service Extension for VMware vCloud Director, version 2.0.0.0b1
[root@nfs bin]# ./vcd cse version
CSE, Container Service Extension for VMware vCloud Director, version 2.0.0.0b1
[root@nfs bin]# pip list | grep pyvcloud
pyvcloud                    20.1.0       
[root@nfs bin]# ./vcd network list
connectedTo       linkType     name
----------------  -----------  ------
External Network  BRIDGED      cse1
cse               INDEPENDENT  cse
[root@nfs bin]# ./vcd cse cluster create test --network cse
create_cluster: Creating cluster test(162a546c-5274-420a-a049-6a14e064c5be)
task: 627bfc53-f269-4b1a-b414-0632eb240fb3, result: error, message: VDC initialization failed as arguments are either invalid or None
[root@nfs bin]# ./vcd cse cluster create test --network cse1
create_cluster: Creating cluster test(9ad2fce8-b291-4c2f-a350-0c10401e72a3)
task: a341148d-2d4d-466c-a80b-e7d524ebcf78, result: error, message: VDC initialization failed as arguments are either invalid or None
[root@nfs bin]# ./vcd cse cluster create test --network abc
create_cluster: Creating cluster test(da32c85c-5531-4134-83b0-6e621f4f7865)
task: 8828a325-9613-4dfb-8b95-8eecdb3cd214, result: error, message: VDC initialization failed as arguments are either invalid or None

**Comment by omairkca** [comment]
Hi Andrew-ni,

Thanks for response please help me out if its possible and one more think am shared with you after cse installation am unable to find cse plugin on vcd ui. please help me out.

[root@nfs bin]# ./vcd cse system info
property              value
--------------------  ------------------------------------------------------
all_threads           6
config_file           /root/cse/config.yaml
consumer_threads      5
description           Container Service Extension for VMware vCloud Director
product               CSE
python                3.6.8
requests_in_progress  0
status                Running
version               2.0.0.0b1
[root@nfs bin]# ./vcd cse ovdc list
name              org             k8s_provider
----------------  --------------  --------------
cse               System          none
Catalog           Catalog         native
cse-cloud-native  cse-native-org  none

**Comment by omairkca** [comment]
19-09-12 10:54:15 | consumer:193 - acknowledge_message | DEBUG :: Acknowledging message 12
19-09-12 10:54:15 | consumer:151 - on_message | DEBUG :: Received message # 12 from None (139802393442048): {"id": "f0d805d0-ab25-46d8-acba-fd5ee602cf34", "method": "POST", "requestUri": "/api/cse", "queryString": null, "protocol": "HTTP/1.1", "scheme": "https", "remoteAddr": "172.16.10.178", "remotePort": 40600, "localAddr": "172.16.10.181", "localPort": 443, "headers": {"Accept": "application/*+json;version=32.0", "User-Agent": "python-requests/2.22.0", "Connection": "keep-alive", "x-vcloud-authorization": "0ec7af90fcb045ef82a13baf5a874ad3", "Host": "172.16.10.181", "Accept-Encoding": "gzip, deflate", "Content-Length": "230", "Content-Type": "application/json"}, "body": "eyJjbHVzdGVyX25hbWUiOiAiYWJjIiwgIm5vZGVfY291bnQiOiAyLCAidmRjIjogIkNhdGFsb2ciLCAiY3B1IjogbnVsbCwgIm1lbW9yeSI6IG51bGwsICJuZXR3b3JrIjogImNzZSIsICJzdG9yYWdlX3Byb2ZpbGUiOiBudWxsLCAic3NoX2tleSI6IG51bGwsICJ0ZW1wbGF0ZSI6IG51bGwsICJlbmFibGVfbmZzIjogZmFsc2UsICJkaXNhYmxlX3JvbGxiYWNrIjogdHJ1ZSwgIm9yZyI6ICJDYXRhbG9nIn0=", "statusCode": 0, "request": true}, props: <BasicProperties(['content_type=application/octet-stream', 'correlation_id=6b28061b-db6d-42a8-b9c2-5a11b9e79f13', 'delivery_mode=1', "headers={'messageType': 'ProcessHttpRequest', 'replyToExchange': 'vcd.replyExchange', 'replyByTimestamp': 1568267675684L}", 'priority=0', 'reply_to=vcd.replyQueue.ae95af81-d001-4b62-9e2b-d09a65e19904'])>
19-09-12 10:54:15 | processor:28 - process_request | DEBUG :: body: {"id": "f0d805d0-ab25-46d8-acba-fd5ee602cf34", "method": "POST", "requestUri": "/api/cse", "queryString": null, "protocol": "HTTP/1.1", "scheme": "https", "remoteAddr": "172.16.10.178", "remotePort": 40600, "localAddr": "172.16.10.181", "localPort": 443, "headers": {"Accept": "application/*+json;version=32.0", "User-Agent": "python-requests/2.22.0", "Connection": "keep-alive", "x-vcloud-authorization": "0ec7af90fcb045ef82a13baf5a874ad3", "Host": "172.16.10.181", "Accept-Encoding": "gzip, deflate", "Content-Length": "230", "Content-Type": "application/json"}, "body": "eyJjbHVzdGVyX25hbWUiOiAiYWJjIiwgIm5vZGVfY291bnQiOiAyLCAidmRjIjogIkNhdGFsb2ciLCAiY3B1IjogbnVsbCwgIm1lbW9yeSI6IG51bGwsICJuZXR3b3JrIjogImNzZSIsICJzdG9yYWdlX3Byb2ZpbGUiOiBudWxsLCAic3NoX2tleSI6IG51bGwsICJ0ZW1wbGF0ZSI6IG51bGwsICJlbmFibGVfbmZzIjogZmFsc2UsICJkaXNhYmxlX3JvbGxiYWNrIjogdHJ1ZSwgIm9yZyI6ICJDYXRhbG9nIn0=", "statusCode": 0, "request": true}
19-09-12 10:54:15 | processor:85 - process_request | DEBUG :: request body: {"cluster_name": "abc", "node_count": 2, "vdc": "Catalog", "cpu": null, "memory": null, "network": "cse", "storage_profile": null, "ssh_key": null, "template": null, "enable_nfs": false, "disable_rollback": true, "org": "Catalog"}
19-09-12 10:54:15 | service:77 - get_sys_admin_client | WARNING :: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
19-09-12 10:54:15 | utils:75 - connect_vcd_user_via_token | WARNING :: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
19-09-12 10:54:15 | utils:75 - connect_vcd_user_via_token | WARNING :: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
19-09-12 10:54:16 | broker_manager:324 - _find_cluster_in_org | DEBUG :: Get cluster info on abc failed on vCD with error: Cluster 'abc' not found.
19-09-12 10:54:16 | service:77 - get_sys_admin_client | WARNING :: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
19-09-12 10:54:16 | utils:75 - connect_vcd_user_via_token | WARNING :: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
19-09-12 10:54:16 | vcdbroker:363 - create_cluster | DEBUG :: About to create cluster abc on Catalog with 2 nodes, sp=None
19-09-12 10:54:16 | utils:75 - connect_vcd_user_via_token | WARNING :: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
19-09-12 10:54:16 | service:77 - get_sys_admin_client | WARNING :: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
19-09-12 10:54:17 | vcdbroker:211 - run | DEBUG :: Thread started for operation=create_cluster
19-09-12 10:54:17 | processor:170 - process_request | DEBUG :: reply: {'body': {'name': 'abc', 'cluster_id': '56e80a52-4860-456c-a433-ee6bec49ab5b', 'task_href': 'https://172.16.10.181/api/task/de31103e-6307-4182-97d2-f801f4d4592d'}, 'status_code': 202}
19-09-12 10:54:17 | consumer:183 - on_message | DEBUG :: reply: "{\"name\": \"abc\", \"cluster_id\": \"56e80a52-4860-456c-a433-ee6bec49ab5b\", \"task_href\": \"https://172.16.10.181/api/task/de31103e-6307-4182-97d2-f801f4d4592d\"}"
19-09-12 10:54:17 | vcdbroker:495 - create_cluster_thread | ERROR :: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/container_service_extension/vcdbroker.py", line 396, in create_cluster_thread
    vdc = VDC(self.tenant_client, resource=vdc_resource)
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/vdc.py", line 59, in __init__
    "VDC initialization failed as arguments are either invalid "
pyvcloud.vcd.exceptions.InvalidParameterException: VDC initialization failed as arguments are either invalid or None

**Comment by rocknes** [comment]
Hi,

The CSE version in question is a beta build of 2.0.0. I would suggest you upgrade to CSE 2.5.0. The REST communication between the client and server has changed a lot between CSE 2.0.0 and CSE 2.5.0. And also we are not going to make any fixes on CSE 2.0.0.

Regards
Aritra Sen
