### ISSUE TITLE
CSE cluster resize command issue

### ISSUE THREAD

**Issue by Vijendrasi** [vmware/container-service-extension#425]
We do not have option to choose template while running vcd cse cluster resize command.

# vcd cse cluster resize -h
Usage: vcd cse cluster resize [OPTIONS] NAME

  Resize the cluster to contain the specified number of worker nodes.

  Clusters that use native Kubernetes provider can not be sized down (use
  'vcd cse node delete' command to do so).

Options:
  -N, --nodes INTEGER  New size of the cluster (or) new worker node count of
                       the cluster
  -n, --network TEXT   Network name (Exclusive to native Kubernetes provider)
                       (Required)
  -v, --vdc VDC_NAME   Restrict cluster search to specified org VDC
  --disable-rollback   Disable rollback on failed node creation (Exclusive to
                       native Kubernetes provider)
  -h, --help           Show this message and exit.

It is possible to add node with template using vcd cse add node command but no option to choose template in resize command.

**Comment by andrew-ni** [comment]
This is fixed in PR #419
