### ISSUE TITLE
Cluster resize command - add template parameter

### ISSUE THREAD

**Issue by Vijendrasi** [vmware/container-service-extension#438]
I have checked this issue is resolved in below mentioned query but I did not find information about how to implement fix.

Add template name and revision to cluster resize #419
https://github.com/vmware/container-service-extension/pull/419

I am using CSE 2.0 with VCD 9.1 please let me know what steps need to perform to fix this issue.

**Comment by goelaashima** [comment]
The fix is in latest CSE 2.5 Beta code, which will be part of CSE 2.5 GA.

It is not available in CSE 2.0 product line.
