### ISSUE TITLE
Feature Request: up-to-date photonOS templates

### ISSUE THREAD

**Issue by flamby** [vmware/container-service-extension#466]
Hi,

PhotonOS templates are faster to provision, and I think less buggy than the ubuntu templates.
It also has a smaller footprint, useful for security.

Thus, can you provide photonOS with latest K8S 1.16 and weave latest stable build as well?

TIA

**Comment by andrew-ni** [comment]
Hi @flamby ,

We are going to be releasing a Photon Kubernetes 1.14.6, weave 2.5.2 template soon. Unfortunately, this is the latest version of kubernetes that Photon supports. More info can be found here: https://github.com/vmware/photon/blob/2.0/SPECS/kubernetes/kubernetes-1.14.spec

You can also open an issue on Photon to press them for more updated Kubernetes versions if you require them.
