### ISSUE TITLE
CSE API monitoring

### ISSUE THREAD

**Issue by Vijendrasi** [vmware/container-service-extension#475]
For our production environment we would like to monitor CSE API availability. 

Please let us know which CSE API we need to request using monitoring tool to check the availability of CSE . 

For example we monitor VCD API using below command : 
https://{vcdCellHttpIp}/api/versions

**Comment by rocknes** [comment]
Hi,

The following call can be used to check availability of CSE service. It can be invoked by any valid vCD user.

GET https://<vcd public end point>/api/cse/system
Accept : application/json;version=<vcd api version>
x-vcloud-authorization : vCD token

Response status : 200
Response body :
{
    "product": "CSE",
    "description": "Container Service Extension for VMware vCloud Director",
    "version": "2.5.1"
}

When CSE service is not running this call you return a 504. If vCD itself is down, some other REST error code will be returned.

However, a word of caution, this api call will only indicate if CSE service is running or not. However if CSE service has been disabled by Service provider (via the CLI), the call will go through but any subsequent non system related (anything other than /api/system/*) calls will fail.

However If this api call is made by a sys admin, then the output will also have the state of the CSE service. e.g.
{
    "product": "CSE",
    "description": "Container Service Extension for VMware vCloud Director",
    "version": "2.5.1",
    "python": "3.7.4",
    "consumer_threads": 5,
    "all_threads": 6,
    "requests_in_progress": 0,
    "config_file": "config_vcd_10_0.yaml",
    "status": "Disabled"   <----------------- this!
}

**Comment by rocknes** [comment]
Closing the issue due to inactivity.
