### ISSUE TITLE
network ports required by CSE

### ISSUE THREAD

**Issue by stephaneclavel** [vmware/container-service-extension#497]
Hello

Are the required network ports to be opened on firewalls for CSE to access vCD, AMQP, vCenter, PKS etc been documented? 

thanks

**Comment by rocknes** [comment]
Hi Stephan,

The port requirements can be specified in the config file and has been documented here.
https://vmware.github.io/container-service-extension/CSE_CONFIG.html

The defaults will work with out-of-box vCD, AMQP, PKS, vCenter installations.

Regards
Aritra Sen

**Comment by stephaneclavel** [comment]
Hi Aritra

Thanks a lot. I forgot some ports were part of the config file. For systems (vCenter and NSX-T) were no port is specified, am I correct to assume port 443 is sufficient? 

thanks

**Comment by rocknes** [comment]
Yes, 443 should be fine for those services :)

I am closing this issue.

Regards
Aritra Sen
