### ISSUE TITLE
CSE 2.5.1 "Error: 'Client' object has no attribute '_uri'"

### ISSUE THREAD

**Issue by nkruniceva** [vmware/container-service-extension#522]
Hello,

I've installed CSE 2.5.1 on Centos8 with vCloud Director 9.7.
Python: 3.7.3.
pyvcloud: 21.0.0
vcd-cli: 22.0.0

I am able to create k8s cluster, but unable to list, resize or delete clusters.
The error response is:

```
(cse-client) [root@smtn]# vcd cse cluster list
Usage: vcd cse cluster list [OPTIONS]
Try "vcd cse cluster list -h" for help.

Error: 'Client' object has no attribute '_uri'
```

in vcd-cli.error log:

```
Traceback (most recent call last):
  File "/cse-client/lib/python3.7/site-packages/container_service_extension/client/cse.py", line 183, in list_clusters
    result = cluster.get_clusters(vdc=vdc, org=org_name)
  File "/cse-client/lib/python3.7/site-packages/container_service_extension/client/cluster.py", line 34, in get_clusters
    return process_response(response)
  File "/cse-client/lib/python3.7/site-packages/container_service_extension/client/response_processor.py", line 41, in process_response
    raise response_to_exception(response)
  File "/cse-client/lib/python3.7/site-packages/container_service_extension/client/response_processor.py", line 99, in response_to_exception
    response.status_code, error_message, minor_error_code)
container_service_extension.exceptions.CseResponseError: 'Client' object has no attribute '_uri'
```

```
(cse-client) [root@smtn]# vcd cse system info
property              value
--------------------  ------------------------------------------------------
all_threads           6
config_file           /usr/src/Python-3.7.3/config.yaml
consumer_threads      5
description           Container Service Extension for VMware vCloud Director
product               CSE
python                3.7.3
requests_in_progress  0
status                Running
version               2.5.1
```

But the creation of cluster succeeds, I'm able to see vApp and nodes in vCloud director.
Can you please advise in which direction should we troubleshoot this?
Thanks.

**Comment by rocknes** [comment]
Hi, 

Can you please run pip3 list in the virtual env and verify that the versions of pyvcloud and vcd-cli are indeed 21.0.0 and 22.0.0 respectively?

The field client._uri was removed recently in pyvcloud but this change shouldn't be in pyvcloud 21.0.0. So I suspect that pyvcloud is installed at v 21.0.1. can you please verify?

Regards
Aritra Sen

**Comment by nkruniceva** [comment]
Hi rocknes,

I've tried from two virutal env.
```
(cse-client) [root@smtn]# pip3 list
Package                     Version
--------------------------- ----------
cachetools                  4.0.0
certifi                     2019.11.28
cffi                        1.14.0
chardet                     3.0.4
Click                       7.0
colorama                    0.4.3
container-service-extension 2.5.1
cryptography                2.8
entrypoints                 0.3
humanfriendly               6.0
idna                        2.8
jeepney                     0.4.2
keyring                     12.0.0
lxml                        4.5.0
pika                        0.13.1
pip                         20.0.2
pycparser                   2.19
pycryptodome                3.4.11
Pygments                    2.5.2
pyvcloud                    21.0.0
pyvmomi                     6.7.3
PyYAML                      5.3
requests                    2.22.0
SecretStorage               3.1.2
setuptools                  40.8.0
six                         1.14.0
tabulate                    0.8.6
unittest-xml-reporting      3.0.0
urllib3                     1.25.8
vcd-cli                     22.0.0
vsphere-guest-run           0.0.7
```

So the first one has versions 21.0.0 and 22.0.0 as mentioned in documentation.

The other one is virtual env. from which i installed container-service-extension.
Could that be a problem, should i re-nstall it?

```
(cse_venv) [root@smtn]# pip3 list
Package                     Version
--------------------------- ----------
cachetools                  4.0.0
certifi                     2019.11.28
cffi                        1.14.0
chardet                     3.0.4
Click                       7.0
colorama                    0.4.3
container-service-extension 2.5.1
cryptography                2.8
entrypoints                 0.3
humanfriendly               5.0
idna                        2.8
jeepney                     0.4.2
keyring                     12.0.0
lxml                        4.5.0
pika                        0.13.1
pip                         20.0.2
pycparser                   2.19
pycryptodome                3.4.11
Pygments                    2.5.2
pyvcloud                    21.0.1
pyvmomi                     6.7.3
PyYAML                      5.3
requests                    2.22.0
SecretStorage               3.1.2
setuptools                  40.8.0
six                         1.14.0
tabulate                    0.8.6
unittest-xml-reporting      2.5.2
urllib3                     1.25.8
vcd-cli                     22.0.2
vsphere-guest-run           0.0.7
```

**Comment by rocknes** [comment]
Yes, the other venv should be modified to have
CSE 2.5.1
pyvcloud 21.0.0
vcd-cli 22.0.0

Regards
Aritra Sen

**Comment by nkruniceva** [comment]
Hello rocknes,

I've updated venv to these version.

Now, i am able to successfully list cluster, delete them, but not resize them.

The error I'm receiving is:

```
(cse_venv) [root@s01cse01p Python-3.7.3]# vcd cse cluster resize k8s-cluster -N 3
Usage: vcd cse cluster resize [OPTIONS] CLUSTER_NAME
Try "vcd cse cluster resize -h" for help.

Error: 'set' object is not subscriptable
```

in vcd-cli.error.log i can see:

```
Traceback (most recent call last):
  File "/cse_venv/lib/python3.7/site-packages/container_service_extension/client/cse.py", line 476, in cluster_resize
    template_revision=template_revision)
  File "/cse_venv/lib/python3.7/site-packages/container_service_extension/client/cluster.py", line 148, in resize_cluster
    return process_response(response)
  File "/cse_venv/lib/python3.7/site-packages/container_service_extension/client/response_processor.py", line 41, in process_response
    raise response_to_exception(response)
  File "/cse_venv/lib/python3.7/site-packages/container_service_extension/client/response_processor.py", line 99, in response_to_exception
    response.status_code, error_message, minor_error_code)
container_service_extension.exceptions.CseResponseError: 'set' object is not subscriptable
```

**Comment by nkruniceva** [comment]
Hello Aritra

Thank you, I've updated both venv to these version, and the issue is resolved.

BR,
Nevena Krunic

**Comment by rocknes** [comment]
Awesome :)

**Comment by minhphuoc275** [comment]
Hello all, I tried to do the same but I cannot pass this step, can you please support me get over it?

Thank you so much for your advice.

(cse-env) [cse@console01 ~]$ pip list
Package                     Version
--------------------------- ----------
cachetools                  4.0.0
certifi                     2019.11.28
cffi                        1.14.0
chardet                     3.0.4
Click                       7.0
colorama                    0.4.3
container-service-extension 2.5.1
cryptography                2.8
entrypoints                 0.3
humanfriendly               8.0
idna                        2.9
jeepney                     0.4.3
keyring                     12.0.0
lxml                        4.5.0
pika                        0.13.1
pip                         20.0.2
pycparser                   2.20
pycryptodome                3.4.11
Pygments                    2.5.2
pyvcloud                    21.0.0
pyvmomi                     6.7.3
PyYAML                      5.3
requests                    2.23.0
SecretStorage               3.1.2
setuptools                  45.2.0
six                         1.14.0
tabulate                    0.8.6
unittest-xml-reporting      3.0.2
urllib3                     1.25.8
vcd-cli                     22.0.0
vsphere-guest-run           0.0.7
wheel                       0.34.2
(cse-env) [cse@console01 ~]$
(cse-env) [cse@console01 ~]$ vcd cse system info
property     value
-----------  ------------------------------------------------------
description  Container Service Extension for VMware vCloud Director
product      CSE
version      2.5.1
(cse-env) [cse@console01 ~]$
(cse-env) [cse@console01 ~]$ vcd cse cluster list
Usage: vcd cse cluster list [OPTIONS]
Try "vcd cse cluster list -h" for help.

Error: 'Client' object has no attribute '_uri'
(cse-env) [cse@console01 ~]$

**Comment by mann1mal** [comment]
@minhphuoc275, after chatting with @rocknes, he mentioned it would be a good idea to check and make sure you have verified the correct pyvcloud and vcd-cli package versions are installed in BOTH the virtualenv that houses the CSE server installation as well as the client packages, if you are using separate virtual env for the client and server installations.

Could that be causing the issues you are seeing?

**Comment by minhphuoc275** [comment]
Thanks Mann1mal, I will check it, thanks so much for your advice (also thanks Rocknes)

**Comment by minhphuoc275** [comment]
Hi all,
I tried to update the version in cse server as well but still be unsuccessful, however, let's wait the version 2.6.0 which is integrated UI. I think it will be more worth to install.
