### ISSUE TITLE
CSE API

### ISSUE THREAD

**Issue by tranvanthanh1988** [vmware/container-service-extension#544]
Hi all,
I want to create a cluster using CSE API. I searched but it seems the API swagger definition is quite old and appear error below:
{
    "message": {
        "minor error code": -1,
        "error description": "'set' object is not subscriptable"
    }
}
Can you help me this case?
Thanks!

**Comment by rocknes** [comment]
Hi,

You are right the swagger definition is obsolete and hence we have removed the support to get it via REST. 

I will update this issue with a sample REST call and body for creating a cluster by end of day today :)

Regards
Aritra Sen

**Comment by rocknes** [comment]
POST https://<vcd fqdn>/api/cse/clusters

Headers
---------
Accept: application/json;version=33.0
x-vcloud-authorization: token
or
Authorization: token

Body
------
{
            cluster_name: ?,
            num_workers: ?,
            ovdc_name: ?,
            num_cpu: ?,
            mb_memory: ?,
            network_name: ?,
            storage_profile_name: ?,
            ssh_key: ?,
            template_name: ?,
            template_revision: ?,
            enable_nfs: ?,
            rollback: ?,
            org_name: ?
}

**Comment by tranvanthanh1988** [comment]
Thanks a lot @rocknes 
We have successfully created based on your REST API.
By the way, can you provide the REST API of the update nodes configuration(vCPU, RAM) and resize cluster (scale in/out nodes)?

Regards,

**Comment by rocknes** [comment]
Hi,

I don't think CSE has an api to update node properties like vCPU and RAM once the node has been created. However you can speicfy those while adding a new node to a cluster. The api to do so is as follows

POST https://{vcd fqdn}/api/cse/nodes

Body:
{
  cluster_name: ?,
  num_workers: ?,
  org_name: ?,
  ovdc_name: ?,
  num_cpu: ?,
  mb_memory: ?,
  network_name: ?,
  storage_profile_name: ?,
  ssh_key: ?,
  template_name: ?,
  template_revision: ?,
  enable_nfs: ?,
  rollback: ?,
}

Regards
Aritra Sen

**Comment by tranvanthanh1988** [comment]
Thank @rocknes very much!

**Comment by tranvanthanh1988** [comment]
Hi @rocknes 
Sorry, can you provide me the API to remove a node?
I tried many ways but failed (API for adding new nodes is ok).
Thank you.

**Comment by rocknes** [comment]
DELETE /api/cse/nodes
Body:
{
  cluster_name: ?,
  org_name: ?,
  vdc_name: ?,
   node_names: [?,...] # <- array of node names e.g. [mstr-abcd, nodes-uxyz]
}

Regards
Aritra Sen

**Comment by tranvanthanh1988** [comment]
it worked!
Thank @rocknes 
Regards,
