### ISSUE TITLE
CSE should be a systemd service

### ISSUE THREAD

**Issue by tsugliani** [vmware/container-service-extension#55]
Hi @pacogomez,

I've seen Issue #50, which could also be leveraged for this, but alternative method would also be nice.

configuration file (for example):
```/etc/vmware-cse/config.yaml```

enable the service:
```systemctl enable vmware-cse```

start the service:
```systemctl start vmware-cse```

 service status:
```systemctl status vmware-cse``` <-- (maybe cse.log files)

etc.

**Comment by pacogomez** [comment]
CSE now includes a sample `cse.service` systemd unit and it is documented in the docs.

**Comment by pacogomez** [comment]
This is now implemented in version `0.4.0` and up.
