### ISSUE TITLE
Cluster created (or upgraded) with CSE 2.6 showing "0.0.0" as Kubernetes version

### ISSUE THREAD

**Issue by mann1mal** [vmware/container-service-extension#563]
Recently upgraded lab environment to CSE 2.6.0 from CSE 2.5.1 and had an existing cluster (test) that was created in 2.5.1 and provisioned a new cluster (ui-upgrade-test) and both show with Kubernetes version "0.0.0"

~~~
$ vcd cse cluster list
name             vdc        status      org_name    k8s_version    k8s_provider
---------------  ---------  ----------  ----------  -------------  --------------
test             base-ovdc  POWERED_ON  base-org    0.0.0          native
ui-upgrade-test  base-ovdc  POWERED_ON  base-org    0.0.0          native
~~~

The "test" cluster was created originally with CSE 2.5.1 and upgraded using `cse convert-cluster`.

Also showing via cli:

~~~
$ vcd cse cluster list
name             vdc        status             org_name    k8s_version    k8s_provider
---------------  ---------  -----------------  ----------  -------------  --------------
test             base-ovdc  POWERED_ON         base-org    0.0.0          native
ui-upgrade-test  base-ovdc  POWERED_ON         base-org    0.0.0          native
~~~

As discussed with @rocknes, the template used to create this cluster was initially deployed and installed using CSE 2.5.1, so thinking that is the issue.

**Comment by rocknes** [comment]
Hi Joe,

We are looking into this. This maybe a design limitation will update once our investigation is over.

Regards
Aritra Sen

**Comment by rocknes** [comment]
Fixed via https://github.com/vmware/container-service-extension/pull/572
Also documented in Known Issues section https://vmware.github.io/container-service-extension/KNOWN_ISSUES.html
