### ISSUE TITLE
Shared Org vDC network are not shown in the UI

### ISSUE THREAD

**Issue by bserratrice** [vmware/container-service-extension#567]
Hello,

It seems that org vDC network that are shared between vDC only appears in CSE UI when a we try to provision a k8s cluster on the same vDC where the org vDC network has been created. If another vDC is selected (where the network is shared with), the network doesn't appear in the dropdown.

Provisioning through CLI works though.

**Comment by rocknes** [comment]
Hi @bserratrice,

The CSE UI, queries vCD for the acceptable list of org VDC network. I guess the query might be missing this particular usecase. @andrew-ni Can you please take a look into this?

Regards
Aritra Sen

**Comment by andrew-ni** [comment]
Hey @bserratrice ,

The query we're using to fetch the ovdc networks doesn't give us any way to fetch the ovdcs that the network is shared with. We'll try to get this use case resolved, and i'll keep this issue updated

**Comment by andrew-ni** [comment]
@bserratrice , 

A new CSE UI plugin build has been released with CSE 2.6.1 that fixes this issue
