### ISSUE TITLE
Cluster status is actually missing vCloud Director host VM state status

### ISSUE THREAD

**Issue by tsugliani** [vmware/container-service-extension#58]
Hi @pacogomez,

I've just witnessed this so logging it.

Basically left my CSE environment running for a while, but as some environment might have this settings enabled & configured, it would probably be worth adding this check.

In vCloud Director you have the ability to setup lease settings for runtime & storage.
So after 7 days for example, VMs for which lease haven't been renewed by the user, will be powered off automatically by vCloud Director.

so from the `vcd-cli cluster list` it "seems" everything is fine.

<img width="1030" alt="screen shot 2017-12-15 at 10 42 03 am" src="https://user-images.githubusercontent.com/146306/34036585-f5a15f40-e185-11e7-96a6-813b155d5fa0.png">

Maybe adding a "Status" column on the right side could be interesting, ensuring that all VMs & connectivity is working as expected ?

**Comment by andrew-ni** [comment]
Hey Timo,

I've implemented this locally. This should be fixed soon!
