### ISSUE TITLE
compatibility of cse 2.5.1 with vcd 9.7 minor version 9.7.0.4 , 9.7.05

### ISSUE THREAD

**Issue by sanjeev-gorai** [vmware/container-service-extension#602]
We have CSE 2.5.1 with VCD 9.1.0.3 which will be upgraded soon to 9.5.0.5 / 6 in coming days and then vCloud 9.7.0.x  in coming weeks. 

As per CSE  release notes  available on github  CSE 2.5.1 has compatibility with VCD  9.1,9.5,9.7,10.0 but not explicitly mentioned minor like 9.5.0.x or x 9.7.0.x.

However, It make some doubt when refer 2.6.1 compatibility which point specific to minor version like 9.7.0.4 not 9.7.0.x.

Our query is if CSE 2.5.1 is compatible with VCD 9.7 release version 9.7.0.4, 9.7.0.5 ?

**Comment by rocknes** [comment]
Hi,

CSE 2.5.1 should work with vCD 9.7.0.4 and 9.7.0.5, since the vCD api doesn't change in patch/update releases. However it has not been tested and verified at our end. If bugs are discovered then you might have to upgrade to a later version of CSE to get the fixes.

Regards
Aritra Sen

**Comment by sanjeev-gorai** [comment]
Hello Aritra,

Thanks for your information.
