### ISSUE TITLE
Error: External service 'cse' failed to respond in the specified timeout (40 SECONDS) - 504, GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by dwtaylornz** [vmware/container-service-extension#615]
```
CSE, Container Service Extension for VMware vCloud Director, version 2.6.1
```

Things are partially working, but _some_ cse commands are timing out... 

I can create clusters successfully with **vcd cse cluster create**, just that vcd-cli times out without returning any data. The following commands work without issue - including expected results ;

  **vcd cse cluster list** 

```
Name    VDC               Org      K8s Runtime    K8s Version    Status      Provider
------  ----------------  -------  -------------  -------------  ----------  ----------
k8      DT_Test_100_PAYG  DT_Test  upstream       1.17.2         POWERED_ON  native
```

  **vcd cse cluster info k8** - returns ok also. 

Issues start here... 

  **vcd cse cluster config k8** 

```
Usage: vcd cse cluster config [OPTIONS] NAME
Try 'vcd cse cluster config -h' for help.

Error: External service 'cse' failed to respond in the specified timeout (40 SECONDS)
```

Logs attached, the closest hint i have had in the logs is GATEWAY_TIMEOUT in the vcd logs... suggesting that the results are not being proxied back correctly? 

```
Request uri (GET): https://vcd-server/api/cse/cluster/k8/config?org_name=DT_Test
Request headers: {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json;version=33.0', 'Connection': 'keep-alive', 'Authorization': '[REDACTED]'}
Response status code: 504
Response headers: {'Date': 'Fri, 12 Jun 2020 02:09:40 GMT', 'X-VMWARE-VCLOUD-REQUEST-ID': '4f2afa75-cbed-4e9f-9de7-d5b51a1aad2e', 'Content-Type': 'application/vnd.vmware.vcloud.error+json;version=33.0', 'X-VMWARE-VCLOUD-REQUEST-EXECUTION-TIME': '40013', 'Cache-Control': 'no-store, must-revalidate', 'Transfer-Encoding': 'chunked'}
Response body: {
  "otherAttributes" : { },
  "tenantError" : null,
  "stackTrace" : null,
  "majorErrorCode" : 504,
  "message" : "External service 'cse' failed to respond in the specified timeout (40 SECONDS)",
  **"minorErrorCode" : "GATEWAY_TIMEOUT",**
  "vendorSpecificErrorCode" : null,
  "vCloudExtension" : [ ]
}
```
i can see the kube.config data being generated in cse-server-debug.log 

CSE landing page on VCD UI perpetually shows a spinning wheel -- assuming related to above :)

**Comment by rocknes** [comment]
Hi,

The error is definitely caused by CSE being unable to respond back to vCD over AMQP bus. I wonder why this is happening only for certain workflows. Do you have a lot of ovdc-s in your system? Will it be possible to upload the full CSE server log?

Regards
Aritra Sen

**Comment by dwtaylornz** [comment]
Your 100% right, i checked vCloud logs and the AMQP exchange was not defined. Strange that it was partially working. I logged into RabbitMQ, created the missing exchange and everything appears tob e working find.   

Except the UI plug-in. But i'll spend a bit more time troubleshooting that one before posting here. Many thanks for your help.
