### ISSUE TITLE
How to configure CSE 2.5.1 as DR protected service

### ISSUE THREAD

**Issue by sanjeev-gorai** [vmware/container-service-extension#619]
We are configuring CSE 2.51 as  DR-protected services , this means CSE VM is constantly replicated to the recovery site , and we will be able to start it up (along with vCD and other stuff) in the event of a disaster. Considering that during disaster the vapp container catalogs will not be available so we need to:
•    Reconfigure CSE application to point to a different catalog, as part of DR’s post-recovery actions 
•   Ensure we maintain exact copies of the templates on two catalogs at all times. 

Can somebody help/suggest  in below points:

1. Is there any way, in CSE, in which we can specify a “secondary” catalog location for the K8s templates and  what are steps required to reconfigure CSE application to point to secondary location?
	
2..  Can we simply copy the templates to a different catalog, and be sure CSE will use them once we re-point the catalog entry in CSE configuration? Or (hopefully not) does CSE need to download again the templates once you reconfigure the catalog?

**Comment by goelaashima** [comment]
Closing it. Hopefully, these were communicated over via VMware TAM.
