### ISSUE TITLE
How to change default storage_profile on running CSE 2.5.1 env.

### ISSUE THREAD

**Issue by sanjeev-gorai** [vmware/container-service-extension#638]
Do any body have any idea how to change the storage_profile on running CSE 2.5.1 env ?
we have updated the new storage_profile in config.yaml and restarted CSE service but still new cluster created is using the old storage profile.

**Comment by sakthisunda** [comment]
Please try `vcd cse cluster create --storage-profile new_profile_name` .  In the meantime, we are checking why the storage_profile in config.yaml is not used in the cluster creation.

**Comment by sakthisunda** [comment]
Hi @sanjeev-gorai : 'storage_profile' in config.yaml is meant only for creating vApp templates. Verfied that it is not meant for cluster creation. We will update the documentation on this.

**Comment by sanjeev-gorai** [comment]
@sakthisunda thanks for your input. 
Is there any way to change this storage in existing vApp templates or we need to create new templates from new storage_profile ?

**Comment by sakthisunda** [comment]
Yes, new template has to be created with new storage profile.
