### ISSUE TITLE
Creating Cluster fails after vApp creation

### ISSUE THREAD

**Issue by mycloudrevolution** [vmware/container-service-extension#64]
CSE Version: 0.3
vCD Version 9.0.0.2
vCenter Version 6.5 U1

**Error Message:**
vcd cse cluster create mycluster --network OrgtNet_A
create_cluster: Creating cluster mycluster(098da013-5741-48d8-9aef-ad7e230220f0)
create_cluster: Creating cluster vApp mycluster(098da013-5741-48d8-9aef-ad7e230220f0)
task: 0c46d46f-ffc7-4be3-ac25-3592558dc0ed, result: error, message: module 'random' has no attribute 'choices'

**Config Check:**
/root/.local/bin/cse check --config /cse/config.yaml
Validating CSE on vCD from file: /cse/config.yaml
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to AMQP server (xxxxxxx:5672): success
Connected to vCenter Server as administrator@vsphere.local (xxxxxx:443): success
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director as system administrator (xxxxxx:443): success
Validating 'default' service broker
Find catalog 'CSE-Global': success
Validating template: photon-v1
  Is default template: True
Find template 'CSE-Global', 'photon-custom-hw11-1.0-62c543d-k8s': success
Validating template: ubuntu-16.04
  Is default template: False
Find template 'CSE-Global', 'ubuntu-16.04-server-cloudimg-amd64-k8s': success
The configuration is valid.

**Service Start:**
Service cse status
● cse.service - Container Service Extension for VMware vCloud Director
   Loaded: loaded (/etc/systemd/system/cse.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-01-23 09:21:50 CET; 41s ago
 Main PID: 1219 (bash)
    Tasks: 7
   Memory: 62.2M
      CPU: 975ms
   CGroup: /system.slice/cse.service
           ├─1219 bash /cse/cse.sh
           └─1230 /usr/bin/python3 /root/.local/bin/cse run --config /cse/config.yaml

Jan 23 09:21:57 cse01 cse.sh[1219]: Validating template: photon-v1
Jan 23 09:21:57 cse01 cse.sh[1219]:   Is default template: True
Jan 23 09:21:58 cse01 cse.sh[1219]: Find template 'CSE-Global', 'photon-custom-hw11-1.0-62c543d-k8s': success
Jan 23 09:21:58 cse01 cse.sh[1219]: Validating template: ubuntu-16.04
Jan 23 09:21:58 cse01 cse.sh[1219]:   Is default template: False
Jan 23 09:21:58 cse01 cse.sh[1219]: Find template 'CSE-Global', 'ubuntu-16.04-server-cloudimg-amd64-k8s': success
Jan 23 09:21:58 cse01 cse.sh[1219]: Container Service Extension for vCloud Director running
Jan 23 09:21:58 cse01 cse.sh[1219]: config file: /cse/config.yaml
Jan 23 09:21:58 cse01 cse.sh[1219]: see file log file for details: cse.log
Jan 23 09:21:58 cse01 cse.sh[1219]: waiting for requests, press Ctrl+C to finish
`

**Comment by mycloudrevolution** [comment]
**cse.log shows these error (as root cause):**
01-23 12:57:05 cse.broker   483 ERROR    Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/container_service_extension/broker.py", line 443, in create_cluster_thread
    wait=True)
  File "/root/.local/lib/python3.5/site-packages/container_service_extension/cluster.py", line 146, in add_nodes
    random.choices(string.ascii_lowercase + string.digits, k=4)))
AttributeError: module 'random' has no attribute 'choices'

**Comment by pacogomez** [comment]
CSE service requires Python 3.6

**Comment by mycloudrevolution** [comment]
Many thanks!
A few hours troubleshooting for me and a just quick look from you...

**Comment by pacogomez** [comment]
You are welcome!. The new version `0.4.0` will include a check for python version in the `cse check` command.
