### ISSUE TITLE
the extension module 'container_service_extension.client.cse' could not be imported

### ISSUE THREAD

**Issue by patpnut** [vmware/container-service-extension#647]
I'm getting the error below when trying to run vcd cse commands. I edited profiles.yaml and added the extensions but still no go
[profiles.yaml.txt](https://github.com/vmware/container-service-extension/files/4904959/profiles.yaml.txt)

"Warning: the extension module 'container_service_extension.client.cse' could not be imported."

**Comment by andrew-ni** [comment]
can you provide your python version (`python3 --version`) as well as your CSE version (from `pip3 list`)

**Comment by patpnut** [comment]
since this was a jumpbox, I had installed everything but cse
