### ISSUE TITLE
Cluster creation errors

### ISSUE THREAD

**Issue by patpnut** [vmware/container-service-extension#650]
So I'm getting the error below when I'm creating a cluster , by the looks of things it doesnt seem that it's a CSE error at all, so I'd love to get some help maybe from anyone on here who has deployed CSE on NSX-V & NSX-T. So the mater node gets created and by the errors below it just seems that the components aren't getting installed . Has anyone run into this before ? The 2 install scenarios that I have done is doing the Install on Publicly available External networks and also Routed networks behind an Edge and both scenarios, I keep getting the same error ...I'm running CSE 2.6.1 with vCD 10.1.1

# vcd cse cluster create lb-cluster1 -v LB-VDC -N 2 -c 4 -m 6000 -n VDC-NET-INT-10.100.10.0/24 -s NSX-T
cluster operation: Creating cluster vApp 'lb-cluster1' (9db0f360-76fd-4a3d-9398-3261914362c8) from template 'ubuntu-16.04_k8-1.17_weave-2.6.0' (revision 1)
cluster operation: Creating cluster vApp lb-cluster1 (9db0f360-76fd-4a3d-9398-3261914362c8)
cluster operation: Creating master node for cluster 'lb-cluster1' (9db0f360-76fd-4a3d-9398-3261914362c8)
cluster operation: Initializing cluster 'lb-cluster1' (9db0f360-76fd-4a3d-9398-3261914362c8)
cluster operation: Error creating cluster 'lb-cluster1'. Deleting cluster (rollback=True)
task: 3385a218-21c2-44f4-8777-51cdcede102c, result: error, message: Couldn't initialize cluster: Initialize cluster script execution failed on node ['mstr-sifa']:['W0713 11:58:40.944088    1450 validation.go:28] Cannot validate kube-proxy config - no validator is available\nW0713 11:58:40.9514181450 validation.go:28] Cannot validate kubelet config - no validator is available\n\t[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.17.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.17.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.17.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.17.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/:net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.4.3-0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n\t[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.6.5: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout\n, error: exit status 1\n[preflight] If you know what you are doing, you can make a che...

**Comment by andrew-ni** [comment]
Hi, can you verify that VMs deployed using that network are able to access the internet? The VMs are attempting to pull images from k8s.gcr.io and failing.

**Comment by patpnut** [comment]
They do have internet access and I can ping k8s.gcr.io just fine.. 

14 Jul 2020, 20:18 by notifications@github.com:

**Comment by andrew-ni** [comment]
We've seen this error occasionally when the connection to the kubernetes repository is flaky while we're pulling the images. I believe we're just seeing an unlucky run here. Can you attempt this cluster creation a few more times to verify that this is a problem you face every time? 

Also, could you verify that there are sufficient IPs for the cluster creation?

**Comment by patpnut** [comment]
Funny thing and it's weird, is after I create the master node(no rollback) even though I can ping the repo, but fails preflight checks due to connectivity... 

15 Jul 2020, 01:41 by notifications@github.com:

**Comment by patpnut** [comment]
After alot of troubleshooting this was an issue with MTU settings for the NSX-T edge uplink dVS.
