### ISSUE TITLE
Non availability of any vcenter registered in VCD.

### ISSUE THREAD

**Issue by sanjeev-gorai** [vmware/container-service-extension#659]
As per VMware CSE document all vcenter's registered in VCD must be available and mentioned in CSE's config.yaml file and have proper login for the CSE server to function properly. In case any of vcenter have some issue and not available then restart of CSE service failed ( comment out of that vcenter in config.yaml does not work).
Does any body have any idea how to bypass  any registered vcenter in VCD so that CSE restart works fine. 
I am using CSE 2.5.1 in my environment.

**Comment by Anirudh9794** [comment]
Hi Sanjeev,
We currently don't have any workaround to bypass the registered vcenter in VCD. This will need some thought and implementation from CSE. We will try to come up with a solution for this in future releases. Thank you for bringing up the issue.

**Comment by sanjeev-gorai** [comment]
Hello Anirudh

Thanks for you reply.

**Comment by sakthisunda** [comment]
Fixed in CSE 3.1.0. vCenter that is not currently connected and continue CSE server start/restart. Display warning information about the server unavailability
