### ISSUE TITLE
Large number of authorization events in vCloud Director

### ISSUE THREAD

**Issue by tranvanthanh1988** [vmware/container-service-extension#668]
Hi all,
We are using CSE 2.6.1 and vCloud Director 10.1 with about ~900 Org VDC.
We are experiencing timeout situation as below:
Error: External service 'cse' failed to respond in the specified timeout (60 SECONDS)

In addition, there are many authorization events on vCloud Director( 1.3 million events within 3 days!) as screenshot here:
https://photos.app.goo.gl/rnPFCqdNsUtob2jeA

Regards,

**Comment by goelaashima** [comment]
Take a look at our known issues - https://vmware.github.io/container-service-extension/KNOWN_ISSUES.html. A workaround is mentioned for this issue under the topic "operation will timeout when numerous OrgVDCs exist".
