### ISSUE TITLE
Gracefull deletion of old templates in CSE 2.5.1

### ISSUE THREAD

**Issue by sanjeev-gorai** [vmware/container-service-extension#670]
We are using CSE 2.5.1 and upgraded the templates with latest available templates in github. Now we have both old and new template available in templates list.
 Is there any procedure/command available to remove the old templates gracefully from CSE template list.

**Comment by Anirudh9794** [comment]
Hi Sanjeev,
There is no CLI from CSE to delete the created templates. To delete the created templates, please use VCD UI.
Log in to the organization mentioned in the CSE server config. Go to libraries > catalogs > click on catalog named 'cse' 
The list of templates in the catalog will be displayed. You can delete templates which are not required here.
Let me know if you have any more questions about this :-)

**Comment by sanjeev-gorai** [comment]
Hello Anirudh

Thanks for your reply. But it does not remove the template gracefully, the template is still listed on vcd cse template list ouputs. I believe its entry in VCD database still exists.

**Comment by sanjeev-gorai** [comment]
On restarting the CSE service , deleted templates get removed from vcd cse template list.

**Comment by Anirudh9794** [comment]
Thank you for confirming.
