### ISSUE TITLE
How to change storage profile of existing cse templates in cse 2.5.1

### ISSUE THREAD

**Issue by sanjeev-gorai** [vmware/container-service-extension#683]
Hello all, do any body have idea on how to change the storage profile of  existing cse templates, one way is to re-create the templates again with new storage profile but this involves a downtime for cse service.  Is there any way to change the storage profile of existing templates through vCloud UI.

**Comment by rocknes** [comment]
Hi,

CSE k8s templates are regular vCD vApp templates with some special metadata added on the corresponding catalog item. As you might be aware that vApp templates once created can't have their properties altered without being deployed first and then re-captured. The same applies for CSE templates, once created they can't be modified. Only way to achieve what is desired is to create the template afresh with the desired storage policy.

Regards
Aritra Sen
