### ISSUE TITLE
Initializing cluster VCD task keeps running forever

### ISSUE THREAD

**Issue by kn3-git** [vmware/container-service-extension#685]
VCD version: 10.1.1
CSE version : 2.6.1

VCD is integrated with ALP and CSE.
When a cluster is created, only master node gets created. When a worker node is manually added, "Adding the node to cluster" task keeps running forever.

Also, when for Launch Container type app operation (With ALP) , we are encountering 400 error stating "Invalid Authentication token"

400code"ERROR_INIT_CLUSTER_FAILED"message"Failed to initialize the cluster with name clusterK8 under organization 72c4e568-ce49-4e4d-9371-85924f342d90. The cause is Authenticate token is incorrect in the request."resource"/api/alp/v1/launched-apps"details{…}cause"Failed to initialize the cluster with name clusterK8 under organization 72c4e568-ce49-4e4d-9371-85924f342d90. The cause is Authenticate token is incorrect in the request."requestId"147131ef-d61a-4000-8e92-13a172b63155"

Initializing cluster snap: Please do not get confused with the Delete operation, it did not trigger automatically. We deleted the cluster manually
![image](https://user-images.githubusercontent.com/69351547/89646122-c6ea4980-d8d8-11ea-9e04-2ceb803c5a50.png)

Also, unable to list clusters from CSE node - increased the timeout to 20 seconds. There are only 4-5 clusters, it shouldn't take much time:
[root@centos cse]# vcd cse cluster list
Usage: vcd cse cluster list [OPTIONS]
Try 'vcd cse cluster list -h' for help.

Error: External service 'cse' failed to respond in the specified timeout (20 SECONDS)

**Comment by kn3-git** [comment]
This is found due to insufficient resources or IPs from the DHCP.
If that is the case, error needs to be reported on the user end and this task needs to be ended gracefully.

**Comment by rocknes** [comment]
Hi,

The CSE list operation is directly dependent on the GET /api/query?type=vApp&metadata... vCD query. This query can take upwards of 5 seconds even for just 4-5 clusters. On top of that CSE 2.6.1 has few un-optimized workflow paths which end up making N+1 queries for cluster/org vdc list (where N= number of the items). We have addressed most of these issue in the upcoming CSE 3.0 release.

Regards
Aritra Sen

**Comment by kn3-git** [comment]
I think we discussed on this offline and can be closed.
Thanks for reverting on this!
