### ISSUE TITLE
Cosmetic issues with CSE cluster list UI page

### ISSUE THREAD

**Issue by kn3-git** [vmware/container-service-extension#701]
Page reports the total number of pagination pages, but not the total number of items.
Bottom right corner of the page looks skewed and the navigation buttons are duplicate.

![image](https://user-images.githubusercontent.com/69351547/90368769-3950eb80-e088-11ea-943a-de0869c13113.png)

**Comment by rocknes** [comment]
@andrew-ni can you please take a look at this?

Regards
Aritra Sen

**Comment by andrew-ni** [comment]
@kn3-git  Hi! This older version of CSE UI plugin is missing the total number of clusters and the current number of clusters displayed on screen.

As of CSE UI plugin 2.0.0 (releasing with next release of VCD), this view will show both the total number of pagination pages as well as the total number of clusters/current set of clusters. The funky looking navigation buttons are a known issue and unfortunately can't be fixed yet. We haven't had the time this release to update our version of Angular/clarity, but that is high priority for us. Until we upgrade, this error will be there :(
