### ISSUE TITLE
0.4.2 Ubuntu template preparation failure

### ISSUE THREAD

**Issue by jondwaite** [vmware/container-service-extension#72]
Attempting to update our Ubuntu-16.04 templates for CSE 0.4.2 the 'Customization' process from config.py fails every time at the same point (log attached):

[ubuntu-16.04-failed-customization.txt](https://github.com/vmware/container-service-extension/files/1749746/ubuntu-16.04-failed-customization.txt)

It appears to be an issue with the (redirected) https request from https://cloud.weave.works/ resulting in a 400 Bad Request error.

Have confirmed that the box running CSE (and the network where the template is being prepared) can both see/access the https://cloud.weave.works/ site.

The lines in config.py that appear to be causing this are below (specifically the 2nd line):
```
export kubever=$(kubectl version --client | base64 | tr -d '\n')
wget -O weave.yml "https://cloud.weave.works/k8s/net?k8s-version=$kubever&version=2.1.3"

curl -L git.io/weave -o /usr/local/bin/weave
chmod a+x /usr/local/bin/weave
```

**Comment by jondwaite** [comment]
This appears to be due to the constructed URI for cloud.weave.works having the 'version=2.1.3' specification at the end of it.

Changing this to 'v=2.1.3' (matching the documentation on the weave website) appears to fix the issue:
`wget -O weave.yml "https://cloud.weave.works/k8s/net?k8s-version=$kubever&v=2.1.3"`

Just running some testing now to confirm this 'fix'.

**Comment by pacogomez** [comment]
It seems like they might have changed the param name, we'll update the script to fix it. Thanks for letting us know.

**Comment by jondwaite** [comment]
Should have mentioned - this is in scripts/cust-ubuntu-16.04.sh (but you'd probably worked that out already)
