### ISSUE TITLE
CSE is support NSX-V?

### ISSUE THREAD

**Issue by sklive** [vmware/container-service-extension#733]
CSE is support NSX-V?

**Comment by rocknes** [comment]
Hi,

CSE doesn't interact with NSX directly. So if the vCD you are using supports NSX-V, and the vCD is supported by CSE, everything should work as usual. Side note, vCD traditionally has supported only NSX-V. It's only starting vCD 10.0 that NSX-T support was added in. So, I believe the answer to your question is a +ve.

Regards
Aritra Sen
