### ISSUE TITLE
what happens behind the scene when we create a CSE Cluster?

### ISSUE THREAD

**Issue by hiteshsharma0** [vmware/container-service-extension#739]
I want to understand the actions which happens behind the scene when a new cluster is created. Here is my understanding.

Whenever we create a CSE cluster, first the cluster vApp gets created, writes the origin id and other metadata information for that vapp and then the master node in the vApp gets deployed using either the default template name and the revision number  which you defined in the config.yaml or you can as usual also override them by defining flags in the vcd cli. Once the master node gets created using the templates, it pushes customization scripts like init.sh, cust.sh and mstr.sh. If I read these shell scripts, 

Init.sh does the root password customization
Cust.sh does the iptables chains modification, update the system packages from internet, install kubernetes, docker, NFS daemon and weavenet plugin.
Mstr.sh does the initialization of the kubernetes cluster from the master node

Once these steps are complete, it starts deployment of the nodes in parallel using the templates and pushes init.sh, cust.sh, nfsd.sh scripts for post customization. It is then node.sh script which is pushed and do the addition of the worker nodes to the cluster.

If my above understanding is correct, I have two questions to ask:-

1.	Does it download any packages from internet(I saw dnf update command in one of the scripts) ? 
2.	Are these custom scripts pushed during the template creation and runs from the template itself? Or Are they pushed from the CSE server during the deployment time?  

I am struggling to reduce the CSE cluster deployment time from quite some time and would like you to please respond to this as early as possible as certain discussions are waiting the results.

**Comment by sahithi** [comment]
Hi Hitesh,

At a high-level, your understanding is correct.

1. Template creation scripts are _cust.sh_ and _init.sh_. The script _cust.sh_ downloads software from the internet.
2. Cluster initialization scripts are _mstr.sh_, _node.sh_ and _nfsd.sh_. They get run during the cluster creation. The script _mstr.sh_ runs the command _kubeadm init_, which may also attempt to download Kubernetes software from the internet.

Hope this helps. Let me know if you have any more questions.

**Comment by PradeepRanjan18** [comment]
Hello Sahithi,

This is regarding your response on point.2 

As per my  understanding, during cluster creation, there is no need of internet. could you please confirm the same from your side.

**Comment by sahithi** [comment]
>As per my understanding, during cluster creation, there is no need of internet. could you please confirm the same from your side.
This is no longer true. As I mentioned, the Kubernetes command _kubeadm init_ downloads the required components from the internet. Note this is a change in the command behavior of _kubeadm_ itself.

**Comment by PradeepRanjan18** [comment]
Thank you sahithi for confirmation :)
