### ISSUE TITLE
Cluster fails to configure - /root/weave.yml

### ISSUE THREAD

**Issue by jondwaite** [vmware/container-service-extension#77]
Just updated templates & CSE to 1.0.0 release and recomposed photon-v2 template. Template preparation / publish to catalog process completes without errors.

Attempting to deploy a new cluster based on photon-v2 template gives:

```
vcd cse cluster create mycluster --nodes 3 --template photon-v2 --cpu 2 --memory 4096 --ssh-key .ssh\id_pub --network "mynetwork" --storage-profile "mystorage"
create_cluster: Creating cluster mycluster(592ea858-1fc9-46eb-b7f4-c781e0ea5727)
create_cluster: Creating cluster vApp mycluster(592ea858-1fc9-46eb-b7f4-c781e0ea5727)
create_cluster: Creating master node for mycluster(592ea858-1fc9-46eb-b7f4-c781e0ea5727)
create_cluster: Initializing cluster mycluster(592ea858-1fc9-46eb-b7f4-c781e0ea5727)
task: 8eea1b16-82c4-437b-9482-37dc0511295f, result: error, message: Couldn't initialize cluster:
[preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 17.06.0-ce. Max validated version: 17.03
error: error validating "/root/weave.yml": error validating data: ValidationError(DaemonSet.spec.template.spec): unknown field "minReadySeconds" in io.k8s.api.core.v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

Appears to be a mismatch in the latest template provisioning between weave & Docker versions (?)

Have left this cluster in current state (with master node only deployed) if needed for further troubleshooting.

**Comment by pacogomez** [comment]
We'll take a look and issue a patch if necessary, thanks for reporting

**Comment by pacogomez** [comment]
on the master, can you show the output of `kubectl version`? can you also provide the contents of `/root/weave.yml`? thanks

**Comment by jondwaite** [comment]
kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+f38e43b221d08", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"not a git tree", BuildDate:"2018-01-31T18:59:49Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

/root/weave.yml attached as quite long:
[weave.yml.txt](https://github.com/vmware/container-service-extension/files/1808007/weave.yml.txt)

**Comment by jondwaite** [comment]
It appears this may be caused by the 'minReadySeconds' change referenced in this: [https://github.com/weaveworks/weave/issues/3257](url) - doing some testing now to confirm.

**Comment by jondwaite** [comment]
Can confirm that updating the photon-v2 template now the weave issue referenced above has been rolled back results in clusters deploying correctly, closing this issue.
