### ISSUE TITLE
Query on New released templates

### ISSUE THREAD

**Issue by sanjeevgorai** [vmware/container-service-extension#798]
Hello All

We have seen that new templates are released on Oct 8 2020 as shown in below link. Just want to confirm that these templates are compatible  to both CSE 2.5.1 as well as CSE 2.6.1.

https://vmware.github.io/container-service-extension/cse2_6/TEMPLATE_ANNOUNCEMENTS.html

**Comment by andrew-ni** [comment]
Hello @sanjeevgorai . Those templates are compatible with both CSE Server versions
