### ISSUE TITLE
Inter operability of new released templates with CSE 2.5.1

### ISSUE THREAD

**Issue by sanjeevgorai** [vmware/container-service-extension#807]
Hello All,
Could any one please confirm if the new released templates on  8-Oct-20 as shown in below link is compatible with  CSE 2.5.1.
https://vmware.github.io/container-service-extension/cse2_6/TEMPLATE_ANNOUNCEMENTS.html

Thanks in anticipation.

**Comment by rocknes** [comment]
Hi,

Yes, the new templates are compatible with CSE 2.5.1 and vCD 10.0.0.

Regards
Aritra Sen
