### ISSUE TITLE
A couple of questions.

### ISSUE THREAD

**Issue by heinoskov** [vmware/container-service-extension#82]
Hi All,

I'm looking to install CSE in our test platform in the coming weeks. Reading through the documentations a few questions pops up:

1. I see different versions of Docker and Kubernetes running in PhotonOS and Ubuntu... which is the recommended path to take? - Is PhotonOS going to be the main OS going forward - or?

2. After installing CSE - is it supported to upgrade vCloud Director when new releases comes out? - any issues with this?

3. If you in vCD have # number of PVDCs with their own VDC for Catalogs - is it supported to have a CSE catalog/templates in each of these - to allow each of the tenants in all of the PVDCs to deploy a kubernetes cluster?

Thanks in advance for your help :-)

**Comment by sahithi** [comment]
1. As of today, Ubuntu supports more functionality like NFS persistent volumes. We will soon catch up on PhotonOS.
2. 95% yes. We will address any new issues as new vCD versions come out.
3. Possible with few tweaks from admin side.

**Comment by sompa** [comment]
Feel free to reopen this issue again if you have any more queries.
