### ISSUE TITLE
1.1.0 version is not available from packages, no github release tag exists

### ISSUE THREAD

**Issue by luzhkovvv** [vmware/container-service-extension#83]
- Documentation at https://vmware.github.io/container-service-extension/#release-notes states:
CSE 1.1.0
Release date: 2018-04-20
- Documentation at https://vmware.github.io/container-service-extension/#installation states two ways to install cse:
`pip3 install --user container-service-extension`
and
`pip3 install --user git+https://github.com/vmware/container-service-extension.git@0.3.0`
- Both ways can only provide you with 1.0.0 version, as that's the last version published to packages, and 1.0.0 is latest release/tag for project on GitHub.
- It's not clear, if latest April 20 commit is intended to be finished 1.1.0 version, and if following install may be used:
`pip3 install --user git+https://github.com/vmware/container-service-extension.git@8a7777830b63bda59baec75797c7b64b5dd8e4c3`

**Comment by sahithi** [comment]
Yes, we will be pushing 1.1.0 soon. Sorry, for the confusion.

**Comment by jon-waite** [comment]
Any update on this? We'd like to push 1.1.0 from pip and don't really want to have to muck around with manually overriding.

**Comment by sahithi** [comment]
1.1.0 is out already. Please check.
