### ISSUE TITLE
CSE Installation Challenge

### ISSUE THREAD

**Issue by AneeqAbid06** [vmware/container-service-extension#831]
Hi,

Can you please advise me on the following issue I am facing while installing CSE:

VCD-CLI/Profile.yaml file fails to create automatically after installation of CSE modules and running the command "vcd version"

**Comment by Anirudh9794** [comment]
Did you try logging in back to vcd again using `vcd login` command?

**Comment by AneeqAbid06** [comment]
Hi @Anirudh9794 ,

This file is supposed to be created on vcd? I am supposed to run this command on vcd? I am doing everything on CSE server which is a separate VM I have installed. When I run the command "vcd version" on CSE machine it gives me a correct response.

**Comment by Anirudh9794** [comment]
Hello Aneeq,
This file should exist to be on the machine which is running `vcd ...` commands. If you are using a separate VM to run vcd-cli, `~/.vcd-cli/profiles.yaml` should be present in that vm.

This file, if not present, will be automatically created during vcd login. Can you please try logging in again using - `vcd login` command?

Thank you,

**Comment by AneeqAbid06** [comment]
Hi @Anirudh9794 ,

The vcd login command requires a host, and organization and a user. Can you please guide what are the parameter definitions? Is the host corresponding to my vcd server? Do I have to create an org first in vcd to pass as the parameter? User is for the org or an admin user of the vcd?

**Comment by Anirudh9794** [comment]
The host corresponds to the VCD host (can be the fqdn of the vcd server)
Organization is the org where you would want to login. A provider can login to a default org called 'system'.
User is the name of the user with which you want to login as. A default user called 'administrator' with all rights will already be present.
If you want to login as a provider, you can use the org as system and user as administrator.
If you want to login as a tenant, the provider needs to create an org first and then create a user for the org to login.

**Comment by AneeqAbid06** [comment]
Hi @Anirudh9794 ,

Thank you so much your support. When I login accordingly, I am receiving the following error:

Error: HTTPSConnectionPool(host='<VCD-FQDN>', port=443): Max retries exceeded with url: /api/versions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff461b81910>: Failed to establish a new connection: [Errno -2] Name or service not known'))

I used VCD FQDN and tried multiple options by logging into System Org and Administrator account and then a Tenant Org using a locally created user in that Org. The error remains same nonetheless. Can you share any insights into this?

**Comment by Anirudh9794** [comment]
Can you please post the format of the login command you are using?
Are you using self signed certificates? if so, you don't have to pass `-i` flag in the login command.

After some googling, I found out that this can happen because of some firewall rule in the machine you are using to connect to vcd. Can you please check this too? https://stackoverflow.com/questions/14818740/python-connectionerror-max-retries-exceeded

**Comment by AneeqAbid06** [comment]
Hi @Anirudh9794 ,

I am using the following command:
vcd login *****.com.pk Demo-org aneeq.abid --password ********

Demo org is a tenant org and aneeq.abid is a user for that tenant org. The FQDN for the HOST paramter in the command is the FQDN of my cell 1 of VCD. I have total 3 cells in my environment. I have tried connecting to all of them. I have tried running this command with different flags as well but the error remains unaffected.

Firewall was Active on my CSE server from where I am running this command. Upon your advise, I have disabled it now but the error is the same.

I am not using any certificate on my CSE server. However, the VCD server I am trying to connect has a wildcard certificate which is not self signed btw.

Do I need to ensure some other settings or configurations now based on this information to be able to connect successfully?

**Comment by Anirudh9794** [comment]
I can see that the error says 'Name or service not known'. So, this can be a DNS issue. Can you please check if the FQDN is properly getting resolved in the machine you are trying to use vcd cli?
Can you also check if VCD is running at the Domain you are trying? Are you able to access VCD UI?
Can you also try using the IP address instead of the FQDN in the VCD login command?

**Comment by AneeqAbid06** [comment]
Hi @Anirudh9794 ,

You were right. The DNS was not resolving the hostname. Adding the right DNS has resolved the issue and I can now reach my vcd server from my cse machine.  

The login is now showing me a certificate error. I believe I need to verify the SSL certificate settings installed in my vcd server to resolve this right?

Error: HTTPSConnectionPool(host='Hostname/IP', port=443): Max retries exceeded with url: /api/versions (Caused by SSLError(CertificateError("hostname 'Hostname/IP' doesn't match either of '*.com.pk', '.com.pk'",),))

**Comment by Anirudh9794** [comment]
Closing this issue as it was a DNS isssue.
