### ISSUE TITLE
VCD login Error

### ISSUE THREAD

**Issue by AneeqAbid06** [vmware/container-service-extension#836]
Need Help ! Trying to login to vcd from cse server gives the following error:

# vcd login https://subdomain.domain.com.pk Demo-org Demo.user

Error: HTTPSConnectionPool(host='subdomain.domain.com.pk', port=443): Max retries exceeded with url: /api/versions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff461b81910>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by Anirudh9794** [comment]
Related to the issue https://github.com/vmware/container-service-extension/issues/831 . Closing this issue as it is a duplicate
