### ISSUE TITLE
CSE 3.0 installation fails

### ISSUE THREAD

**Issue by sreejesh-d** [vmware/container-service-extension#848]
CSE installation fails with following error. does CSE server need access to the host? if so can you please give the port details. There is a firewall between CSE server and ESXi host.

I couldn't locate the folder cse-logs  in the base OS (Centos 7). where is that folder located? also, please let me know the default username and password for the Ubunut and photon OS templates? 

`Waiting for guest tools, status: "vm='vim.VirtualMachine:vm-5326', status=guestToolsNotRunning
Waiting for guest tools, status: "vm='vim.VirtualMachine:vm-5326', status=guestToolsRunning
Failed VM customization. Check CSE install log
CSE Installation Error. Check CSE install logs
HTTPSConnectionPool(host='esxi-123', port=443): Max retries exceeded with url: /guestFile?id=5&token=52c89558-629b-1036-b707-455b32ccf5445 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa758687a90>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

**Comment by sakthisunda** [comment]
1. cse-logs folder for CSE 3.0 is under ~/.cse-logs (`cse-install_yyyy-mm-dd_hh-mm-ss.log, cse-install_wire_yyyy-mm-dd_hh-mm-ss.log`).
2. cse-logs folder for CSE 2.6.x is under /cse-logs (`cse-install_yyyy-mm-dd_hh-mm-ss.log, cse-install_wire_yyyy-mm-dd_hh-mm-ss.log`). It is relative path from where you execute install command.

Password based login to template is disabled.  Please try either of the following if you want to login to template.

1. Try installing with ssh-key option

```
cse install --ssh-key FILENAME 
cse template install --ssh-key FILENAME
```

2. Use `ssh -i <ssh-file> ` should let you login without password

By default, the vSphere uses  HTTPS port 443 to communicate with ESX/ESXi hosts.

**Comment by sreejesh-d** [comment]
thanks for the answers, much appreciated.

The vCenter already have access to esxi hosts on 443 and CSE server has access to vCenter on 443. But CSE server doesn't have access to ESXi host on 443. Does CSE server need access to ESXi hosts directly? The error shows guest customization failed.

**Comment by sakthisunda** [comment]
Guest customization failure is due to `connection error `. 
To check if this is an intermittent error, you may want to retry install again. 
Also, check the log file for any error message

**Comment by sreejesh-d** [comment]
thank you,

it was consistent, the issue is resolved after allowing from 443 from CSE server to ESXi hosts.
