### ISSUE TITLE
Fail when creating the cluster

### ISSUE THREAD

**Issue by Amdusis** [vmware/container-service-extension#86]
Hello!
During the creation the cluster i'm had the following error:

> 
create_cluster: Creating cluster k8k(9dbd7734-5fc2-4b29-8c0d-66f365da929d)
create_cluster: Creating cluster vApp k8k(9dbd7734-5fc2-4b29-8c0d-66f365da929d)
create_cluster: Creating master node for k8k(9dbd7734-5fc2-4b29-8c0d-66f365da929d)
create_cluster: Initializing cluster k8k(9dbd7734-5fc2-4b29-8c0d-66f365da929d)
create_cluster: Creating 1 node(s) for k8k(9dbd7734-5fc2-4b29-8c0d-66f365da929d)
create_cluster: Adding 1 node(s) to k8k(9dbd7734-5fc2-4b29-8c0d-66f365da929d)
task: 5a11126a-35ae-4758-be33-3a01956dd1cb, result: error, message: list index out of range
> 

> 
06-14 10:11:44 cse.cluster  373 DEBUG   failed to load admin kubeconfig [open /etc/kubernetes/admin.conf: no such file or directory]

06-14 10:11:44 cse.cluster  374 DEBUG    10.0.10.10

06-14 10:11:44 cse.config   334 ERROR    Data file not found: None
06-14 10:11:44 cse.broker   476 ERROR    Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/container_service_extension/broker.py", line 470, in create_cluster_thread
    join_cluster(self.config, vapp, template)
  File "/root/.local/lib/python3.6/site-packages/container_service_extension/cluster.py", line 273, in join_cluster
    script = tmp_script.format(token=init_info[0], ip=init_info[1])
IndexError: list index out of range
> 

property              value
--------------------  ------------------------------------------------------
all_threads           6
config_file           ./.local/bin/config.yaml
consumer_threads      5
description           Container Service Extension for VMware vCloud Director
product               CSE
python                3.6.5
requests_in_progress  0
status                Running
version               1.0.0

Thanks!

**Comment by mgaruccio** [comment]
@daydrim I had this the other day, I ended up narrowing it down to either the Ubuntu customization silently failing or CSE not liking the Photon template being missing.  Either way the problem was ultimately related to #145 and the data file not being found when running from within a venv.  check out - https://github.com/vmware/container-service-extension/issues/145#issuecomment-434964458 for a potential workaround.  hope that helps.
