### ISSUE TITLE
VCD 10.2 and CSE 3.0. Reinstall ui plugin 2.0

### ISSUE THREAD

**Issue by work423** [vmware/container-service-extension#865]
Unfortunately from customization portal i removed build-in cse plugin which ships with vcd 10.2. But have no idea how to install it again.
cse install or cse upgrade does not install ui-plugin again. How can i solve it ? 
Thanks!

# cse ui-plugin list -c config.yaml -s
Retrieved config from 'config.yaml'
name                                vendor    version         id
----------------------------------  --------  --------------  --------------------------------------------------------
Operations Plugin                   VMware    2.4.0           urn:vcloud:uiPlugin:67514268-6fdc-4b46-828d-589aa4f7ce0f
VMware Cloud Director Availability  VMware    4.0.0           urn:vcloud:uiPlugin:f2fb629c-4716-4f37-9c9f-0c6c12f7584c
Customize Portal                    VMware    2.0.2           urn:vcloud:uiPlugin:3877deb6-1ef5-47e9-af52-6aaad661810c
Guided Tours plugin                 VMware    1.0.0           urn:vcloud:uiPlugin:3bf8ec5d-c85d-47a0-9c90-216cbc26491e
CPOM extension                      VMware    0.0.2           urn:vcloud:uiPlugin:3e5d6c74-5239-4d2d-a2b2-578684df8057
CPOM extension                      VMware    1.1.0           urn:vcloud:uiPlugin:288fbee3-103e-456b-8061-d1f4764a8dcb
CPOM extension                      VMware    1.2.0           urn:vcloud:uiPlugin:5b977e28-5b3a-443e-badd-5728be87acad
Customize Portal                    VMware    2.0.0           urn:vcloud:uiPlugin:7bf57d34-d3c4-4a04-bcc1-49fe19d6360b
App Launchpad                       VMware    2.0.0-17029135  urn:vcloud:uiPlugin:7f2dd562-3d75-4044-b60d-78ddaddc791d

**Comment by Anirudh9794** [comment]
Hello,
You need to use the `cse ui-plugin` cli or `Customize Portal` in the UI to register the plugin. More details - https://vmware.github.io/container-service-extension/cse3_0/CSE_UI_PLUGIN.html

Thank you,
Aniruddha
