### ISSUE TITLE
Sample Config YAML File Error

### ISSUE THREAD

**Issue by AneeqAbid06** [vmware/container-service-extension#873]
Hi,

I am running the command **cse sample -o config.yaml** but the file is not being generated. There is no output for the command **cse sample** as well.

**Comment by ltimothy7** [comment]
Hi @AneeqAbid06,
Thank you for your post. Would you please let us know which cse version you have (run `cse version`)?

**Comment by AneeqAbid06** [comment]
Hi @ltimothy7

Yes, please see details of the CSE version below:

# cse version
CSE, Container Service Extension for VMware vCloud Director, version 3.0.1

Kindly guide further.

**Comment by ltimothy7** [comment]
Hi @AneeqAbid06,

Would you please try the following to see if this helps?

1. Please try re-running the command
2. Make sure you are not running the command in a write-protected folder
3. Buffering could be causing this issue, so please edit "~/.virtualenvs/cse/bin/cse" to flush stdout
4. If none of the above work, please trace the command and attach the file: `python -m trace -t /path/to/cse/bin/file/cse sample -o config.yaml | grep -v "frozen importlib._bootstrap" > cse_sample.trace`

**Comment by goelaashima** [comment]
@AneeqAbid06 

Were you able to get passed above?

If you are still seeing this issue, please reopen.

Aashima
