### ISSUE TITLE
How trust Vmware about containers orchestration system provisioning tools ?

### ISSUE THREAD

**Issue by vahric** [vmware/container-service-extension#88]
Hello, 

For a long time fallowing Vmware about their strategy about containers. First it started with Photon OS then Photon Controller is arrived and right now CSE.
I didn't check for a long time for Photon Controller, I saw that related project not maintained by Vmware.
CSE also kind a another dream of Vmware ? it will over like Photon Controller in feature ? 

VM

**Comment by goelaashima** [comment]
Hi there!

CSE is an extension to VMware vCloud Director product which facilitates the bootstrapping and lifecycle management of Kubernetes Clusters on VMware vCloud Director powere Clouds. We support Ubuntu based operating systems for K8s cluster deployments, just as well as, VMware PhotoOS based operating systems.

I hope this clarifies any confusion you might have on your end. Thanks for reaching out, btw.

Aashima
