### ISSUE TITLE
Why only Weave support ? not nsx or flannel support ? 

### ISSUE THREAD

**Issue by vahric** [vmware/container-service-extension#89]
Hello,

K8s support many networking backend, why CSE force to use only weave not flannel or Vmware own product nsx ? 

Regards
VM

**Comment by sahithi** [comment]
Weave was chosen for first version of CSE. We will consider supporting other softwares soon.

If this is your immediate need, we encourage you to contribute to the project (with our guidance).

**Comment by sompa** [comment]
Feel free to reopen this issue if you have further queries.
