### ISSUE TITLE
Cluster upgrade fails when cluster has NFS nodes

### ISSUE THREAD

**Issue by andrew-ni** [vmware/container-service-extension#890]
The affected code is in cluster_service.py in the _upgrade_cluster_async() function. 

The way I had implemented this was that if docker or CNI needed to be upgraded, then all node names were fetched, and the kubectl drain command was run on those node names. However, the node names are fetched by iterating through the vApp and getting the name property, and this includes NFS nodes. NFS nodes are not part of the cluster, so the drain fails with the unrecognized NFS node. This specific workflow - upgrading cluster with NFS node - wasn’t tested.

The fix for this should be to exclude NFS nodes when fetching all node names.

![image](https://user-images.githubusercontent.com/29108945/105888998-85527580-5fc2-11eb-887b-2819b9eca426.png)

**Comment by goelaashima** [comment]
Resolved in CSE 3.0.2
