### ISSUE TITLE
CSE 3.0.1 Server Support OS for deployment and Compute Sizing

### ISSUE THREAD

**Issue by viveksingh2323** [vmware/container-service-extension#893]
We are about to start CSE 3.0.1 deployment however in CSE documentation we were looking for below two information:

Supported Operating System and version for CSE Server Installation.  
Any guideline for sizing CSE Server e.g. on what basis we can decide memory/cpu/storage requirement for CSE.

**Comment by Anirudh9794** [comment]
Hi @viveksingh2323 ,
CSE server can be installed in Windows, MacOS or linux with recommended version of python i.e 3.7.3 or greater. (Although one of the libraries we are using has issues with python 3.8. So, Python 3.7.9 should work fine)
As far as the sizing requirements are concerned, CSE needs memory to store some OVA. We recommend the following configuration at a bare minimum -
2 core cpu with 2 Ghz, 2GB memory and 10 GB storage
