### ISSUE TITLE
Failed to authenticate with the guest operating system using the supplied credentials.

### ISSUE THREAD

**Issue by jkfletch02** [vmware/container-service-extension#973]
CSE upgrade failing using the VMware container-service-extension-templates list.

OS: CentOS 8.3.2011
Python: 3.8.3
vCenter: 6.7
Director: 10.2
CSE: 3.0.1
vcd-cli, VMware vCloud Director Command Line Interface, 24.0.0

Output from cse-install log.
> 21-03-25 15:08:23 | vsphere_utils:94 - callback | INFO :: Waiting for guest tools, status: "vm='vim.VirtualMachine:vm-17897', status=guestToolsRunning
21-03-25 15:08:25 | template_builder:326 - _customize_vm | ERROR :: Failed VM customization with error: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
Traceback (most recent call last):
  File "/root/test01/lib64/python3.8/site-packages/container_service_extension/template_builder.py", line 307, in _customize_vm
    result = vs.execute_script_in_guest(
  File "/root/test01/lib64/python3.8/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/root/test01/lib64/python3.8/site-packages/vsphere_guest_run/vsphere.py", line 137, in upload_file_to_guest
    url = content.guestOperationsManager.fileManager. \
  File "/root/test01/lib64/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/root/test01/lib64/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/root/test01/lib64/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vim.fault.InvalidGuestLogin: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
21-03-25 15:08:25 | configure_cse:1445 - upgrade_cse | ERROR :: CSE Installation Error
Traceback (most recent call last):
  File "/root/test01/lib64/python3.8/site-packages/container_service_extension/configure_cse.py", line 1422, in upgrade_cse
    _upgrade_to_35(
  File "/root/test01/lib64/python3.8/site-packages/container_service_extension/configure_cse.py", line 1600, in _upgrade_to_35
    _install_all_templates(
  File "/root/test01/lib64/python3.8/site-packages/container_service_extension/configure_cse.py", line 1048, in _install_all_templates
    _install_single_template(
  File "/root/test01/lib64/python3.8/site-packages/container_service_extension/configure_cse.py", line 1263, in _install_single_template
    builder.build(force_recreate=force_update,
  File "/root/test01/lib64/python3.8/site-packages/container_service_extension/template_builder.py", line 465, in build
    self._customize_vm(vapp, self.temp_vm_name)
  File "/root/test01/lib64/python3.8/site-packages/container_service_extension/template_builder.py", line 307, in _customize_vm
    result = vs.execute_script_in_guest(
  File "/root/test01/lib64/python3.8/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/root/test01/lib64/python3.8/site-packages/vsphere_guest_run/vsphere.py", line 137, in upload_file_to_guest
    url = content.guestOperationsManager.fileManager. \
  File "/root/test01/lib64/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/root/test01/lib64/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/root/test01/lib64/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vim.fault.InvalidGuestLogin: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []

**Comment by jkfletch02** [comment]
`cse template install '*' '*'` runs without issue.

**Comment by jkfletch02** [comment]
Attempting new cluster creation after doing errors out with...

> 21-03-26 14:49:22 | cluster_service:1766 - _init_cluster | Request Id: a0c75a7f-76b3-4ea5-83d6-c33aee64b65b | ERROR :: Error executing script in node mstr-l6vz: <module 'container_service_extension.exceptions' from '/usr/local/lib/python3.8/site-packages/container_service_extension/exceptions.py'>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 1873, in _execute_script_in_nodes
>     _wait_until_ready_to_exec(vs, vm, password)
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 1832, in _wait_until_ready_to_exec
>     result = vs.execute_script_in_guest(
>   File "/usr/local/lib/python3.8/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
>     self.upload_file_to_guest(vm, user, password, content, target)
>   File "/usr/local/lib/python3.8/site-packages/vsphere_guest_run/vsphere.py", line 137, in upload_file_to_guest
>     url = content.guestOperationsManager.fileManager. \
>   File "/usr/local/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
>     self.f(*(self.args + (obj,) + args), **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
>     return self._stub.InvokeMethod(self, info, args)
>   File "/usr/local/lib/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
>     raise obj # pylint: disable-msg=E0702
> pyVmomi.VmomiSupport.vim.fault.InvalidGuestLogin: (vim.fault.InvalidGuestLogin) {
>    dynamicType = <unset>,
>    dynamicProperty = (vmodl.DynamicProperty) [],
>    msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
>    faultCause = <unset>,
>    faultMessage = (vmodl.LocalizableMessage) []
> }
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 1756, in _init_cluster
>     result = _execute_script_in_nodes(sysadmin_client, vapp=vapp,
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 1900, in _execute_script_in_nodes
>     raise e.ScriptExecutionError(f"Error executing script in node {node_name}: {str(e)}")  # noqa: E501
> container_service_extension.exceptions.ScriptExecutionError: Error executing script in node mstr-l6vz: <module 'container_service_extension.exceptions' from '/usr/local/lib/python3.8/site-packages/container_service_extension/exceptions.py'>
> 21-03-26 14:49:22 | cluster_service:644 - _create_cluster_async | Request Id: a0c75a7f-76b3-4ea5-83d6-c33aee64b65b | ERROR :: Error creating cluster 'Demo-Cluster'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 1873, in _execute_script_in_nodes
>     _wait_until_ready_to_exec(vs, vm, password)
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 1832, in _wait_until_ready_to_exec
>     result = vs.execute_script_in_guest(
>   File "/usr/local/lib/python3.8/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
>     self.upload_file_to_guest(vm, user, password, content, target)
>   File "/usr/local/lib/python3.8/site-packages/vsphere_guest_run/vsphere.py", line 137, in upload_file_to_guest
>     url = content.guestOperationsManager.fileManager. \
>   File "/usr/local/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
>     self.f(*(self.args + (obj,) + args), **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
>     return self._stub.InvokeMethod(self, info, args)
>   File "/usr/local/lib/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
>     raise obj # pylint: disable-msg=E0702
> pyVmomi.VmomiSupport.vim.fault.InvalidGuestLogin: (vim.fault.InvalidGuestLogin) {
>    dynamicType = <unset>,
>    dynamicProperty = (vmodl.DynamicProperty) [],
>    msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
>    faultCause = <unset>,
>    faultMessage = (vmodl.LocalizableMessage) []
> }
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 1756, in _init_cluster
>     result = _execute_script_in_nodes(sysadmin_client, vapp=vapp,
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 1900, in _execute_script_in_nodes
>     raise e.ScriptExecutionError(f"Error executing script in node {node_name}: {str(e)}")  # noqa: E501
> container_service_extension.exceptions.ScriptExecutionError: Error executing script in node mstr-l6vz: <module 'container_service_extension.exceptions' from '/usr/local/lib/python3.8/site-packages/container_service_extension/exceptions.py'>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 560, in _create_cluster_async
>     _init_cluster(self.context.sysadmin_client,
>   File "/usr/local/lib/python3.8/site-packages/container_service_extension/def_/cluster_service.py", line 1767, in _init_cluster
>     raise e.ClusterInitializationError(
> container_service_extension.exceptions.ClusterInitializationError: Couldn't initialize cluster: Error executing script in node mstr-l6vz: <module 'container_service_extension.exceptions' from '/usr/local/lib/python3.8/site-packages/container_service_extension/exceptions.py'>
> 21-03-26 14:49:22 | cluster_service:649 - _create_cluster_async | Request Id: a0c75a7f-76b3-4ea5-83d6-c33aee64b65b | INFO :: Error creating cluster 'Demo-Cluster'. Deleting cluster (rollback=True)

**Comment by jkfletch02** [comment]
Also forgot to add, CSE check returns valid installation.

**Comment by sahithi** [comment]
Is this consistently reproducible? If not, can you please retry the operation?

**Comment by jkfletch02** [comment]
Can confirm that this occurs consistently.

**Comment by Anirudh9794** [comment]
Hello @jkfletch02 
CSE 3.0.4 adds timeouts to allow sufficient time for VCD to finish guest customization.
Please let us know if you are facing this issue after upgrading to CSE 3.0.4 and feel free to open the bug.

Thanks ,
Aniruddha
